Repository yunionio/ocboot, pull requests merged in 2020-08, with the labels that each got.

#7 checkout branches
  OWNERS
  hack/cherry_pick_pull.sh
  onecloud/roles/common/tasks/main.yml
Labels: size/L

#11 Automated cherry pick of #10: 解决 kmod-openvswitch rpm 安装等问题
  onecloud/roles/common/tasks/main.yml
Labels: size/M

#12 Automated cherry pick of #10: 解决 kmod-openvswitch rpm 安装等问题
  onecloud/roles/common/tasks/main.yml
Labels: size/M

#10 解决 kmod-openvswitch rpm 安装等问题
  onecloud/roles/common/tasks/main.yml
Labels: approved, lgtm, size/M

#14 不指定 yunion repo
  onecloud/roles/common/tasks/main.yml
Labels: size/XS

#15 Automated cherry pick of #14: 不指定 yunion repo
  onecloud/roles/common/tasks/main.yml
Labels: size/XS

#16 Automated cherry pick of #14: 不指定 yunion repo
  onecloud/roles/common/tasks/main.yml
Labels: size/XS
