Repository yunionio/ocboot, pull requests merged in 2021-07, with the labels that each got.

#160 fix: remove onecloud keyword in readme
  README.md
  lib/ssh.py
Labels: size/XS

#161 fix(deploy,kernel): 解决3.6升级3.7过程中找不到最新 kernel 的 bug
  lib/upgrade.py
  onecloud/roles/upgrade/common/tasks/v3_6-v3_7.yml
Labels: size/XS

#162 Automated cherry pick of #161: fix(deploy,kernel): 解决3.6升级3.7过程中找不到最新 kernel 的 bug
  lib/upgrade.py
  onecloud/roles/upgrade/common/tasks/v3_6-v3_7.yml
Labels: size/XS

#163 feat: add update-pciids step
  Makefile
  onecloud/install-cluster.yml
  onecloud/roles/utils/update-pciids/files/pci.ids
  onecloud/roles/utils/update-pciids/tasks/main.yml
  onecloud/upgrade-cluster.yml
Labels: approved, lgtm, size/XXL

#164 Automated cherry pick of #163: feat: add update-pciids step
  Makefile
  onecloud/install-cluster.yml
  onecloud/roles/utils/update-pciids/files/pci.ids
  onecloud/roles/utils/update-pciids/tasks/main.yml
  onecloud/upgrade-cluster.yml
Labels: approved, lgtm, size/XXL

#165 fix(reboot,k8s,host): 解决 host 节点不能重启的 bug
  onecloud/roles/primary-master-node/reboot/tasks/main.yml
  onecloud/roles/utils/kernel-check/tasks/main.yml
Labels: size/XS

#166 Automated cherry pick of #165: fix(reboot,k8s,host): 解决 host 节点不能重启的 bug
  onecloud/roles/primary-master-node/reboot/tasks/main.yml
  onecloud/roles/utils/kernel-check/tasks/main.yml
Labels: size/XS

#168 feat(deploy,gpu): 在 ocboot 里增加 gpu init 的步骤
  Makefile
  lib/install.py
  lib/ocboot.py
  onecloud/install-cluster.yml
  onecloud/roles/utils/gpu-init/files/functions
  onecloud/roles/utils/gpu-init/files/gpu_setup.sh
  onecloud/roles/utils/gpu-init/files/pci.ids
  onecloud/roles/utils/gpu-init/tasks/main.yml
  onecloud/roles/utils/update-pciids/tasks/main.yml
  onecloud/upgrade-cluster.yml
Labels: size/L

#169 Automated cherry pick of #168: feat(deploy,gpu): 在 ocboot 里增加 gpu init 的步骤
  Makefile
  lib/install.py
  lib/ocboot.py
  onecloud/install-cluster.yml
  onecloud/roles/utils/gpu-init/files/functions
  onecloud/roles/utils/gpu-init/files/gpu_setup.sh
  onecloud/roles/utils/gpu-init/files/pci.ids
  onecloud/roles/utils/gpu-init/tasks/main.yml
  onecloud/roles/utils/update-pciids/tasks/main.yml
  onecloud/upgrade-cluster.yml
Labels: size/L

#170 fix(arm,user): arm64 兼容 hotfix；安装时创建用户增加判断是否开源
  onecloud/roles/primary-master-node/setup_cloud/tasks/main.yml
  onecloud/roles/utils/detect-os/vars/uos-aarch64.yml
Labels: size/XS

#171 Automated cherry pick of #170: fix(arm,user): arm64 兼容 hotfix；安装时创建用户增加判断是否开源
  onecloud/roles/primary-master-node/setup_cloud/tasks/main.yml
  onecloud/roles/utils/detect-os/vars/uos-aarch64.yml
Labels: size/XS

#172 fix: install epel-release for ansible
  run.py
Labels: size/XS

#174 fix: config NetworkManager when install
  VERSION
  onecloud/roles/common/tasks/main.yml
  onecloud/roles/utils/config-network-manager/handlers/main.yml
  onecloud/roles/utils/config-network-manager/tasks/main.yml
Labels: size/M

#175 Automated cherry pick of #174: fix: config NetworkManager when install
  VERSION
  onecloud/roles/common/tasks/main.yml
  onecloud/roles/utils/config-network-manager/handlers/main.yml
  onecloud/roles/utils/config-network-manager/tasks/main.yml
Labels: size/M
