Repository yunionio/ocboot, pull requests merged in 2021-09, with the labels that each got.

#201 fix(upgrade,kernel): 版本升级时，确保新内核生效
  onecloud/upgrade-cluster.yml
Labels: size/XS

#202 Automated cherry pick of #201: fix(upgrade,kernel): 版本升级时，确保新内核生效
  onecloud/upgrade-cluster.yml
Labels: size/XS

#203 Automated cherry pick of #201: fix(upgrade,kernel): 版本升级时，确保新内核生效
  onecloud/upgrade-cluster.yml
Labels: size/XS

#215 fix: use ocadm replace kubeadm update certs
  onecloud/roles/utils/controlplane/tasks/main.yml
Labels: size/S

#216 Automated cherry pick of #215: fix: use ocadm replace kubeadm update certs
  onecloud/roles/utils/controlplane/tasks/main.yml
Labels: size/S

#217 Automated cherry pick of #215: fix: use ocadm replace kubeadm update certs
  onecloud/roles/utils/controlplane/tasks/main.yml
Labels: size/S

#218 Automated cherry pick of #215: fix: use ocadm replace kubeadm update certs
  onecloud/roles/utils/controlplane/tasks/main.yml
Labels: size/S

#219 fix(py,trim): 更新 pip requirements；更新 python imports
  lib/backup.py
  lib/cmd.py
  lib/db.py
  lib/restore.py
  requirements.txt
Labels: size/S

#220 Automated cherry pick of #219: fix(py,trim): 更新 pip requirements；更新 python imports
  lib/backup.py
  lib/cmd.py
  lib/db.py
  lib/restore.py
  requirements.txt
Labels: size/S

#221 Automated cherry pick of #219: fix(py,trim): 更新 pip requirements；更新 python imports
  lib/backup.py
  lib/cmd.py
  lib/db.py
  lib/restore.py
  requirements.txt
Labels: size/S

#223 fix(ssh,paramiko): 解决升级过程中，paramiko 丢失 env 变量的问题
  lib/ssh.py
Labels: size/XS

#224 Automated cherry pick of #223: fix(ssh,paramiko): 解决升级过程中，paramiko 丢失 env 变量的问题
  lib/ssh.py
Labels: size/XS

#225 Automated cherry pick of #223: fix(ssh,paramiko): 解决升级过程中，paramiko 丢失 env 变量的问题
  lib/ssh.py
Labels: size/XS

#222 feat(deploy,offline): ocboot 支持离线部署方案，since 3.7
  lib/ocboot.py
  lib/utils.py
  onecloud/roles/common/tasks/main.yml
  onecloud/roles/common/tasks/master.yml
  onecloud/roles/common/tasks/v3_4.yml
  onecloud/roles/common/tasks/v3_6.yml
  onecloud/roles/common/tasks/v3_7.yml
  onecloud/roles/mariadb/tasks/main.yml
  onecloud/roles/pre-install-common/tasks/main.yml
  onecloud/roles/registry/tasks/main.yml
  onecloud/roles/upgrade/common/tasks/v3_4-v3_6.yml
Labels: size/S

#226 Automated cherry pick of #222: feat(deploy,offline): ocboot 支持离线部署方案，since 3.7
  lib/ocboot.py
  lib/utils.py
  onecloud/roles/common/tasks/main.yml
  onecloud/roles/common/tasks/v3_4.yml
  onecloud/roles/common/tasks/v3_6.yml
  onecloud/roles/common/tasks/v3_7.yml
  onecloud/roles/mariadb/tasks/main.yml
  onecloud/roles/pre-install-common/tasks/main.yml
  onecloud/roles/registry/tasks/main.yml
  onecloud/roles/upgrade/common/tasks/v3_4-v3_6.yml
Labels: size/S

#227 Automated cherry pick of #222: feat(deploy,offline): ocboot 支持离线部署方案，since 3.7
  lib/ocboot.py
  lib/utils.py
  onecloud/roles/common/tasks/main.yml
  onecloud/roles/common/tasks/master.yml
  onecloud/roles/common/tasks/v3_4.yml
  onecloud/roles/common/tasks/v3_6.yml
  onecloud/roles/common/tasks/v3_7.yml
  onecloud/roles/mariadb/tasks/main.yml
  onecloud/roles/pre-install-common/tasks/main.yml
  onecloud/roles/registry/tasks/main.yml
  onecloud/roles/upgrade/common/tasks/v3_4-v3_6.yml
Labels: size/S

#228 fix(arm64,reboot,deploy): arm64 开源部署重启判断更新
  lib/install.py
  lib/kernel_utils.py
  onecloud/roles/utils/gpu-init/tasks/main.yml
Labels: size/S

#229 Automated cherry pick of #228: fix(arm64,reboot,deploy): arm64 开源部署重启判断更新
  lib/install.py
  lib/kernel_utils.py
  onecloud/roles/utils/gpu-init/tasks/main.yml
Labels: size/S

#230 Automated cherry pick of #228: fix(arm64,reboot,deploy): arm64 开源部署重启判断更新
  lib/install.py
  lib/kernel_utils.py
  onecloud/roles/utils/gpu-init/tasks/main.yml
Labels: size/S

#231 fix(hotfix,minor): 增补3.8文件到 master
  onecloud/roles/common/tasks/v3_8.yml
  onecloud/roles/upgrade/common/tasks/v3_7-v3_8.yml
Labels: size/M

#233 Automated cherry pick of #232: feat(kernel,debian): install 5.10 kernel for debian since release/3.8
  lib/install.py
  lib/kernel_utils.py
  onecloud/roles/common/tasks/master.yml
  onecloud/roles/common/tasks/v3_8.yml
  onecloud/roles/mariadb/tasks/main.yml
  onecloud/roles/primary-master-node/reboot/tasks/main.yml
  onecloud/roles/utils/detect-os/vars/centos-x86_64.yml
  onecloud/roles/utils/kernel-check/tasks/main.yml
Labels: size/L

#232 feat(kernel,debian): install 5.10 kernel for debian since release/3.8
  VERSION
  lib/install.py
  lib/kernel_utils.py
  onecloud/roles/common/tasks/master.yml
  onecloud/roles/common/tasks/v3_8.yml
  onecloud/roles/mariadb/tasks/main.yml
  onecloud/roles/primary-master-node/reboot/tasks/main.yml
  onecloud/roles/utils/detect-os/vars/centos-x86_64.yml
  onecloud/roles/utils/kernel-check/tasks/main.yml
Labels: size/L

#234 minor update version tag
  VERSION
Labels: size/XS

#236 fix(kernel,upgrade,update): 低版本升级到3.8时，保持当前内核，不对内核进行升级
  onecloud/roles/upgrade/common/tasks/v3_7-v3_8.yml
Labels: size/XS

#237 Automated cherry pick of #236: fix(kernel,upgrade,update): 低版本升级到3.8时，保持当前内核，不对内核进行升级
  onecloud/roles/upgrade/common/tasks/v3_7-v3_8.yml
Labels: size/XS
