Repository yunionio/ocboot, pull requests merged in 2021-03, with the labels that each got.

#40 chore(readme): update version
  README.md
  lib/upgrade.py
Labels: size/S

#41 Automated cherry pick of #40: chore(readme): update version
  README.md
  lib/upgrade.py
Labels: size/S

#42 fix(readme): install requirements
  README.md
  requirements.txt
Labels: size/XS

#43 Automated cherry pick of #42: fix(readme): install requirements
  README.md
  requirements.txt
Labels: size/XS

#45 feat(config): set default onecloud role config
  lib/ocboot.py
Labels: size/XS

#46 Automated cherry pick of #45: feat(config): set default onecloud role config
  lib/ocboot.py
Labels: size/XS

#39 兼容 arm64 部署
  lib/ocboot.py
  lib/utils.py
  onecloud/roles/common/files/apt.yunion.list
  onecloud/roles/common/tasks/main.yml
  onecloud/roles/common/tasks/v3_4.yml
  onecloud/roles/common/tasks/v3_6.yml
  onecloud/roles/common/templates/daemon.json.j2
  onecloud/roles/common/vars/centos-x86_64.yml
  onecloud/roles/common/vars/debian-10.aarch64.yml
  onecloud/roles/common/vars/uniontech_os_server_20_enterprise-20.aarch64.yml
  onecloud/roles/mariadb/tasks/main.yml
  onecloud/roles/pre-install-common/tasks/main.yml
  onecloud/roles/pre-install-host/tasks/main.yml
  onecloud/roles/primary-master-node/tasks/main.yml
  onecloud/roles/registry/tasks/main.yml
  onecloud/roles/upgrade/common/tasks/v3_4-v3_6.yml
Labels: size/L

#47 Automated cherry pick of #39: feat(config): set default onecloud role config
  lib/ocboot.py
  lib/utils.py
  onecloud/roles/common/files/apt.yunion.list
  onecloud/roles/common/tasks/main.yml
  onecloud/roles/common/tasks/v3_4.yml
  onecloud/roles/common/tasks/v3_6.yml
  onecloud/roles/common/templates/daemon.json.j2
  onecloud/roles/common/vars/centos-x86_64.yml
  onecloud/roles/common/vars/debian-10.aarch64.yml
  onecloud/roles/common/vars/uniontech_os_server_20_enterprise-20.aarch64.yml
  onecloud/roles/mariadb/tasks/main.yml
  onecloud/roles/pre-install-common/tasks/main.yml
  onecloud/roles/pre-install-host/tasks/main.yml
  onecloud/roles/primary-master-node/tasks/main.yml
  onecloud/roles/registry/tasks/main.yml
  onecloud/roles/upgrade/common/tasks/v3_4-v3_6.yml
Labels: size/L

#48 hotfix(deploy): 调整x86的 yunion.repo 初始化顺序
  onecloud/roles/common/tasks/main.yml
Labels: size/XS

#49 Automated cherry pick of #48: hotfix(deploy): 调整x86的 yunion.repo 初始化顺序
  onecloud/roles/common/tasks/main.yml
Labels: size/XS

#50 禁用 swap 服务
  onecloud/roles/common/tasks/main.yml
Labels: size/S

#51 Automated cherry pick of #50: 禁用 swap 服务
  onecloud/roles/common/tasks/main.yml
Labels: size/S

#52 fix(arm64): add missing pkgs
  onecloud/roles/common/tasks/main.yml
  onecloud/roles/common/vars/debian-10.aarch64.yml
  onecloud/roles/common/vars/uniontech_os_server_20_enterprise-20.aarch64.yml
  onecloud/roles/mariadb/tasks/main.yml
  onecloud/roles/primary-master-node/tasks/main.yml
Labels: size/S

#53 Automated cherry pick of #52: fix(arm64): add missing pkgs
  onecloud/roles/common/tasks/main.yml
  onecloud/roles/common/vars/debian-10.aarch64.yml
  onecloud/roles/common/vars/uniontech_os_server_20_enterprise-20.aarch64.yml
  onecloud/roles/mariadb/tasks/main.yml
  onecloud/roles/primary-master-node/tasks/main.yml
Labels: size/S

#54 mariadb 初始化启动顺序，兼容 UOS mariadb
  onecloud/roles/mariadb/tasks/main.yml
Labels: size/S

#55 Automated cherry pick of #54: mariadb 初始化启动顺序
  onecloud/roles/mariadb/tasks/main.yml
Labels: size/S

#56 fix: debian config maridb need python-pymysql
  onecloud/roles/mariadb/tasks/main.yml
Labels: size/XS

#57 Automated cherry pick of #56: fix: debian config maridb need python-pymysql
  onecloud/roles/mariadb/tasks/main.yml
Labels: size/XS

#58 fix: common install task order
  lib/ocboot.py
  onecloud/roles/common/tasks/main.yml
  onecloud/roles/mariadb/tasks/main.yml
Labels: size/M
