Repository yunionio/ocboot, pull requests merged in 2021-05, with the labels that each got.

#89 fix(docker,deploy): 去掉 docker version 的字符串;使用 repo 默认的版本安装
  onecloud/roles/common/tasks/main.yml
Labels: size/XS

#91 Automated cherry pick of #89: fix(docker,deploy): 去掉 docker version 的字符串;使用 repo 默认的版本安装
  onecloud/roles/common/tasks/main.yml
Labels: size/XS

#90 Automated cherry pick of #89: fix(docker,deploy): 去掉 docker version 的字符串;使用 repo 默认的版本安装
  onecloud/roles/common/tasks/main.yml
Labels: size/XS

#92 mariadb conf hotfix
  lib/ocboot.py
Labels: size/XS

#93 fix(deb, repo): 更新3.7的 apt repo
  onecloud/roles/common/tasks/v3_7.yml
Labels: size/S

#94 fix: v3.7 installation and upgrade
  onecloud/roles/common/tasks/v3_7.yml
  onecloud/roles/upgrade/common/tasks/v3_6-v3_7.yml
Labels: size/M

#95 Automated cherry pick of #94: fix: v3.7 installation and upgrade
  onecloud/roles/common/tasks/v3_7.yml
  onecloud/roles/upgrade/common/tasks/v3_6-v3_7.yml
Labels: size/M

#96 fix: reboot node if centos kernel is not yn version
  onecloud/roles/master-node/tasks/main.yml
  onecloud/roles/primary-master-node/setup_k8s/tasks/main.yml
  onecloud/roles/utils/kernel-check/tasks/main.yml
  onecloud/roles/worker-node/tasks/main.yml
Labels: size/M

#97 Automated cherry pick of #96: fix: reboot node if centos kernel is not yn version
  onecloud/roles/master-node/tasks/main.yml
  onecloud/roles/primary-master-node/setup_k8s/tasks/main.yml
  onecloud/roles/utils/kernel-check/tasks/main.yml
  onecloud/roles/worker-node/tasks/main.yml
Labels: size/M

#98 feat(deploy,reboot,kernel): 重构内核重启逻辑
  onecloud/roles/master-node/tasks/main.yml
  onecloud/roles/primary-master-node/reboot/tasks/main.yml
  onecloud/roles/primary-master-node/setup_k8s/tasks/main.yml
  onecloud/roles/worker-node/tasks/main.yml
Labels: size/M

#99 Automated cherry pick of #98: feat(deploy,reboot,kernel): 重构内核重启逻辑
  onecloud/roles/master-node/tasks/main.yml
  onecloud/roles/primary-master-node/reboot/tasks/main.yml
  onecloud/roles/primary-master-node/setup_k8s/tasks/main.yml
  onecloud/roles/worker-node/tasks/main.yml
Labels: size/M

#104 fix(deploy,reboot): 在外部的python里检测是否需要重启。重启条件：本机执行 primary 安装时，python …
  lib/install.py
  lib/kernel_utils.py
  onecloud/install-cluster.yml
  onecloud/roles/utils/kernel-check/tasks/main.yml
Labels: size/M

#105 Automated cherry pick of #104: fix(deploy,reboot): 在外部的python里检测是否需要重启。重启条件：本机执行 primary 安装时，python 脚本负责重启；远程 ssh 安装primary时，ansible 负责重启.
  lib/install.py
  lib/kernel_utils.py
  onecloud/install-cluster.yml
  onecloud/roles/utils/kernel-check/tasks/main.yml
Labels: size/M

#106 fix(deploy,os): 解决在 linux/macos 下运行 ansible 获取当前机器的 interfaces 的兼容性问题
  lib/kernel_utils.py
Labels: size/M

#107 Automated cherry pick of #106: fix(deploy,os): 解决在 linux/macos 下运行 ansible 获取当前机器的 interfaces 的兼容性问题
  lib/kernel_utils.py
Labels: size/M

#109 fix(deploy,arm64,x86,k8s,ha): 高可用跨平台开源部署
  onecloud/roles/common/vars/centos-x86_64.yml
  onecloud/roles/common/vars/debian-10.aarch64.yml
  onecloud/roles/common/vars/debian-10.x86_64.yml
  onecloud/roles/common/vars/uniontech_os_server_20_enterprise-20.aarch64.yml
  onecloud/roles/common/vars/uniontech_os_server_20_enterprise-20.x86_64.yml
  onecloud/roles/pre-install-common/tasks/main.yml
  onecloud/roles/primary-master-node/setup_cloud/tasks/main.yml
Labels: size/M

#110 Automated cherry pick of #109: fix(deploy,arm64,x86,k8s,ha): 高可用跨平台开源部署平台部署
  onecloud/roles/common/vars/centos-x86_64.yml
  onecloud/roles/common/vars/debian-10.aarch64.yml
  onecloud/roles/common/vars/debian-10.x86_64.yml
  onecloud/roles/common/vars/uniontech_os_server_20_enterprise-20.aarch64.yml
  onecloud/roles/common/vars/uniontech_os_server_20_enterprise-20.x86_64.yml
  onecloud/roles/pre-install-common/tasks/main.yml
  onecloud/roles/primary-master-node/setup_cloud/tasks/main.yml
Labels: size/M

#113 docs(deploy,arch,k8s): 高可用部署步骤文档更新
  README.md
Labels: size/M

#114 Automated cherry pick of #113: docs(deploy,arch,k8s): 高可用部署步骤文档更新
  README.md
Labels: size/M

#112 Automated cherry pick of #109: fix(deploy,arm64,x86,k8s,ha): 高可用跨平台开源部署平台部署
  onecloud/roles/common/vars/centos-x86_64.yml
  onecloud/roles/common/vars/debian-10.aarch64.yml
  onecloud/roles/common/vars/debian-10.x86_64.yml
  onecloud/roles/common/vars/uniontech_os_server_20_enterprise-20.aarch64.yml
  onecloud/roles/common/vars/uniontech_os_server_20_enterprise-20.x86_64.yml
  onecloud/roles/pre-install-common/tasks/main.yml
Labels: size/M

#117 refactor detect OS distribution code
  lib/upgrade.py
  onecloud/roles/common/tasks/main.yml
  onecloud/roles/upgrade/common/tasks/main.yml
  onecloud/roles/upgrade/common/tasks/v3_4-v3_6.yml
  onecloud/roles/upgrade/common/tasks/v3_6-v3_7.yml
  onecloud/roles/utils/detect-os/tasks/main.yml
  onecloud/roles/utils/detect-os/vars/centos-x86_64.yml
  onecloud/roles/utils/detect-os/vars/debian-10.aarch64.yml
  onecloud/roles/utils/detect-os/vars/debian-10.x86_64.yml
  onecloud/roles/utils/detect-os/vars/uniontech_os_server_20_enterprise-20.aarch64.yml
  onecloud/roles/utils/detect-os/vars/uniontech_os_server_20_enterprise-20.x86_64.yml
Labels: size/M

#119 Automated cherry pick of #117: refactor detect OS distribution code
  lib/upgrade.py
  onecloud/roles/common/tasks/main.yml
  onecloud/roles/upgrade/common/tasks/main.yml
  onecloud/roles/upgrade/common/tasks/v3_4-v3_6.yml
  onecloud/roles/utils/detect-os/tasks/main.yml
  onecloud/roles/utils/detect-os/vars/centos-x86_64.yml
  onecloud/roles/utils/detect-os/vars/debian-10.aarch64.yml
  onecloud/roles/utils/detect-os/vars/debian-10.x86_64.yml
  onecloud/roles/utils/detect-os/vars/uniontech_os_server_20_enterprise-20.aarch64.yml
  onecloud/roles/utils/detect-os/vars/uniontech_os_server_20_enterprise-20.x86_64.yml
Labels: size/M

#120 fix: detect os at first
  onecloud/install-cluster.yml
  onecloud/roles/common/tasks/main.yml
  onecloud/roles/upgrade/common/tasks/main.yml
  onecloud/upgrade-cluster.yml
Labels: size/S

#121 Automated cherry pick of #120: fix: detect os at first
  onecloud/install-cluster.yml
  onecloud/roles/common/tasks/main.yml
  onecloud/roles/upgrade/common/tasks/main.yml
  onecloud/upgrade-cluster.yml
Labels: size/S

#122 Automated cherry pick of #120: fix: detect os at first
  onecloud/install-cluster.yml
  onecloud/roles/common/tasks/main.yml
  onecloud/roles/upgrade/common/tasks/main.yml
  onecloud/upgrade-cluster.yml
Labels: size/S

#124 fix(upgrade): force update yum repo file
  onecloud/roles/upgrade/common/tasks/v3_4-v3_6.yml
  onecloud/roles/upgrade/common/tasks/v3_6-v3_7.yml
Labels: size/XS

#125 Automated cherry pick of #124: fix(upgrade): force update yum repo file
  onecloud/roles/upgrade/common/tasks/v3_4-v3_6.yml
  onecloud/roles/upgrade/common/tasks/v3_6-v3_7.yml
Labels: size/XS

#126 Automated cherry pick of #124: fix(upgrade): force update yum repo file
  onecloud/roles/upgrade/common/tasks/v3_4-v3_6.yml
Labels: size/XS
