Repository yunionio/ocboot, pull requests merged in 2021-10, with the labels that each got.

#239 Automated cherry pick of #238: fix(k8s,deploy,iso): 解决开源部署、iso 部署时 rpm 安装源的选择的 bug
  onecloud/roles/common/tasks/main.yml
  onecloud/roles/common/tasks/master.yml
  onecloud/roles/common/tasks/v3_4.yml
  onecloud/roles/common/tasks/v3_6.yml
  onecloud/roles/common/tasks/v3_7.yml
  onecloud/roles/common/tasks/v3_8.yml
  onecloud/roles/mariadb/tasks/main.yml
  onecloud/roles/pre-install-common/tasks/main.yml
  onecloud/roles/registry/tasks/main.yml
  onecloud/roles/utils/detect-os/tasks/main.yml
Labels: size/M

#241 fix(kernel,lsmod): 5.x 内核不再进行 lsmod 内核模块校验，以免报错
  onecloud/roles/common/tasks/main.yml
Labels: size/XS

#242 Automated cherry pick of #241: fix(kernel,lsmod): 5.x 内核不再进行 lsmod 内核模块校验，以免报错
  onecloud/roles/common/tasks/main.yml
Labels: size/XS

#245 Automated cherry pick of #244: 提前安装 ca certs 以防证书过期
  onecloud/roles/common/tasks/main.yml
Labels: size/XS

#243 Automated cherry pick of #235: use kubernetes v1.15.12
  onecloud/roles/pre-install-common/tasks/main.yml
  onecloud/roles/utils/detect-os/vars/centos-x86_64.yml
  onecloud/roles/utils/detect-os/vars/debian-10.aarch64.yml
  onecloud/roles/utils/detect-os/vars/debian-10.x86_64.yml
  onecloud/roles/utils/detect-os/vars/uniontech_os_server_20_enterprise-20.aarch64.yml
  onecloud/roles/utils/detect-os/vars/uniontech_os_server_20_enterprise-20.x86_64.yml
Labels: size/M

#248 Automated cherry pick of #247: feat(ceph,deploy,host): 所有节点默认安装 ceph-common 包
  onecloud/roles/common/tasks/master.yml
  onecloud/roles/common/tasks/v3_4.yml
  onecloud/roles/common/tasks/v3_6.yml
  onecloud/roles/common/tasks/v3_7.yml
  onecloud/roles/common/tasks/v3_8.yml
  onecloud/roles/pre-install-common/tasks/main.yml
  onecloud/roles/upgrade/common/tasks/v3_4-v3_6.yml
  onecloud/roles/upgrade/common/tasks/v3_6-v3_7.yml
  onecloud/roles/upgrade/common/tasks/v3_7-v3_8.yml
  onecloud/roles/utils/detect-os/vars/centos-x86_64.yml
  onecloud/roles/utils/detect-os/vars/debian-10.aarch64.yml
  onecloud/roles/utils/detect-os/vars/debian-10.x86_64.yml
  onecloud/roles/utils/detect-os/vars/uniontech_os_server_20_enterprise-20.aarch64.yml
  onecloud/roles/utils/detect-os/vars/uniontech_os_server_20_enterprise-20.x86_64.yml
Labels: size/S

#253 update version to v3.8.3
  VERSION
Labels: size/XS
