Repository yunionio/ocboot, pull requests merged in 2021-11, with the labels that each got.

#267 update version to v3.8.4
  VERSION
Labels: size/XS

#268 Automated cherry pick of #267: update version to v3.8.4
  VERSION
Labels: size/XS

#259 feat(eip,ha,keepalived): EIP 高可用部署
  lib/ocboot.py
  onecloud/install-cluster.yml
  onecloud/roles/utils/eip-ha/files/get_oc_vars.sh
  onecloud/roles/utils/eip-ha/files/keepalived-eipgw-notify.sh
  onecloud/roles/utils/eip-ha/handlers/main.yml
  onecloud/roles/utils/eip-ha/tasks/main.yml
  onecloud/roles/utils/eip-ha/templates/keepalived-eipgw.conf.j2
  onecloud/roles/utils/eip-ha/templates/sdnagent.conf.j2
Labels: size/L

#266 Automated cherry pick of #259: feat(eip,ha,keepalived): EIP 高可用部署
  lib/ocboot.py
  onecloud/install-cluster.yml
  onecloud/roles/utils/eip-ha/files/get_oc_vars.sh
  onecloud/roles/utils/eip-ha/files/keepalived-eipgw-notify.sh
  onecloud/roles/utils/eip-ha/handlers/main.yml
  onecloud/roles/utils/eip-ha/tasks/main.yml
  onecloud/roles/utils/eip-ha/templates/keepalived-eipgw.conf.j2
  onecloud/roles/utils/eip-ha/templates/sdnagent.conf.j2
Labels: size/L

#269 fix(deploy,arm64): arm64兼容问题：executor 软件包名
  onecloud/roles/common/tasks/v3_8.yml
Labels: size/XS

#270 Automated cherry pick of #269: fix(deploy,arm64): arm64兼容问题：executor 软件包名
  onecloud/roles/common/tasks/v3_8.yml
Labels: size/XS

#272 Automated cherry pick of #271: feat(deploy,kernel): release/3.8 恢复旧版本的 kernel: kernel-3.10.0-1160.6.1.el7.yn20201125; 升级逻辑保持不变
  onecloud/roles/common/tasks/master.yml
  onecloud/roles/common/tasks/v3_8.yml
Labels: size/S

#271 [wip]feat(deploy,kernel): release/3.8 恢复旧版本的 kernel: kernel-3.10.0-1160.6
  onecloud/roles/common/tasks/master.yml
  onecloud/roles/common/tasks/v3_8.yml
Labels: size/S, do-not-merge/work-in-progress

#273 fix(deploy,check): 开源部署前，检测域名是否包含 localhost 字串
  onecloud/roles/common/tasks/main.yml
  onecloud/roles/utils/misc-check/tasks/main.yml
  onecloud/roles/utils/port-check/tasks/main.yml
Labels: size/M

#274 Automated cherry pick of #273: fix(deploy,check): 开源部署前，检测域名是否包含 localhost 字串
  onecloud/roles/common/tasks/main.yml
  onecloud/roles/utils/misc-check/tasks/main.yml
  onecloud/roles/utils/port-check/tasks/main.yml
Labels: size/M

#275 Automated cherry pick of #273: fix(deploy,check): 开源部署前，检测域名是否包含 localhost 字串
  onecloud/roles/common/tasks/main.yml
  onecloud/roles/utils/misc-check/tasks/main.yml
  onecloud/roles/utils/port-check/tasks/main.yml
Labels: size/M
