Repository yunionio/ocboot, pull requests merged in 2021-08, with the labels that each got.

#176 fix(deploy,gpu): 解决某些环境，sh 脚本丢失可执行权限的问题
  onecloud/roles/utils/gpu-init/tasks/main.yml
Labels: size/XS

#177 Automated cherry pick of #176: fix(deploy,gpu): 解决某些环境，sh 脚本丢失可执行权限的问题
  onecloud/roles/utils/gpu-init/tasks/main.yml
Labels: size/XS

#181 fix: install failed if no ansible installed
  onecloud/roles/mariadb/files/my.cnf
  run.py
Labels: size/XS

#182 Automated cherry pick of #181: fix: install failed if no ansible installed
  onecloud/roles/mariadb/files/my.cnf
  run.py
Labels: size/M

#179 feat(db,backup,restore): 新增 k8s 的备份与恢复模式
  README.md
  lib/backup.py
  lib/cmd.py
  lib/db.py
  lib/ocboot.py
  lib/restore.py
  lib/utils.py
  ocboot.py
  onecloud/install-cluster.yml
  onecloud/roles/restore/add-sync-user/tasks/main.yml
  onecloud/roles/restore/rm-sync-user/tasks/main.yml
Labels: size/L

#180 Automated cherry pick of #179: feat(db,backup,restore): 新增 k8s 的备份与恢复模式
  README.md
  lib/backup.py
  lib/cmd.py
  lib/db.py
  lib/ocboot.py
  lib/restore.py
  lib/utils.py
  ocboot.py
  onecloud/install-cluster.yml
  onecloud/roles/restore/add-sync-user/tasks/main.yml
  onecloud/roles/restore/rm-sync-user/tasks/main.yml
Labels: size/L

#183 备份与恢复的优化
  lib/backup.py
  lib/cmd.py
  lib/db.py
  lib/restore.py
  lib/utils.py
Labels: size/L

#184 Automated cherry pick of #183: 备份与恢复的优化
  lib/backup.py
  lib/cmd.py
  lib/db.py
  lib/restore.py
  lib/utils.py
Labels: size/L

#185 fix(db,k8s,backup,restore): k8s 的备份与恢复，修复sync-user报错的问题
  lib/backup.py
  lib/cmd.py
  lib/color.py
  lib/db.py
  lib/restore.py
  onecloud/roles/restore/add-sync-user/tasks/main.yml
Labels: size/L

#186 Automated cherry pick of #185: fix(db,k8s,backup,restore): k8s 的备份与恢复，修复sync-user报错的问题
  lib/backup.py
  lib/cmd.py
  lib/color.py
  lib/db.py
  lib/restore.py
  onecloud/roles/restore/add-sync-user/tasks/main.yml
Labels: size/L

#191 3.8 ~ master 升级 kernel到 kernel-lt-5.4.130-1.yn20210710.el7.x86_64.rpm
  onecloud/roles/utils/gpu-init/files/gpu_setup.sh
Labels: size/S

#193 3.8 task 升级等文件更新
  onecloud/roles/common/tasks/v3_8.yml
  onecloud/roles/upgrade/common/tasks/v3_7-v3_8.yml
Labels: size/M

#192 Automated cherry pick of #191: 3.8 ~ master 升级 kernel到 kernel-lt-5.4.130-1.yn20210710.el7.x86_64.rpm
  onecloud/roles/utils/gpu-init/files/gpu_setup.sh
Labels: size/S

#194 v3.8 stable
  VERSION
Labels: size/XS

#195 python3 import hotfix
  lib/backup.py
  lib/db.py
Labels: size/XS

#196 Automated cherry pick of #195: python3 import hotfix
  lib/backup.py
  lib/db.py
Labels: size/XS

#197 Automated cherry pick of #195: python3 import hotfix
  lib/backup.py
  lib/db.py
Labels: size/XS

#198 python3 import hotfix
  onecloud/roles/utils/gpu-init/files/gpu_setup.sh
  onecloud/upgrade-cluster.yml
Labels: size/XS, lgtm

#200 Automated cherry pick of #198: python3 import hotfix
  onecloud/roles/utils/gpu-init/files/gpu_setup.sh
  onecloud/upgrade-cluster.yml
Labels: size/XS

#199 Automated cherry pick of #198: python3 import hotfix
  onecloud/roles/utils/gpu-init/files/gpu_setup.sh
  onecloud/upgrade-cluster.yml
Labels: size/S
