Repository yunionio/ocboot, pull requests merged in 2021-04, with the labels that each got.

#60 fix(deploy,tcp): 预装系统时调高系统邻居表允许的最大条目数
  onecloud/roles/tcp/tasks/main.yml
Labels: approved, lgtm, size/S

#61 Automated cherry pick of #60: fix(deploy,tcp): 预装系统时调高系统邻居表允许的最大条目数
  onecloud/roles/tcp/tasks/main.yml
Labels: approved, lgtm, size/S

#62 fix: centos qemu rpm package missing
  onecloud/roles/common/vars/centos-x86_64.yml
Labels: size/XS

#66 feat: add cronjobs
  onecloud/roles/common/tasks/main.yml
  onecloud/roles/master-node/tasks/main.yml
  onecloud/roles/master-node/upgrade/tasks/v3-4-v3-6.yaml
  onecloud/roles/primary-master-node/tasks/main.yml
  onecloud/roles/upgrade/common/tasks/main.yml
  onecloud/roles/upgrade/master_nodes/tasks/main.yml
  onecloud/roles/upgrade/primary_master_node/tasks/main.yml
  onecloud/roles/upgrade/worker_nodes/tasks/main.yml
  onecloud/roles/utils/controlplane/tasks/main.yml
  onecloud/roles/utils/cronjobs/tasks/main.yml
  onecloud/upgrade-cluster.yml
Labels: size/M

#67 Automated cherry pick of #66: feat: add cronjobs
  onecloud/roles/common/tasks/main.yml
  onecloud/roles/master-node/tasks/main.yml
  onecloud/roles/master-node/upgrade/tasks/v3-4-v3-6.yaml
  onecloud/roles/primary-master-node/tasks/main.yml
  onecloud/roles/upgrade/common/tasks/main.yml
  onecloud/roles/upgrade/master_nodes/tasks/main.yml
  onecloud/roles/upgrade/primary_master_node/tasks/main.yml
  onecloud/roles/upgrade/worker_nodes/tasks/main.yml
  onecloud/roles/utils/controlplane/tasks/main.yml
  onecloud/roles/utils/cronjobs/tasks/main.yml
  onecloud/upgrade-cluster.yml
Labels: size/M

#68 feat: support debian x86_64
  onecloud/roles/common/vars/debian-10.x86_64.yml
Labels: size/M

#69 Automated cherry pick of #68: feat: support debian x86_64
  onecloud/roles/common/vars/debian-10.x86_64.yml
Labels: size/M

#70 feat: support deploy minio in v3.7 version
  lib/ocboot.py
  onecloud/install-cluster.yml
  onecloud/roles/common/tasks/v3_4.yml
  onecloud/roles/common/tasks/v3_7.yml
  onecloud/roles/primary-master-node/setup_cloud/tasks/main.yml
  onecloud/roles/primary-master-node/setup_k8s/tasks/main.yml
Labels: size/L

#71 fix: v3.7 domain resolve
  onecloud/roles/common/tasks/v3_7.yml
Labels: size/XS

#72 Automated cherry pick of #71: fix: v3.7 domain resolve
  onecloud/roles/common/tasks/v3_7.yml
Labels: size/XS

#73 fix: missing yunion-fetcherfs
  onecloud/roles/common/vars/centos-x86_64.yml
Labels: size/XS

#74 Automated cherry pick of #73: fix: missing yunion-fetcherfs
  onecloud/roles/common/vars/centos-x86_64.yml
Labels: size/XS

#75 Automated cherry pick of #73: fix: missing yunion-fetcherfs
  onecloud/roles/common/vars/centos-x86_64.yml
Labels: size/XS

#76 fix: debian based OS fetcherfs not installed
  onecloud/roles/common/vars/debian-10.aarch64.yml
  onecloud/roles/common/vars/debian-10.x86_64.yml
  onecloud/roles/common/vars/uniontech_os_server_20_enterprise-20.aarch64.yml
  onecloud/roles/common/vars/uniontech_os_server_20_enterprise-20.x86_64.yml
Labels: size/XS

#77 Automated cherry pick of #76: fix: debian based OS fetcherfs not installed
  onecloud/roles/common/vars/debian-10.aarch64.yml
  onecloud/roles/common/vars/debian-10.x86_64.yml
  onecloud/roles/common/vars/uniontech_os_server_20_enterprise-20.aarch64.yml
  onecloud/roles/common/vars/uniontech_os_server_20_enterprise-20.x86_64.yml
Labels: size/XS

#78 Automated cherry pick of #76: fix: debian based OS fetcherfs not installed
  onecloud/roles/common/vars/debian-10.aarch64.yml
  onecloud/roles/common/vars/debian-10.x86_64.yml
  onecloud/roles/common/vars/uniontech_os_server_20_enterprise-20.aarch64.yml
  onecloud/roles/common/vars/uniontech_os_server_20_enterprise-20.x86_64.yml
Labels: size/XS

#81 fix(centos): add missing pkgs
  onecloud/roles/common/vars/centos-x86_64.yml
Labels: approved, size/XS

#82 Automated cherry pick of #81: fix(centos): add missing pkgs
  onecloud/roles/common/vars/centos-x86_64.yml
Labels: approved, size/XS

#83 Automated cherry pick of #81: fix(centos): add missing pkgs
  onecloud/roles/common/vars/centos-x86_64.yml
Labels: size/XS

#85 fix: search for the correct line from ip route
  onecloud/roles/primary-master-node/setup_cloud/tasks/main.yml
Labels: size/XS

#86 Automated cherry pick of #85: fix: search for the correct line from ip route
  onecloud/roles/primary-master-node/setup_cloud/tasks/main.yml
Labels: approved

#84 fix: get network mask length
  onecloud/roles/primary-master-node/tasks/main.yml
Labels: approved, size/XS

#79 ocboot 与 yunionboot 合并
  lib/ocboot.py
  onecloud/roles/common/tasks/main.yml
  onecloud/roles/longhorn-node/tasks/main.yml
  onecloud/roles/master-node/tasks/main.yml
  onecloud/roles/pre-install-common/tasks/main.yml
  onecloud/roles/pre-install-host/tasks/main.yml
  onecloud/roles/primary-master-node/setup_cloud/tasks/main.yml
  onecloud/roles/primary-master-node/setup_k8s/tasks/main.yml
  onecloud/roles/reboot-node/tasks/main.yml
  onecloud/roles/tcp/tasks/main.yml
  onecloud/roles/worker-node/tasks/main.yml
  run.py
Labels: approved, lgtm, size/L

#80 Automated cherry pick of #79: ocboot 与 yunionboot 合并
  lib/ocboot.py
  onecloud/roles/common/tasks/main.yml
  onecloud/roles/longhorn-node/tasks/main.yml
  onecloud/roles/master-node/tasks/main.yml
  onecloud/roles/pre-install-common/tasks/main.yml
  onecloud/roles/pre-install-host/tasks/main.yml
  onecloud/roles/primary-master-node/setup_cloud/tasks/main.yml
  onecloud/roles/primary-master-node/setup_k8s/tasks/main.yml
  onecloud/roles/reboot-node/tasks/main.yml
  onecloud/roles/tcp/tasks/main.yml
  onecloud/roles/worker-node/tasks/main.yml
  run.py
Labels: approved, lgtm, size/L
