Repository yunionio/ocboot, pull requests merged in 2021-06, with the labels that each got.

#123 fix(deploy): 解决 ocboot 不支持 master的问题
  lib/utils.py
  onecloud/roles/common/tasks/master.yml
Labels: size/M

#115 fix: set keepalived_version_tag when high_availability is true
  README.md
  lib/ocboot.py
Labels: size/XS

#116 Automated cherry pick of #115: fix: set keepalived_version_tag when high_availability is true
  README.md
  lib/ocboot.py
Labels: size/XS

#128 fix(deploy,k8s,opensource,iso): 解决k8s开源部署时与光盘部署差异引起的bug
  onecloud/roles/pre-install-common/tasks/main.yml
Labels: size/M

#130 Automated cherry pick of #128: fix(deploy,k8s,opensource,iso): 解决k8s开源部署时与光盘部署差异引起的bug
  onecloud/roles/pre-install-common/tasks/main.yml
Labels: size/M

#131 fix(typo): minor yaml typo
  onecloud/roles/common/tasks/master.yml
Labels: size/XS

#103 hotfix: adjust paramiko SSH connect timeout
  lib/ssh.py
Labels: approved, lgtm, size/XS

#136 Automated cherry pick of #135: feat(deploy,offline,k8s,ha): 高可用模式支持离线部署
  lib/ocboot.py
  onecloud/install-cluster.yml
  onecloud/roles/primary-master-node/rsync_rpms/tasks/main.yml
Labels: size/S

#135 feat(deploy,offline,k8s,ha): 高可用模式支持离线部署
  lib/ocboot.py
  onecloud/install-cluster.yml
  onecloud/roles/primary-master-node/rsync_rpms/tasks/main.yml
Labels: size/S

#132 improve: simplify allinone setup
  README.md
  VERSION
  run.py
Labels: size/L

#133 Automated cherry pick of #132: improve: simplify allinone setup
  README.md
  VERSION
  run.py
Labels: size/L

#134 Automated cherry pick of #132: improve: simplify allinone setup
  README.md
  VERSION
  run.py
Labels: size/L

#137 fix(ha,k8s,deploy): 高可用集群部署细节修正
  lib/ocboot.py
  onecloud/roles/common/tasks/master.yml
  onecloud/roles/common/tasks/v3_7.yml
Labels: size/S

#138 Automated cherry pick of #137: fix(ha,k8s,deploy): 高可用集群部署细节修正
  lib/ocboot.py
  onecloud/roles/common/tasks/v3_7.yml
Labels: size/XS

#139 fix(upgrade): 增加升级提示语句；处理升级 rpm 包冲突的问题
  lib/upgrade.py
  onecloud/roles/upgrade/common/tasks/v3_6-v3_7.yml
Labels: size/M

#140 Automated cherry pick of #139: fix(upgrade): 增加升级提示语句；处理升级 rpm 包冲突的问题
  lib/upgrade.py
  onecloud/roles/upgrade/common/tasks/v3_6-v3_7.yml
Labels: size/M

#141 feat:(deploy,port) 部署时检测端口是否被占用
  lib/install.py
  onecloud/roles/common/tasks/main.yml
  onecloud/roles/utils/port-check/tasks/main.yml
Labels: do-not-merge/work-in-progress, size/S

#143 hotfix(db,port):解决临时密码安装的 bug，解决端口检测的 bug
  .gitignore
  lib/upgrade.py
  onecloud/roles/utils/port-check/tasks/main.yml
  run.py
Labels: size/S

#144 Automated cherry pick of #143: hotfix(db,port):解决临时密码安装的 bug，解决端口检测的 bug
  .gitignore
  lib/upgrade.py
  onecloud/roles/utils/port-check/tasks/main.yml
  run.py
Labels: size/S

#145 fix(deploy,check): 暂时注释掉端口检测
  onecloud/roles/common/tasks/main.yml
Labels: size/XS

#146 Automated cherry pick of #145: fix(deploy,check): 暂时注释掉端口检测
  onecloud/roles/common/tasks/main.yml
Labels: size/XS

#148 fix(reboot,deploy,k8s): 重构重启逻辑
  lib/install.py
  onecloud/roles/utils/kernel-check/tasks/main.yml
Labels: approved, lgtm, size/S

#149 Automated cherry pick of #148: fix(reboot,deploy,k8s): 重构重启逻辑
  lib/install.py
  onecloud/roles/utils/kernel-check/tasks/main.yml
Labels: approved, lgtm, size/S

#147 feature: further simplify ocboot
  VERSION
  lib/ocboot.py
  lib/utils.py
  onecloud/roles/mariadb/files/my.cnf
  requirements.txt
  run.py
Labels: size/M

#153 fix: turn off swap with name none
  onecloud/roles/common/tasks/main.yml
Labels: size/XS

#154 Automated cherry pick of #153: fix: turn off swap with name none
  onecloud/roles/common/tasks/main.yml
Labels: size/XS

#155 Automated cherry pick of #153: fix: turn off swap with name none
  onecloud/roles/common/tasks/main.yml
Labels: size/XS

#156 fix(deploy,ocboot,reboot): 解决 ocboot 远程 ssh 执行安装时,错误地重启 ocboot 本机的 bug
  lib/install.py
Labels: size/XS

#157 Automated cherry pick of #156: fix(deploy,ocboot,reboot): 解决 ocboot 远程 ssh 执行安装时,错误地重启 ocboot 本机的 bug
  lib/install.py
Labels: size/XS

#158 update version to v3.7.5
  VERSION
Labels: size/XS

#159 Automated cherry pick of #158: update version to v3.7.5
  VERSION
Labels: size/XS

#150 feat(kubelet): set pod pid limit
  onecloud/roles/master-node/tasks/main.yml
  onecloud/roles/primary-master-node/setup_k8s/tasks/main.yml
  onecloud/roles/upgrade/common/tasks/main.yml
  onecloud/roles/utils/k8s/kubelet/extra-args/files/etc_sysconfig_kubelet
  onecloud/roles/utils/k8s/kubelet/extra-args/tasks/main.yml
  onecloud/roles/worker-node/tasks/main.yml
Labels: size/M

#152 Automated cherry pick of #150: feat(kubelet): set pod pid limit
  onecloud/roles/master-node/tasks/main.yml
  onecloud/roles/primary-master-node/tasks/main.yml
  onecloud/roles/upgrade/common/tasks/main.yml
  onecloud/roles/utils/k8s/kubelet/extra-args/files/etc_sysconfig_kubelet
  onecloud/roles/utils/k8s/kubelet/extra-args/tasks/main.yml
  onecloud/roles/worker-node/tasks/main.yml
Labels: size/M

#151 Automated cherry pick of #150: feat(kubelet): set pod pid limit
  onecloud/roles/master-node/tasks/main.yml
  onecloud/roles/primary-master-node/setup_k8s/tasks/main.yml
  onecloud/roles/upgrade/common/tasks/main.yml
  onecloud/roles/utils/k8s/kubelet/extra-args/files/etc_sysconfig_kubelet
  onecloud/roles/utils/k8s/kubelet/extra-args/tasks/main.yml
  onecloud/roles/worker-node/tasks/main.yml
Labels: size/M
