Repository yunionio/ocboot, pull requests merged in 2021-12, with the labels that each got.

#276 feat(eip,allinone): 在 allinone 模式下部署时，默认启用 eip-man
  lib/ocboot.py
  onecloud/install-cluster.yml
  onecloud/roles/utils/enable-eip/tasks/main.yml
  run.py
Labels: size/S

#277 Automated cherry pick of #276: feat(eip,allinone): 在 allinone 模式下部署时，默认启用 eip-man
  lib/ocboot.py
  onecloud/install-cluster.yml
  onecloud/roles/utils/enable-eip/tasks/main.yml
  run.py
Labels: size/S

#278 x86 debian10 release 3.8 fix
  onecloud/roles/utils/kernel-check/tasks/main.yml
Labels: size/XS

#279 Automated cherry pick of #278: x86 debian10 release 3.8 fix
  onecloud/roles/utils/kernel-check/tasks/main.yml
Labels: size/XS

#280 minor fix
  lib/ocboot.py
  run.py
Labels: size/XS

#281 Automated cherry pick of #280: minor fix
  lib/ocboot.py
  run.py
Labels: size/XS

#282 Automated cherry pick of #280: minor fix
  lib/ocboot.py
  run.py
Labels: size/XS

#284 fix(grub_setup): find grub2 cfg exists
  onecloud/roles/utils/gpu-init/files/gpu_setup.sh
Labels: size/XS

#285 Automated cherry pick of #284: fix(grub_setup): find grub2 cfg exists
  onecloud/roles/utils/gpu-init/files/gpu_setup.sh
Labels: size/XS

#286 Automated cherry pick of #284: fix(grub_setup): find grub2 cfg exists
  onecloud/roles/utils/gpu-init/files/gpu_setup.sh
Labels: size/XS

#283 Feature/run in docker
  Dockerfile
  README.md
  run-in-docker.sh
Labels: size/M

#287 run inside docker optimized
  Dockerfile
  Makefile
  README.md
  onecloud/install-cluster.yml
  onecloud/roles/utils/misc-check/tasks/main.yml
  run-in-docker.sh
  run.py
Labels: size/M
