Repository yunionio/ocboot, pull requests merged in 2022-03, with the labels that each got.

#331 minor update package name
  onecloud/roles/common/tasks/v3_7.yml
Labels: size/XS

#332 Automated cherry pick of #331: minor update package name
  onecloud/roles/common/tasks/v3_7.yml
Labels: size/XS

#333 Automated cherry pick of #331: minor update package name
  onecloud/roles/common/tasks/v3_7.yml
Labels: size/XS

#334 Automated cherry pick of #331: minor update package name
  onecloud/roles/common/tasks/v3_7.yml
Labels: size/XS

#335 feat: remove paramiko dependency
  lib/ssh.py
  requirements.txt
Labels: size/M

#336 Automated cherry pick of #335: feat: remove paramiko dependency
  lib/ssh.py
  requirements.txt
Labels: size/M

#337 Automated cherry pick of #335: feat: remove paramiko dependency
  lib/ssh.py
  requirements.txt
Labels: size/M

#338 fix: primary_master config db_port not work
  lib/ocboot.py
Labels: size/XS

#339 Automated cherry pick of #338: fix: primary_master config db_port not work
  lib/ocboot.py
Labels: size/XS

#340 Automated cherry pick of #338: fix: primary_master config db_port not work
  lib/ocboot.py
Labels: size/XS

#342 Automated cherry pick of #341: fix(deploy,python,parser): 解决欧拉、麒麟等系统执行 ssh 命令返回的json字串不规则的问题
  lib/cluster.py
Labels: size/S

#341 fix(deploy,python,parser): 解决欧拉、麒麟等系统执行 ssh 命令返回的json字串不规则的问题
  lib/cluster.py
Labels: size/S

#343 fix:(deploy,os)显式拒绝centos/uos/debian 之外的 OS release
  onecloud/roles/utils/detect-os/tasks/main.yml
Labels: size/XS

#344 Automated cherry pick of #343: fix:(deploy,os)显式拒绝centos/uos/debian 之外的 OS release
  onecloud/roles/utils/detect-os/tasks/main.yml
Labels: size/XS

#345 Automated cherry pick of #343: fix:(deploy,os)显式拒绝centos/uos/debian 之外的 OS release
  onecloud/roles/utils/detect-os/tasks/main.yml
Labels: size/XS

#346 Automated cherry pick of #343: fix:(deploy,os)显式拒绝centos/uos/debian 之外的 OS release
  onecloud/roles/utils/detect-os/tasks/main.yml
Labels: size/XS
