Repository yunionio/ocboot, pull requests merged in 2022-08, with the labels that each got.

#447 update version to v3.8.14
  VERSION
Labels: size/XS

#448 Automated cherry pick of #447: update version to v3.8.14
  VERSION
Labels: size/XS

#449 Automated cherry pick of #447: update version to v3.8.14
  VERSION
Labels: size/XS

#456 fix: update VERSION to v3.9.1
  VERSION
Labels: size/XS

#458 v3.9.0 去掉 rpm包 iscsi-initiator-utils
  onecloud/roles/pre-install-common/tasks/main.yml
Labels: size/XS, lgtm

#459 Automated cherry pick of #458: v3.9.0 去掉 rpm包 iscsi-initiator-utils
  onecloud/roles/pre-install-common/tasks/main.yml
Labels: size/XS, lgtm

#455 feat(helm): charts init
  charts/cloudpods/.helmignore
  charts/cloudpods/Chart.yaml
  charts/cloudpods/Makefile
  charts/cloudpods/README.md
  charts/cloudpods/templates/NOTES.txt
  charts/cloudpods/templates/_helpers.tpl
  charts/cloudpods/templates/cluster-crd.yaml
  charts/cloudpods/templates/cluster.yaml
  charts/cloudpods/templates/ingress.yaml
  charts/cloudpods/templates/local-path-csi.yaml
  charts/cloudpods/templates/mysql.yaml
  charts/cloudpods/templates/operator.yaml
  charts/cloudpods/templates/tests/test-connection.yaml
  charts/cloudpods/values-dev.yaml
  charts/cloudpods/values-prod.yaml
  charts/cloudpods/values.yaml
Labels: size/XXL

#465 feat(helm): add cloudpods chart README
  charts/cloudpods/README.md
  charts/cloudpods/values-prod.yaml
Labels: size/L

#474 fix(helm): disable monitorStack
  charts/cloudpods/templates/cluster.yaml
  charts/cloudpods/values-dev.yaml
  charts/cloudpods/values-prod.yaml
  charts/cloudpods/values.yaml
Labels: size/S

#475 Automated cherry pick of #474: fix(helm): disable monitorStack
  charts/cloudpods/templates/cluster.yaml
  charts/cloudpods/values-dev.yaml
  charts/cloudpods/values-prod.yaml
  charts/cloudpods/values.yaml
Labels: size/S

#476 fix(util): python in cherry_pick_pull
  hack/cherry_pick_pull.sh
Labels: size/XS

#478 fix(helm): nginx ingress annotations for HTTPS
  charts/cloudpods/values-dev.yaml
  charts/cloudpods/values-prod.yaml
  charts/cloudpods/values.yaml
Labels: size/XS

#479 Automated cherry pick of #478: fix(helm): nginx ingress annotations for HTTPS
  charts/cloudpods/values-dev.yaml
  charts/cloudpods/values-prod.yaml
  charts/cloudpods/values.yaml
Labels: size/XS

#480 fix(operator): update operator tag
  charts/cloudpods/values-dev.yaml
  charts/cloudpods/values-prod.yaml
  charts/cloudpods/values.yaml
Labels: size/XS

#460 3.9 全面兼容离线部署
  TODO.md
  onecloud/ansible.cfg
  onecloud/install-cluster.yml
  onecloud/roles/common/tasks/main.yml
  onecloud/roles/common/tasks/master.yml
  onecloud/roles/common/tasks/v3_9_offline.yml
  onecloud/roles/common/tasks/v3_9_online.yml
  onecloud/roles/common/templates/yunion.repo.j2
  onecloud/roles/mariadb/tasks/centos-aarch64.yml
  onecloud/roles/mariadb/tasks/centos-x86_64.yml
  onecloud/roles/mariadb/tasks/kylin_linux_advanced_server-aarch64.yml
  onecloud/roles/mariadb/tasks/kylin_linux_advanced_server-x86_64.yml
  onecloud/roles/mariadb/tasks/main.yml
  onecloud/roles/pre-install-common/tasks/main.yml
  onecloud/roles/primary-master-node/reboot/tasks/main.yml
  onecloud/roles/primary-master-node/setup_k8s/tasks/main.yml
  onecloud/roles/registry/tasks/main.yml
  onecloud/roles/utils/detect-os/tasks/main.yml
  onecloud/roles/utils/detect-os/vars/centos-aarch64.yml
  onecloud/roles/utils/detect-os/vars/centos-x86_64.yml
  onecloud/roles/utils/detect-os/vars/kylin_linux_advanced_server-v10.aarch64.yml
  onecloud/roles/utils/detect-os/vars/kylin_linux_advanced_server-v10.x86_64.yml
  onecloud/roles/utils/gpu-init/tasks/main.yml
  onecloud/roles/utils/kernel-check/tasks/centos-aarch64.yml
  onecloud/roles/utils/kernel-check/tasks/centos-x86_64.yml
  onecloud/roles/utils/kernel-check/tasks/main.yml
  run.py
Labels: size/XL

#472 Automated cherry pick of #460: 3.9 全面兼容离线部署
  TODO.md
  onecloud/ansible.cfg
  onecloud/install-cluster.yml
  onecloud/roles/common/tasks/main.yml
  onecloud/roles/common/tasks/master.yml
  onecloud/roles/common/tasks/v3_9_offline.yml
  onecloud/roles/common/tasks/v3_9_online.yml
  onecloud/roles/common/templates/yunion.repo.j2
  onecloud/roles/mariadb/tasks/centos-aarch64.yml
  onecloud/roles/mariadb/tasks/centos-x86_64.yml
  onecloud/roles/mariadb/tasks/kylin_linux_advanced_server-aarch64.yml
  onecloud/roles/mariadb/tasks/kylin_linux_advanced_server-x86_64.yml
  onecloud/roles/mariadb/tasks/main.yml
  onecloud/roles/pre-install-common/tasks/main.yml
  onecloud/roles/primary-master-node/reboot/tasks/main.yml
  onecloud/roles/primary-master-node/setup_k8s/tasks/main.yml
  onecloud/roles/registry/tasks/main.yml
  onecloud/roles/utils/detect-os/tasks/main.yml
  onecloud/roles/utils/detect-os/vars/centos-aarch64.yml
  onecloud/roles/utils/detect-os/vars/centos-x86_64.yml
  onecloud/roles/utils/detect-os/vars/kylin_linux_advanced_server-v10.aarch64.yml
  onecloud/roles/utils/detect-os/vars/kylin_linux_advanced_server-v10.x86_64.yml
  onecloud/roles/utils/gpu-init/tasks/main.yml
  onecloud/roles/utils/kernel-check/tasks/centos-aarch64.yml
  onecloud/roles/utils/kernel-check/tasks/centos-x86_64.yml
  onecloud/roles/utils/kernel-check/tasks/main.yml
  run.py
Labels: size/XL

#482 backup and restore
  lib/db.py
Labels: size/XS

#483 Automated cherry pick of #482: backup and restore
  lib/db.py
Labels: size/XS

#484 Automated cherry pick of #482: backup and restore
  lib/db.py
Labels: size/XS
