Repository yunionio/ocboot, pull requests merged in 2022-10, with the labels that each got.

#516 fix(mariadb/mysql): 使用 pip 安装 mysql 相关 libs
  onecloud/roles/common/tasks/centos_7.6_aarch64.yml
  onecloud/roles/mariadb/tasks/centos-x86_64.yml
  onecloud/roles/mariadb/tasks/debian-aarch64.yml
  onecloud/roles/mariadb/tasks/debian-x86_64.yml
  onecloud/roles/mariadb/tasks/kylin_linux_advanced_server-aarch64.yml
  onecloud/roles/mariadb/tasks/kylin_linux_advanced_server-x86_64.yml
  onecloud/roles/utils/kernel-check/tasks/centos-aarch64.yml
Labels: size/M

#517 Automated cherry pick of #516: fix(mariadb/mysql): 使用 pip 安装 mysql 相关 libs
  onecloud/roles/common/tasks/centos_7.6_aarch64.yml
  onecloud/roles/mariadb/tasks/centos-x86_64.yml
  onecloud/roles/mariadb/tasks/debian-aarch64.yml
  onecloud/roles/mariadb/tasks/debian-x86_64.yml
  onecloud/roles/mariadb/tasks/kylin_linux_advanced_server-aarch64.yml
  onecloud/roles/mariadb/tasks/kylin_linux_advanced_server-x86_64.yml
  onecloud/roles/utils/kernel-check/tasks/centos-aarch64.yml
Labels: size/M

#521 Automated cherry pick of #520: fix(README): updateset service_dns_domain
  README.md
Labels: size/XS

#523 Automated cherry pick of #522: ocboot 部署时 mask 不能解析成 int 应该默认成 30
  onecloud/roles/primary-master-node/setup_cloud/tasks/main.yml
Labels: size/S

#524 Automated cherry pick of #522: ocboot 部署时 mask 不能解析成 int 应该默认成 30
  onecloud/roles/primary-master-node/setup_cloud/tasks/main.yml
Labels: size/S

#526 fix(typo): fix typo in join cluster step
  onecloud/roles/master-node/tasks/main.yml
Labels: size/XS

#527 Automated cherry pick of #526: fix(typo): fix typo in join cluster step
  onecloud/roles/master-node/tasks/main.yml
Labels: size/XS

#529 Automated cherry pick of #528: fix(python): 升级模式不再强行设置interpreter
  lib/cmd.py
Labels: size/XS

#531 fix(deploy,python3,ha): 高可用集群部署的 hotfix
  lib/cmd.py
  onecloud/roles/common/tasks/main.yml
  onecloud/roles/mariadb-ha/tasks/05ha.yml
  onecloud/roles/mariadb-ha/tasks/20ha.yml
  onecloud/roles/mariadb-ha/tasks/main.yml
  onecloud/roles/pre-install-common/tasks/main.yml
  onecloud/roles/primary-master-node/setup_cloud/tasks/main.yml
  onecloud/roles/utils/detect-os/vars/centos-x86_64.yml
  run.py
Labels: size/L

#533 fix(deploy,python3,ha): 高可用集群部署的 hotfix
  lib/cmd.py
  onecloud/roles/common/tasks/main.yml
  onecloud/roles/pre-install-common/tasks/main.yml
  onecloud/roles/primary-master-node/setup_cloud/tasks/main.yml
  onecloud/roles/utils/detect-os/vars/centos-x86_64.yml
  run.py
Labels: size/M

#525 feat: add hugetlb setup
  README.md
  lib/ocboot.py
  onecloud/roles/master-node/tasks/main.yml
  onecloud/roles/primary-master-node/setup_k8s/tasks/main.yml
  onecloud/roles/utils/kernel-check/files/hugetlb_setup.sh
  onecloud/roles/utils/kernel-check/files/oc-hugetlb-gigantic-pages.service
  onecloud/roles/utils/kernel-check/files/oc-hugetlb-reserve-pages.sh
  onecloud/roles/utils/kernel-check/tasks/main.yml
  onecloud/roles/worker-node/tasks/main.yml
Labels: size/L

#534 hotfix: db python3 issue
  onecloud/roles/mariadb/tasks/main.yml
Labels: size/XS

#535 Automated cherry pick of #534: minor db fix
  onecloud/roles/mariadb/tasks/main.yml
Labels: size/XS

#536 fix(kylin,ha,mariadb): 麒麟环境下的高可用数据库部署bugfix
  onecloud/roles/mariadb-ha/tasks/main.yml
  onecloud/roles/mariadb-ha/vars/kylin_linux_advanced_server-aarch64.yml
  onecloud/roles/mariadb-ha/vars/kylin_linux_advanced_server-x86_64.yml
Labels: size/S

#537 fix(db): db minor issue
  onecloud/roles/mariadb/tasks/centos-x86_64.yml
  onecloud/roles/mariadb/tasks/debian-x86_64.yml
Labels: size/XS

#538 Automated cherry pick of #537: fix(db): db minor issue
  onecloud/roles/mariadb/tasks/centos-x86_64.yml
  onecloud/roles/mariadb/tasks/debian-x86_64.yml
Labels: size/XS

#539 iso离线安装高可用
  TODO.md
  onecloud/roles/common/tasks/v3_9_offline.yml
  onecloud/roles/primary-master-node/setup_k8s/tasks/main.yml
  onecloud/roles/utils/load-images/files/load-images.sh
  onecloud/roles/utils/load-images/tasks/main.yml
Labels: size/L

#540 Automated cherry pick of #539: iso离线安装高可用
  TODO.md
  onecloud/roles/common/tasks/v3_9_offline.yml
  onecloud/roles/primary-master-node/setup_k8s/tasks/main.yml
  onecloud/roles/utils/load-images/files/load-images.sh
  onecloud/roles/utils/load-images/tasks/main.yml
Labels: size/L

#541 更新arp thresh value
  onecloud/roles/tcp/tasks/main.yml
Labels: size/S

#542 Automated cherry pick of #541: 更新arp thresh value
  onecloud/roles/tcp/tasks/main.yml
Labels: size/S

#543 Automated cherry pick of #541: 更新arp thresh value
  onecloud/roles/tcp/tasks/main.yml
Labels: size/S

#544 Automated cherry pick of #541: 更新arp thresh value
  onecloud/roles/tcp/tasks/main.yml
Labels: size/S
