Repository yunionio/ocboot, pull requests merged in 2022-09, with the labels that each got.

#485 fix: update onecloud_version of config
  config-example-allinone.yml
  config-example-nodes.yml
Labels: size/XS

#489 Automated cherry pick of #487: 解决mysql 不能远程登录的bug
  onecloud/roles/mariadb/tasks/main.yml
Labels: size/S

#487 解决mysql 不能远程登录的bug
  onecloud/roles/mariadb/tasks/main.yml
Labels: size/S

#488 Automated cherry pick of #487: 解决mysql 不能远程登录的bug
  onecloud/roles/mariadb/tasks/main.yml
Labels: size/S

#490 数据库选项优化
  onecloud/roles/mariadb-ha/templates/my.cnf.j2
  onecloud/roles/mariadb/files/my.cnf
  onecloud/roles/mariadb/tasks/main.yml
Labels: size/XS

#491 数据库选项优化 for 3.9
  onecloud/roles/mariadb/files/my.cnf
  onecloud/roles/mariadb/tasks/main.yml
Labels: size/XS

#493 Automated cherry pick of #492: minor: backward compatibility fix
  onecloud/roles/primary-master-node/setup_cloud/tasks/main.yml
Labels: size/XS

#492 minor: backward compatibility fix
  onecloud/roles/primary-master-node/setup_cloud/tasks/main.yml
Labels: size/XS

#494 Automated cherry pick of #492: minor: backward compatibility fix
  onecloud/roles/primary-master-node/setup_cloud/tasks/main.yml
Labels: size/XS

#496 Automated cherry pick of #495: 高可用相关hotfix
  onecloud/install-cluster.yml
  onecloud/roles/common/tasks/v3_9_offline.yml
  onecloud/roles/primary-master-node/rsync_rpms/tasks/main.yml
  onecloud/roles/primary-master-node/setup_k8s/tasks/main.yml
Labels: size/M

#497 db permission fix
  onecloud/roles/mariadb/files/my.cnf
  onecloud/roles/mariadb/tasks/main.yml
Labels: size/XS

#498 安装脚本加上lsusb的命令
  onecloud/roles/utils/detect-os/vars/centos-aarch64.yml
  onecloud/roles/utils/detect-os/vars/centos-x86_64.yml
  onecloud/roles/utils/detect-os/vars/kylin_linux_advanced_server-v10.aarch64.yml
  onecloud/roles/utils/detect-os/vars/kylin_linux_advanced_server-v10.x86_64.yml
Labels: size/XS

#499 Automated cherry pick of #498: 安装脚本加上lsusb的命令
  onecloud/roles/utils/detect-os/vars/centos-aarch64.yml
  onecloud/roles/utils/detect-os/vars/centos-x86_64.yml
  onecloud/roles/utils/detect-os/vars/kylin_linux_advanced_server-v10.aarch64.yml
  onecloud/roles/utils/detect-os/vars/kylin_linux_advanced_server-v10.x86_64.yml
Labels: size/XS

#500 安装脚本加上lsusb的命令 for 3.8
  onecloud/roles/utils/detect-os/vars/centos-aarch64.yml
  onecloud/roles/utils/detect-os/vars/centos-x86_64.yml
Labels: size/XS

#501 add loading and push images step
  onecloud/roles/mariadb/tasks/kylin_linux_advanced_server-aarch64.yml
  onecloud/roles/mariadb/tasks/main.yml
  onecloud/roles/primary-master-node/setup_k8s/tasks/main.yml
Labels: size/L

#502 Automated cherry pick of #501: add loading and push images step
  onecloud/roles/mariadb/tasks/kylin_linux_advanced_server-aarch64.yml
  onecloud/roles/mariadb/tasks/main.yml
  onecloud/roles/primary-master-node/setup_k8s/tasks/main.yml
Labels: size/L

#503 麒麟兼容 sp1/sp2, arm/x86
  onecloud/roles/common/tasks/v3_9_online.yml
  onecloud/roles/utils/detect-os/vars/kylin_linux_advanced_server-v10.aarch64.yml
Labels: size/XS

#504 Automated cherry pick of #503: 麒麟兼容 sp1/sp2, arm/x86
  onecloud/roles/common/tasks/v3_9_online.yml
  onecloud/roles/utils/detect-os/vars/kylin_linux_advanced_server-v10.aarch64.yml
Labels: size/XS

#505 检测 ansible 版本
  onecloud/roles/utils/misc-check/tasks/main.yml
Labels: size/S

#506 Automated cherry pick of #505: 检测 ansible 版本
  onecloud/roles/utils/misc-check/tasks/main.yml
Labels: size/S

#508 feat(helm): update appVersion of helm to v3.9.2
  charts/cloudpods/Chart.yaml
Labels: size/XS

#507 Feature/rex 3.9 add debian 10 support
  lib/cmd.py
  lib/utils.py
  onecloud/roles/common/tasks/centos_7.6_x86_64.yml
  onecloud/roles/common/tasks/debian_10_aarch64.yml
  onecloud/roles/common/tasks/debian_10_x86_64.yml
  onecloud/roles/common/tasks/kylin_linux_advanced_server_v10_aarch64.yml
  onecloud/roles/common/tasks/kylin_linux_advanced_server_v10_x86_64.yml
  onecloud/roles/common/tasks/main.yml
  onecloud/roles/common/tasks/v3_9_online.yml
  onecloud/roles/mariadb/tasks/centos-x86_64.yml
  onecloud/roles/mariadb/tasks/debian-aarch64.yml
  onecloud/roles/mariadb/tasks/debian-x86_64.yml
  onecloud/roles/mariadb/tasks/kylin_linux_advanced_server-x86_64.yml
  onecloud/roles/mariadb/tasks/main.yml
  onecloud/roles/primary-master-node/setup_cloud/tasks/main.yml
  onecloud/roles/utils/detect-os/vars/centos-aarch64.yml
  onecloud/roles/utils/detect-os/vars/centos-x86_64.yml
  onecloud/roles/utils/detect-os/vars/debian-10.aarch64.yml
  onecloud/roles/utils/detect-os/vars/debian-10.x86_64.yml
  onecloud/roles/utils/kernel-check/tasks/main.yml
  run.py
Labels: size/L

#510 Automated cherry pick of #507: 增加debian 10 支持
  lib/cmd.py
  lib/utils.py
  onecloud/roles/common/tasks/centos_7.6_x86_64.yml
  onecloud/roles/common/tasks/debian_10_aarch64.yml
  onecloud/roles/common/tasks/debian_10_x86_64.yml
  onecloud/roles/common/tasks/kylin_linux_advanced_server_v10_aarch64.yml
  onecloud/roles/common/tasks/kylin_linux_advanced_server_v10_x86_64.yml
  onecloud/roles/common/tasks/main.yml
  onecloud/roles/common/tasks/v3_9_online.yml
  onecloud/roles/mariadb/tasks/centos-x86_64.yml
  onecloud/roles/mariadb/tasks/debian-aarch64.yml
  onecloud/roles/mariadb/tasks/debian-x86_64.yml
  onecloud/roles/mariadb/tasks/kylin_linux_advanced_server-x86_64.yml
  onecloud/roles/mariadb/tasks/main.yml
  onecloud/roles/primary-master-node/setup_cloud/tasks/main.yml
  onecloud/roles/utils/detect-os/vars/centos-aarch64.yml
  onecloud/roles/utils/detect-os/vars/centos-x86_64.yml
  onecloud/roles/utils/detect-os/vars/debian-10.aarch64.yml
  onecloud/roles/utils/detect-os/vars/debian-10.x86_64.yml
  onecloud/roles/utils/kernel-check/tasks/main.yml
  run.py
Labels: size/L

#511 fix(deploy): ocboot通过yaml配置文件进行部署时执行环境检测
  run.py
Labels: size/XS

#512 Automated cherry pick of #511: fix(deploy): ocboot通过yaml配置文件进行部署时执行环境检测
  run.py
Labels: size/XS

#514 Automated cherry pick of #513: docs(deploy,ansible,python3): 更新readme文档中,关于Python3/ansible的安装命令
  README.md
Labels: size/S
