Repository yunionio/ocboot, pull requests merged in 2022-01, with the labels that each got.

#288 feat: ocboot add-node subcommand
  README.md
  lib/add_node.py
  lib/cluster.py
  lib/ssh.py
  lib/upgrade.py
  ocboot.py
  onecloud/add-node.yml
  onecloud/roles/worker-node/tasks/main.yml
Labels: size/XL

#290 minor update version tag
  VERSION
Labels: size/XS

#291 Automated cherry pick of #290: minor update version tag
  VERSION
Labels: size/XS

#292 fix(db,mariadb,mysql): 修复 mysql 权限问题
  onecloud/roles/mariadb/tasks/main.yml
Labels: size/XS

#293 Automated cherry pick of #292: fix(db,mariadb,mysql): 修复 mysql 权限问题
  onecloud/roles/mariadb/tasks/main.yml
Labels: size/XS

#294 Automated cherry pick of #292: fix(db,mariadb,mysql): 修复 mysql 权限问题
  onecloud/roles/mariadb/tasks/main.yml
Labels: size/XS

#295 fix(deploy,kernel): 修复 arm 环境安装 kernel 找不到版本的问题
  onecloud/roles/common/tasks/v3_8.yml
Labels: size/XS

#296 Automated cherry pick of #295: fix(deploy,kernel): 修复 arm 环境安装 kernel 找不到版本的问题
  onecloud/roles/common/tasks/v3_8.yml
Labels: size/XS

#297 Fix add-node
  run-in-docker.sh
Labels: size/M

#298 fix yunion directory not exist
  onecloud/roles/registry/tasks/main.yml
Labels: size/XS

#302 备份/恢复时,明确忽略掉iso_install_mode变量
  lib/db.py
  lib/restore.py
Labels: size/XS

#303 Automated cherry pick of #302: 备份/恢复时,明确忽略掉iso_install_mode变量
  lib/db.py
  lib/restore.py
Labels: size/XS

#304 Automated cherry pick of #302: 备份/恢复时,明确忽略掉iso_install_mode变量
  lib/db.py
  lib/restore.py
Labels: size/XS

#305 Automated cherry pick of #302: 备份/恢复时,明确忽略掉iso_install_mode变量
  lib/db.py
  lib/restore.py
Labels: size/XS

#307 minor: add 3.9 files
  onecloud/roles/common/tasks/v3_9.yml
  onecloud/roles/upgrade/common/tasks/v3_8-v3_9.yml
Labels: size/L

#308 Automated cherry pick of #307: minor: add 3.9 files
  onecloud/roles/common/tasks/v3_9.yml
  onecloud/roles/upgrade/common/tasks/v3_8-v3_9.yml
Labels: size/L

#309 minor ansible verbosity level
  lib/cmd.py
Labels: size/XS

#310 Automated cherry pick of #309: minor ansible verbosity level
  lib/cmd.py
Labels: size/XS

#311 Automated cherry pick of #309: minor ansible verbosity level
  lib/cmd.py
Labels: size/XS

#312 Automated cherry pick of #309: minor ansible verbosity level
  lib/cmd.py
Labels: size/XS

#306 Install database optimization
  README.md
  lib/ocboot.py
  onecloud/install-cluster.yml
  onecloud/roles/mariadb/defaults/main.yml
  onecloud/roles/mariadb/tasks/05ha.yml
  onecloud/roles/mariadb/tasks/10ha.yml
  onecloud/roles/mariadb/tasks/20ha.yml
  onecloud/roles/mariadb/tasks/keepalived.yml
  onecloud/roles/mariadb/tasks/main.yml
  onecloud/roles/mariadb/templates/check_interface.sh.j2
  onecloud/roles/mariadb/templates/keepalived.conf.j2
  onecloud/roles/mariadb/templates/my.cnf.j2
  onecloud/roles/mariadb/vars/centos-7.yml
  onecloud/roles/mariadb/vars/debian-10.yml
Labels: size/L

#301 fix mount config file
  run-in-docker.sh
Labels: size/XS

#313 Fix backup/restore cannot be used in the container
  Dockerfile
  lib/restore.py
Labels: size/S
