Repository yunionio/ocboot, pull requests merged in 2022-07, with the labels that each got.

#415 麒麟部署时，不重启os
  d.diff
  onecloud/roles/utils/kernel-check/tasks/main.yml
Labels: size/S

#419 Automated cherry pick of #417: TUI安装界面隐藏yunion字符串
  onecloud/roles/common/tasks/main.yml
  onecloud/roles/common/tasks/master.yml
  onecloud/roles/common/tasks/v3_4.yml
  onecloud/roles/common/tasks/v3_6.yml
  onecloud/roles/common/tasks/v3_7.yml
  onecloud/roles/common/tasks/v3_8.yml
  onecloud/roles/pre-install-common/tasks/main.yml
  onecloud/roles/upgrade/common/tasks/v3_4-v3_6.yml
  onecloud/roles/upgrade/common/tasks/v3_6-v3_7.yml
  onecloud/roles/upgrade/common/tasks/v3_7-v3_8.yml
  onecloud/roles/utils/eip-ha/tasks/main.yml
  onecloud/roles/utils/gpu-init/files/gpu_setup.sh
  onecloud/roles/utils/kernel-check/tasks/main.yml
  onecloud/roles/worker-node/tasks/main.yml
  run.py
Labels: size/M

#417 TUI安装界面隐藏yunion字符串
  onecloud/roles/common/tasks/main.yml
  onecloud/roles/common/tasks/master.yml
  onecloud/roles/common/tasks/v3_4.yml
  onecloud/roles/common/tasks/v3_6.yml
  onecloud/roles/common/tasks/v3_7.yml
  onecloud/roles/common/tasks/v3_8.yml
  onecloud/roles/common/tasks/v3_9.yml
  onecloud/roles/pre-install-common/tasks/main.yml
  onecloud/roles/registry/tasks/main.yml
  onecloud/roles/upgrade/common/tasks/v3_4-v3_6.yml
  onecloud/roles/upgrade/common/tasks/v3_6-v3_7.yml
  onecloud/roles/upgrade/common/tasks/v3_7-v3_8.yml
  onecloud/roles/upgrade/common/tasks/v3_8-v3_9.yml
  onecloud/roles/utils/eip-ha/tasks/main.yml
  onecloud/roles/utils/gpu-init/files/gpu_setup.sh
  onecloud/roles/utils/kernel-check/tasks/main.yml
  onecloud/roles/worker-node/tasks/main.yml
  run.py
Labels: size/M

#418 Automated cherry pick of #417: TUI安装界面隐藏yunion字符串
  onecloud/roles/common/tasks/main.yml
  onecloud/roles/common/tasks/master.yml
  onecloud/roles/common/tasks/v3_4.yml
  onecloud/roles/common/tasks/v3_6.yml
  onecloud/roles/common/tasks/v3_7.yml
  onecloud/roles/common/tasks/v3_8.yml
  onecloud/roles/common/tasks/v3_9.yml
  onecloud/roles/pre-install-common/tasks/main.yml
  onecloud/roles/registry/tasks/main.yml
  onecloud/roles/upgrade/common/tasks/v3_4-v3_6.yml
  onecloud/roles/upgrade/common/tasks/v3_6-v3_7.yml
  onecloud/roles/upgrade/common/tasks/v3_7-v3_8.yml
  onecloud/roles/upgrade/common/tasks/v3_8-v3_9.yml
  onecloud/roles/utils/eip-ha/tasks/main.yml
  onecloud/roles/utils/gpu-init/files/gpu_setup.sh
  onecloud/roles/utils/kernel-check/tasks/main.yml
  onecloud/roles/worker-node/tasks/main.yml
  run.py
Labels: size/M

#420 允许在升级时使用第三方image repo
  lib/upgrade.py
  onecloud/roles/upgrade/primary_master_node/tasks/main.yml
Labels: size/S

#422 Automated cherry pick of #421: 允许在升级时使用第三方image repo
  lib/upgrade.py
  onecloud/roles/upgrade/primary_master_node/tasks/main.yml
Labels: size/S

#421 允许在升级时使用第三方image repo
  lib/upgrade.py
Labels: size/XS

#423 adjust run-in-docker in README
  README.md
Labels: size/M

#425 Automated cherry pick of #424: zentao/bug-view-8490.html: v3.9 开源版本通过yaml配置文件安装v3.9.1时不应该拉取registry.cn-beijing.aliyuncs.com/yunionio仓库的镜像
  Makefile
  lib/ocboot.py
  lib/upgrade.py
  onecloud/roles/primary-master-node/setup_k8s/tasks/main.yml
  onecloud/roles/upgrade/primary_master_node/tasks/main.yml
Labels: size/S

#424 zentao/bug-view-8490.html: v3.9 开源版本通过yaml配置文件安装v3.9.1时不应该拉取registry.…
  Makefile
  lib/ocboot.py
  lib/upgrade.py
  onecloud/roles/primary-master-node/setup_k8s/tasks/main.yml
  onecloud/roles/upgrade/primary_master_node/tasks/main.yml
Labels: size/S

#428 offline deploy for 3.8
  lib/ocboot.py
  onecloud/roles/common/tasks/main.yml
  onecloud/roles/common/tasks/v3_8.yml
  onecloud/roles/utils/detect-os/tasks/main.yml
Labels: size/XS

#427 Automated cherry pick of #426: 离线部署适配
  lib/ocboot.py
  onecloud/roles/common/tasks/main.yml
  onecloud/roles/common/tasks/v3_9.yml
  onecloud/roles/mariadb/tasks/main.yml
  onecloud/roles/primary-master-node/setup_k8s/tasks/main.yml
  onecloud/roles/utils/detect-os/tasks/main.yml
  run.py
Labels: size/M

#426 离线部署适配
  lib/ocboot.py
  onecloud/roles/common/tasks/main.yml
  onecloud/roles/common/tasks/v3_9.yml
  onecloud/roles/mariadb/tasks/main.yml
  onecloud/roles/primary-master-node/setup_k8s/tasks/main.yml
  onecloud/roles/utils/detect-os/tasks/main.yml
  run.py
Labels: size/M

#429 fix: yunionio image repository when version below v3.9
  Makefile
  hack/cherry_pick_pull.sh
  lib/consts.py
  lib/ocboot.py
  lib/upgrade.py
  lib/utils.py
  tests/test_utils.py
Labels: size/M

#431 Automated cherry pick of #429: fix: yunionio image repository when version below v3.9
  Makefile
  hack/cherry_pick_pull.sh
  lib/consts.py
  lib/ocboot.py
  lib/upgrade.py
  lib/utils.py
  tests/test_utils.py
Labels: size/M

#432 初始化yunion repo之前，先清空缓存，避免不同版本之间缓存影响
  onecloud/roles/common/tasks/v3_8.yml
  onecloud/roles/common/tasks/v3_9.yml
  onecloud/roles/pre-install-common/tasks/main.yml
  onecloud/roles/primary-master-node/rsync_rpms/tasks/main.yml
Labels: size/XS

#433 Automated cherry pick of #432: 初始化yunion repo之前，先清空缓存，避免不同版本之间缓存影响
  onecloud/roles/common/tasks/v3_8.yml
  onecloud/roles/common/tasks/v3_9.yml
  onecloud/roles/pre-install-common/tasks/main.yml
  onecloud/roles/primary-master-node/rsync_rpms/tasks/main.yml
Labels: size/XS

#434 初始化yunion repo之前，先清空缓存，避免不同版本之间缓存影响
  onecloud/roles/common/tasks/v3_8.yml
Labels: size/XS

#435 fix: update docker image
  Makefile
  VERSION
  run-in-docker.sh
Labels: size/XS

#438 fix(run-in-docker): upgrade steps
  Dockerfile
  Makefile
  README.md
  onecloud/roles/upgrade/primary_master_node/tasks/main.yml
  run-in-docker.sh
Labels: size/M

#439 Automated cherry pick of #438: fix(run-in-docker): upgrade steps
  Dockerfile
  Makefile
  README.md
  onecloud/roles/upgrade/primary_master_node/tasks/main.yml
  run-in-docker.sh
Labels: size/M

#440 解决光盘部署高可用环境的一些bug
  onecloud/roles/common/tasks/main.yml
  onecloud/roles/common/tasks/v3_8.yml
  onecloud/roles/pre-install-common/tasks/main.yml
  onecloud/roles/primary-master-node/rsync_rpms/tasks/main.yml
  onecloud/roles/utils/detect-os/vars/centos-x86_64.yml
  onecloud/roles/utils/gpu-init/tasks/main.yml
Labels: size/S

#441 解决光盘部署高可用环境的一些bug; 3.9+master
  onecloud/roles/common/tasks/main.yml
  onecloud/roles/common/tasks/v3_8.yml
  onecloud/roles/common/tasks/v3_9.yml
  onecloud/roles/pre-install-common/tasks/main.yml
  onecloud/roles/primary-master-node/rsync_rpms/tasks/main.yml
  onecloud/roles/utils/detect-os/vars/centos-x86_64.yml
  onecloud/roles/utils/gpu-init/tasks/main.yml
Labels: size/S

#442 Automated cherry pick of #441: 解决光盘部署高可用环境的一些bug; 3.9+master
  onecloud/roles/common/tasks/main.yml
  onecloud/roles/common/tasks/v3_8.yml
  onecloud/roles/common/tasks/v3_9.yml
  onecloud/roles/pre-install-common/tasks/main.yml
  onecloud/roles/primary-master-node/rsync_rpms/tasks/main.yml
  onecloud/roles/utils/detect-os/vars/centos-x86_64.yml
  onecloud/roles/utils/gpu-init/tasks/main.yml
Labels: size/S

#443 fix(upgrade): image_repository of yunion and yunionio
  lib/upgrade.py
Labels: size/XS

#444 Automated cherry pick of #443: fix(upgrade): image_repository of yunion and yunionio
  lib/upgrade.py
Labels: size/XS

#445 去掉对epel 的依赖；将所需的rpm 纳入yunion源
  onecloud/roles/pre-install-common/tasks/main.yml
  onecloud/roles/utils/detect-os/vars/centos-aarch64.yml
  onecloud/roles/utils/detect-os/vars/centos-x86_64.yml
Labels: size/XS

#446 Automated cherry pick of #445: 去掉对epel 的依赖；将所需的rpm 纳入yunion源
  onecloud/roles/pre-install-common/tasks/main.yml
  onecloud/roles/utils/detect-os/vars/centos-aarch64.yml
  onecloud/roles/utils/detect-os/vars/centos-x86_64.yml
Labels: size/XS
