Repository yunionio/ocboot, pull requests merged in 2022-06, with the labels that each got.

#401 feat: update VERSION to v3.8.11
  VERSION
Labels: size/XS

#404 3.9 更改 repo url 路径
  lib/upgrade.py
  onecloud/roles/common/tasks/v3_9.yml
Labels: size/XS

#405 Automated cherry pick of #404: 3.9 更改 repo url 路径
  lib/upgrade.py
  onecloud/roles/common/tasks/v3_9.yml
Labels: size/XS

#407 feat(upgrade): spcify ssh port
  lib/cluster.py
  lib/upgrade.py
  tests/test_upgrade.py
Labels: size/M

#410 fix(upgrade): install yunion-qemu-4.2.0 from v3.8 to v3.9
  onecloud/roles/upgrade/common/tasks/v3_8-v3_9.yml
Labels: size/XS

#411 Automated cherry pick of #410: fix(upgrade): install yunion-qemu-4.2.0 from v3.8 to v3.9
  onecloud/roles/upgrade/common/tasks/v3_8-v3_9.yml
Labels: size/XS

#413 minor: 更新arm kylin qemu version
  d.diff
  onecloud/roles/utils/detect-os/vars/kylin_linux_advanced_server-v10.aarch64.yml
Labels: size/S

#414 Automated cherry pick of #413: minor: 更新arm kylin qemu version
  d.diff
  onecloud/roles/utils/detect-os/vars/kylin_linux_advanced_server-v10.aarch64.yml
Labels: size/S
