Repository yunionio/ocboot, pull requests merged in 2022-12, with the labels that each got.

#582 fix(ha,upgrade,iso): iso升级高可用时使用主节点的nodeip而非高可用ip来同步文件
  lib/upgrade.py
  onecloud/roles/upgrade/common/tasks/v3_8-v3_9.yml
  onecloud/roles/upgrade/common/tasks/v3_9-v3_10.yml
Labels: size/S

#583 Automated cherry pick of #582: fix(ha,upgrade,iso): iso升级高可用时使用主节点的nodeip而非高可用ip来同步文件
  lib/upgrade.py
  onecloud/roles/upgrade/common/tasks/v3_8-v3_9.yml
  onecloud/roles/upgrade/common/tasks/v3_9-v3_10.yml
Labels: size/S

#584 Automated cherry pick of #582: fix(ha,upgrade,iso): iso升级高可用时使用主节点的nodeip而非高可用ip来同步文件
  lib/upgrade.py
  onecloud/roles/upgrade/common/tasks/v3_8-v3_9.yml
  onecloud/roles/upgrade/common/tasks/v3_9-v3_10.yml
Labels: size/S

#585 fix(ansible,env): 执行ansible-playbook之前检测并更新PATH变量，确保包含/usr/local/bin
  lib/cmd.py
  run.py
Labels: size/XS

#587 Automated cherry pick of #585: fix(ansible,env): 执行ansible-playbook之前检测并更新PATH变量，确保包含/usr/local/bin
  lib/cmd.py
  run.py
Labels: size/XS

#586 Automated cherry pick of #585: fix(ansible,env): 执行ansible-playbook之前检测并更新PATH变量，确保包含/usr/local/bin
  lib/cmd.py
  run.py
Labels: size/XS

#588 fix(chart): update to v3.9.4 version
  charts/cloudpods/Chart.yaml
  charts/cloudpods/values-prod.yaml
Labels: size/XS

#589 Automated cherry pick of #588: fix(chart): update to v3.9.4 version
  charts/cloudpods/Chart.yaml
  charts/cloudpods/values-prod.yaml
Labels: size/XS

#591 fix(check,hostname): 部署时检测域名是否以数字开头
  onecloud/roles/utils/misc-check/tasks/main.yml
Labels: size/XS

#592 Automated cherry pick of #591: fix(check,hostname): 部署时检测域名是否以数字开头
  onecloud/roles/utils/misc-check/tasks/main.yml
Labels: size/XS

#593 Automated cherry pick of #591: fix(check,hostname): 部署时检测域名是否以数字开头
  onecloud/roles/utils/misc-check/tasks/main.yml
Labels: size/S

#594 Automated cherry pick of #591: fix(check,hostname): 部署时检测域名是否以数字开头
  onecloud/roles/utils/misc-check/tasks/main.yml
Labels: size/XS

#596 fix: update version to 3.9.5
  VERSION
Labels: size/XS

#597 Automated cherry pick of #596: fix: update version to 3.9.5
  VERSION
Labels: size/XS

#598 fix(chart): installation failed when CRD exists
  charts/cloudpods/Chart.yaml
  charts/cloudpods/templates/cluster-crd.yaml
  charts/cloudpods/templates/local-path-csi.yaml
  charts/cloudpods/values-dev.yaml
  charts/cloudpods/values.yaml
Labels: size/S

#599 Automated cherry pick of #598: fix(chart): installation failed when CRD exists
  charts/cloudpods/Chart.yaml
  charts/cloudpods/templates/cluster-crd.yaml
  charts/cloudpods/templates/local-path-csi.yaml
  charts/cloudpods/values-dev.yaml
  charts/cloudpods/values.yaml
Labels: size/S

#600 Automated cherry pick of #598: fix(chart): installation failed when CRD exists
  charts/cloudpods/Chart.yaml
  charts/cloudpods/templates/cluster-crd.yaml
  charts/cloudpods/templates/local-path-csi.yaml
  charts/cloudpods/values-dev.yaml
  charts/cloudpods/values.yaml
Labels: size/S

#604 fix(deploy,python,pips): 确保安装时存在所需的pips
  run.py
Labels: size/XS

#605 Automated cherry pick of #604: fix(deploy,python,pips): 确保安装时存在所需的pips
  run.py
Labels: size/XS

#606 Automated cherry pick of #604: fix(deploy,python,pips): 确保安装时存在所需的pips
  run.py
Labels: size/XS

#608 Automated cherry pick of #595: fix(offline,mysql,mariadb,pip): 解决离线部署mysql依赖的问题
  onecloud/roles/mariadb/tasks/centos-x86_64.yml
Labels: size/S

#609 fix(db,mariadb,pips): minor语法修正
  onecloud/roles/mariadb/tasks/centos-x86_64.yml
Labels: size/XS

#610 Automated cherry pick of #609: fix(db,mariadb,pips): minor语法修正
  onecloud/roles/mariadb/tasks/centos-x86_64.yml
Labels: size/XS

#611 Automated cherry pick of #609: fix(db,mariadb,pips): minor语法修正
  onecloud/roles/mariadb/tasks/centos-x86_64.yml
Labels: size/XS

#612 docs(image,repo): 更新文档,增加自定义image repository 的说明
  README.md
Labels: size/S

#613 Automated cherry pick of #612: docs(image,repo): 更新文档,增加自定义image repository 的说明
  README.md
Labels: size/S

#615 fix(deploy): 修正mastklen计算方式
  onecloud/roles/primary-master-node/setup_cloud/tasks/main.yml
Labels: size/S

#616 Automated cherry pick of #615: fix(deploy): 修正mastklen计算方式
  onecloud/roles/primary-master-node/setup_cloud/tasks/main.yml
Labels: size/S

#617 Automated cherry pick of #615: fix(deploy): 修正mastklen计算方式
  onecloud/roles/primary-master-node/setup_cloud/tasks/main.yml
Labels: size/S

#618 feat(kernel): 3.9～3.10安装新内核：5.4.130-1.yn20221208
  onecloud/roles/utils/kernel-check/tasks/centos-x86_64.yml
Labels: size/XS

#619 Automated cherry pick of #618: feat(kernel): 3.9～3.10安装新内核：5.4.130-1.yn20221208
  onecloud/roles/utils/kernel-check/tasks/centos-x86_64.yml
Labels: size/XS

#620 Automated cherry pick of #618: feat(kernel): 3.9～3.10安装新内核：5.4.130-1.yn20221208
  onecloud/roles/utils/kernel-check/tasks/centos-x86_64.yml
Labels: size/XS

#622 fix(clickhouse): clickhouse deploy: only for centos x86 ISO
  onecloud/roles/clickhouse/deploy/tasks/main.yml
  onecloud/roles/clickhouse/install/tasks/main.yml
Labels: size/L

#623 Automated cherry pick of #622: fix(clickhouse): clickhouse deploy: only for centos x86 ISO
  onecloud/roles/clickhouse/deploy/tasks/main.yml
  onecloud/roles/clickhouse/install/tasks/main.yml
Labels: size/L

#624 Automated cherry pick of #622: fix(clickhouse): clickhouse deploy: only for centos x86 ISO
  onecloud/roles/clickhouse/deploy/tasks/main.yml
  onecloud/roles/clickhouse/install/tasks/main.yml
Labels: size/L

#625 fix(reboot,kernel): 确保重启逻辑
  onecloud/install-cluster.yml
Labels: size/XS

#626 Automated cherry pick of #625: fix(reboot,kernel): 确保重启逻辑
  onecloud/install-cluster.yml
Labels: size/XS

#627 Automated cherry pick of #625: fix(reboot,kernel): 确保重启逻辑
  onecloud/install-cluster.yml
Labels: size/XS

#628 fix(clickhouse): 解决多次重装iso导致clickhouse随机密码变更导致的问题
  onecloud/roles/clickhouse/install/tasks/main.yml
Labels: size/S

#629 Automated cherry pick of #628: fix(clickhouse): 解决多次重装iso导致clickhouse随机密码变更导致的问题
  onecloud/roles/clickhouse/install/tasks/main.yml
Labels: size/S

#631 feat: stop services of nodes
  lib/ocboot.py
  lib/parser.py
  lib/service.py
  lib/start.py
  lib/stop.py
  ocboot.py
  onecloud/roles/utils/start-services/tasks/main.yml
  onecloud/roles/utils/stop-services/tasks/main.yml
  onecloud/roles/utils/stop-services/tasks/stop-container.yml
  onecloud/start-services.yml
  onecloud/stop-services.yml
Labels: size/L

#632 Automated cherry pick of #631: feat: start and stop services of nodes
  lib/ocboot.py
  lib/parser.py
  lib/service.py
  lib/start.py
  lib/stop.py
  ocboot.py
  onecloud/roles/utils/start-services/tasks/main.yml
  onecloud/roles/utils/stop-services/tasks/main.yml
  onecloud/roles/utils/stop-services/tasks/stop-container.yml
  onecloud/start-services.yml
  onecloud/stop-services.yml
Labels: size/L
