Repository yunionio/ocboot, pull requests merged in 2022-11, with the labels that each got.

#546 Automated cherry pick of #545: fix(offline,deploy,rpm): 离线安装时指定本地yunion repo
  onecloud/roles/common/tasks/centos_7_x86_64.yml
Labels: size/XS

#545 fix(offline,deploy,rpm): 离线安装时指定本地yunion repo
  onecloud/roles/common/tasks/centos_7_x86_64.yml
Labels: size/XS

#547 高可用模式下添加打开和关闭sync-user的步骤
  onecloud/roles/primary-master-node/setup_cloud/tasks/main.yml
  onecloud/roles/restore/add-sync-user/tasks/main.yml
  onecloud/roles/restore/rm-sync-user/tasks/main.yml
  onecloud/roles/utils/sync-user/off/tasks/main.yml
  onecloud/roles/utils/sync-user/on/tasks/main.yml
Labels: size/M

#548 Automated cherry pick of #547: 高可用模式下添加打开和关闭sync-user的步骤
  onecloud/roles/primary-master-node/setup_cloud/tasks/main.yml
  onecloud/roles/restore/add-sync-user/tasks/main.yml
  onecloud/roles/restore/rm-sync-user/tasks/main.yml
  onecloud/roles/utils/sync-user/off/tasks/main.yml
  onecloud/roles/utils/sync-user/on/tasks/main.yml
Labels: size/M

#549 fix(update,offline,cluster): 离线 iso 升级集群hotfix
  lib/upgrade.py
  onecloud/roles/upgrade/common/tasks/v3_8-v3_9.yml
Labels: size/S

#550 Automated cherry pick of #549: fix(update,offline,cluster): 离线 iso 升级集群hotfix
  lib/upgrade.py
  onecloud/roles/upgrade/common/tasks/v3_8-v3_9.yml
Labels: size/S

#551 fix(deploy,mariadb): 离线模式、在线模式安装PyMySQL
  onecloud/roles/mariadb/tasks/centos-x86_64.yml
Labels: size/XS

#552 Automated cherry pick of #551: fix(deploy,mariadb): 离线模式、在线模式安装PyMySQL
  onecloud/roles/mariadb/tasks/centos-x86_64.yml
Labels: size/XS

#555 feat(kernel,x86,centos): TASK#4016 centos7 安装 5.4 内核
  onecloud/roles/utils/kernel-check/tasks/centos-x86_64.yml
Labels: size/XS

#556 Automated cherry pick of #555: feat(kernel,x86,centos): TASK#4016 centos7 安装 5.4 内核
  onecloud/roles/utils/kernel-check/tasks/centos-x86_64.yml
Labels: size/XS

#553 feat(host,virt): 检测os的虚拟化类型，如果是虚机则不开启enable-host-agent选项
  README.md
  config-example-allinone.yml
  lib/add_node.py
  lib/ocboot.py
  onecloud/roles/common/tasks/main.yml
  onecloud/roles/master-node/tasks/main.yml
  onecloud/roles/primary-master-node/setup_k8s/tasks/main.yml
  onecloud/roles/utils/detect-os/tasks/main.yml
  onecloud/roles/utils/detect-os/vars/kylin_linux_advanced_server-v10.x86_64.yml
  onecloud/roles/utils/detect-os/vars/uniontech_os_server_20_enterprise-20.aarch64.yml
  onecloud/roles/utils/detect-os/vars/uniontech_os_server_20_enterprise-20.x86_64.yml
  onecloud/roles/worker-node/tasks/main.yml
Labels: size/M

#554 Automated cherry pick of #553: feat(host,virt): 检测os的虚拟化类型，如果是虚机则不开启enable-host-agent选项
  README.md
  config-example-allinone.yml
  lib/add_node.py
  lib/ocboot.py
  onecloud/roles/common/tasks/main.yml
  onecloud/roles/master-node/tasks/main.yml
  onecloud/roles/primary-master-node/setup_k8s/tasks/main.yml
  onecloud/roles/utils/detect-os/tasks/main.yml
  onecloud/roles/utils/detect-os/vars/kylin_linux_advanced_server-v10.x86_64.yml
  onecloud/roles/utils/detect-os/vars/uniontech_os_server_20_enterprise-20.aarch64.yml
  onecloud/roles/utils/detect-os/vars/uniontech_os_server_20_enterprise-20.x86_64.yml
  onecloud/roles/worker-node/tasks/main.yml
Labels: size/M

#559 fix(offline,upgrade): 离线升级容错
  onecloud/roles/upgrade/common/tasks/v3_8-v3_9.yml
Labels: size/XS

#560 Automated cherry pick of #559: fix(offline,upgrade): 离线升级容错
  onecloud/roles/upgrade/common/tasks/v3_8-v3_9.yml
Labels: size/XS

#557 feat(clickhouse,role): 新增clickhouse 角色
  README.md
  lib/ocboot.py
  onecloud/install-cluster.yml
  onecloud/roles/clickhouse/handlers/main.yml
  onecloud/roles/clickhouse/tasks/centos.yml
  onecloud/roles/clickhouse/tasks/debian.yml
  onecloud/roles/clickhouse/tasks/kylin_linux_advanced_server.yml
  onecloud/roles/clickhouse/tasks/main.yml
  onecloud/roles/utils/detect-os/vars/uniontech_os_server_20_enterprise-20.x86_64.yml
  run.py
Labels: size/L

#558 Automated cherry pick of #557: feat(clickhouse,role): 新增clickhouse 角色
  README.md
  lib/ocboot.py
  onecloud/install-cluster.yml
  onecloud/roles/clickhouse/handlers/main.yml
  onecloud/roles/clickhouse/tasks/centos.yml
  onecloud/roles/clickhouse/tasks/debian.yml
  onecloud/roles/clickhouse/tasks/kylin_linux_advanced_server.yml
  onecloud/roles/clickhouse/tasks/main.yml
  onecloud/roles/utils/detect-os/vars/uniontech_os_server_20_enterprise-20.x86_64.yml
  run.py
Labels: size/L

#564 release/3.9 using kernel 3.10.0-1160.53.1.el7.yn20220518.x86_64
  onecloud/roles/utils/kernel-check/tasks/centos-x86_64.yml
Labels: size/XS

#565 Automated cherry pick of #564: 3.9 using kernel 3.10.0-1160.53.1.el7.yn20220518.x86_64
  onecloud/roles/utils/kernel-check/tasks/centos-x86_64.yml
Labels: size/XS

#566 Automated cherry pick of #564: 3.9 using kernel 3.10.0-1160.53.1.el7.yn20220518.x86_64
  onecloud/roles/utils/kernel-check/tasks/centos-x86_64.yml
Labels: size/XS

#561 feat(clickhouse): 拆分clickhouse为安装和部署两个步骤
  README.md
  lib/ocboot.py
  onecloud/install-cluster.yml
  onecloud/roles/clickhouse/deploy/tasks/main.yml
  onecloud/roles/clickhouse/deploy/templates/clickhouse.spec.j2
  onecloud/roles/clickhouse/handlers/main.yml
  onecloud/roles/clickhouse/install/tasks/centos.yml
  onecloud/roles/clickhouse/install/tasks/debian.yml
  onecloud/roles/clickhouse/install/tasks/kylin_linux_advanced_server.yml
  onecloud/roles/clickhouse/install/tasks/main.yml
Labels: size/M

#562 Automated cherry pick of #561: feat(clickhouse): 拆分clickhouse为安装和部署两个步骤
  README.md
  lib/ocboot.py
  onecloud/install-cluster.yml
  onecloud/roles/clickhouse/deploy/tasks/main.yml
  onecloud/roles/clickhouse/deploy/templates/clickhouse.spec.j2
  onecloud/roles/clickhouse/handlers/main.yml
  onecloud/roles/clickhouse/install/tasks/centos.yml
  onecloud/roles/clickhouse/install/tasks/debian.yml
  onecloud/roles/clickhouse/install/tasks/kylin_linux_advanced_server.yml
  onecloud/roles/clickhouse/install/tasks/main.yml
Labels: size/M

#563 Automated cherry pick of #561: feat(clickhouse): 拆分clickhouse为安装和部署两个步骤
  README.md
  lib/ocboot.py
  onecloud/install-cluster.yml
  onecloud/roles/clickhouse/deploy/tasks/main.yml
  onecloud/roles/clickhouse/deploy/templates/clickhouse.spec.j2
  onecloud/roles/clickhouse/handlers/main.yml
  onecloud/roles/clickhouse/install/tasks/centos.yml
  onecloud/roles/clickhouse/install/tasks/debian.yml
  onecloud/roles/clickhouse/install/tasks/kylin_linux_advanced_server.yml
  onecloud/roles/clickhouse/install/tasks/main.yml
Labels: size/M

#570 fix(deploy,host): detect ansible_virtualization_type minor hotfix
  onecloud/roles/utils/detect-os/tasks/main.yml
Labels: size/XS

#571 Automated cherry pick of #570: fix(deploy,host): detect ansible_virtualization_type minor hotfix
  onecloud/roles/utils/detect-os/tasks/main.yml
Labels: size/XS

#572 Automated cherry pick of #570: fix(deploy,host): detect ansible_virtualization_type minor hotfix
  onecloud/roles/utils/detect-os/tasks/main.yml
Labels: size/XS

#567 fix: set affinity for coredns and calico controller
  onecloud/roles/primary-master-node/setup_k8s/tasks/main.yml
  onecloud/roles/utils/k8s/addons/calico/tasks/main.yml
  onecloud/roles/utils/k8s/addons/coredns/tasks/main.yml
  onecloud/roles/utils/k8s/addons/meta/main.yml
  onecloud/roles/utils/k8s/addons/patch/defaults/main.yml
  onecloud/roles/utils/k8s/addons/patch/files/deployment.patch.yml
  onecloud/roles/utils/k8s/addons/patch/tasks/main.yml
  onecloud/upgrade-cluster.yml
Labels: size/M, lgtm

#568 Automated cherry pick of #567: fix: set affinity for coredns and calico controller
  onecloud/roles/primary-master-node/setup_k8s/tasks/main.yml
  onecloud/roles/utils/k8s/addons/calico/tasks/main.yml
  onecloud/roles/utils/k8s/addons/coredns/tasks/main.yml
  onecloud/roles/utils/k8s/addons/meta/main.yml
  onecloud/roles/utils/k8s/addons/patch/defaults/main.yml
  onecloud/roles/utils/k8s/addons/patch/files/deployment.patch.yml
  onecloud/roles/utils/k8s/addons/patch/tasks/main.yml
  onecloud/upgrade-cluster.yml
Labels: size/M

#569 Automated cherry pick of #567: fix: set affinity for coredns and calico controller
  onecloud/roles/primary-master-node/setup_k8s/tasks/main.yml
  onecloud/roles/utils/k8s/addons/calico/tasks/main.yml
  onecloud/roles/utils/k8s/addons/coredns/tasks/main.yml
  onecloud/roles/utils/k8s/addons/meta/main.yml
  onecloud/roles/utils/k8s/addons/patch/defaults/main.yml
  onecloud/roles/utils/k8s/addons/patch/files/deployment.patch.yml
  onecloud/roles/utils/k8s/addons/patch/tasks/main.yml
  onecloud/upgrade-cluster.yml
Labels: size/M

#573 fix(reboot): 安装完毕如需重启则强行重启
  onecloud/roles/primary-master-node/reboot/tasks/main.yml
  onecloud/roles/utils/kernel-check/tasks/main.yml
Labels: size/S

#574 Automated cherry pick of #573: fix(reboot): 安装完毕如需重启则强行重启
  onecloud/roles/primary-master-node/reboot/tasks/main.yml
  onecloud/roles/utils/kernel-check/tasks/main.yml
Labels: size/S

#575 Automated cherry pick of #573: fix(reboot): 安装完毕如需重启则强行重启
  onecloud/roles/primary-master-node/reboot/tasks/main.yml
  onecloud/roles/utils/kernel-check/tasks/main.yml
Labels: size/S

#576 fix(clickhouse): 部署clickhouse之后,更新configmaps
  onecloud/roles/clickhouse/deploy/tasks/main.yml
Labels: size/XS

#577 Automated cherry pick of #576: fix(clickhouse): 部署clickhouse之后,更新configmaps
  onecloud/roles/clickhouse/deploy/tasks/main.yml
Labels: size/XS

#578 Automated cherry pick of #576: fix(clickhouse): 部署clickhouse之后,更新configmaps
  onecloud/roles/clickhouse/deploy/tasks/main.yml
Labels: size/XS
