Repository yunionio/ocboot, pull requests merged in 2023-10, with the labels that each got.

#942 fix(version): update version from v3.10.5 to v3.10.6
  VERSION
  charts/cloudpods/values-dev.yaml
  charts/cloudpods/values-prod.yaml
  charts/cloudpods/values.yaml
  compose/docker-compose.yml
  generate-compose.py
  run-in-docker.sh
Labels: size/M

#943 Automated cherry pick of #942: fix(version): update version from v3.10.5 to v3.10.6
  VERSION
  charts/cloudpods/values-dev.yaml
  charts/cloudpods/values-prod.yaml
  charts/cloudpods/values.yaml
  compose/docker-compose.yml
  generate-compose.py
  run-in-docker.sh
Labels: size/M

#944 Automated cherry pick of #942: fix(version): update version from v3.10.5 to v3.10.6
  VERSION
  charts/cloudpods/values-dev.yaml
  charts/cloudpods/values-prod.yaml
  charts/cloudpods/values.yaml
  compose/docker-compose.yml
  generate-compose.py
  run-in-docker.sh
Labels: size/M

#947 fix(upgrade): offline upgrade issue
  onecloud/roles/utils/detect-os/tasks/main.yml
Labels: size/S

#948 Automated cherry pick of #947: fix(upgrade): offline upgrade issue
  onecloud/roles/utils/detect-os/tasks/main.yml
Labels: size/S

#949 Automated cherry pick of #947: fix(upgrade): offline upgrade issue
  onecloud/roles/utils/detect-os/tasks/main.yml
Labels: size/S

#950 Automated cherry pick of #947: fix(upgrade): offline upgrade issue
  onecloud/roles/utils/detect-os/tasks/main.yml
Labels: size/S

#953 Automated cherry pick of #951: fix(offline): default offline deploy task yaml file
  onecloud/roles/common/tasks/centos_offline.yml
  onecloud/roles/common/tasks/main.yml
Labels: size/XS

#951 fix(offline): default offline deploy task yaml file
  onecloud/roles/common/tasks/centos_offline.yml
  onecloud/roles/common/tasks/main.yml
Labels: size/XS

#952 Automated cherry pick of #951: fix(offline): default offline deploy task yaml file
  onecloud/roles/common/tasks/centos_offline.yml
  onecloud/roles/common/tasks/main.yml
Labels: size/XS

#954 Automated cherry pick of #951: fix(offline): default offline deploy task yaml file
  onecloud/roles/common/tasks/centos_offline.yml
  onecloud/roles/common/tasks/main.yml
Labels: size/XS

#955 fix(kernel): install kernel 20230805 on centos7 x86 since 3.10
  onecloud/roles/utils/kernel-check/tasks/centos-x86_64.yml
  run.py
Labels: size/M

#956 Automated cherry pick of #955: fix(kernel): install kernel 20230805 on centos7 x86 since 3.10
  onecloud/roles/utils/kernel-check/tasks/centos-x86_64.yml
  run.py
Labels: size/M

#957 Automated cherry pick of #955: fix(kernel): install kernel 20230805 on centos7 x86 since 3.10
  onecloud/roles/utils/kernel-check/tasks/centos-x86_64.yml
  run.py
Labels: size/M

#958 fix: update version of config example yaml
  config-example-allinone.yml
  config-example-nodes.yml
Labels: size/XS

#959 Automated cherry pick of #958: fix: update version of config example yaml
  config-example-allinone.yml
  config-example-nodes.yml
Labels: size/XS

#960 Automated cherry pick of #958: fix: update version of config example yaml
  config-example-allinone.yml
  config-example-nodes.yml
Labels: size/XS

#961 Automated cherry pick of #945: 构建双架构registry
  onecloud/install-cluster.yml
  onecloud/roles/pre-install-common/files/yunion-local.repo
  onecloud/roles/primary-master-node/setup_k8s/tasks/main.yml
  onecloud/roles/utils/bin-version-check/tasks/main.yml
  onecloud/roles/utils/load-images/files/load-bi-images.sh
  onecloud/roles/utils/load-images/files/push-images.sh
  onecloud/roles/utils/load-images/tasks/main.yml
Labels: size/L

#945 Feature/rex bi arch registry
  onecloud/install-cluster.yml
  onecloud/roles/pre-install-common/files/yunion-local.repo
  onecloud/roles/primary-master-node/setup_k8s/tasks/main.yml
  onecloud/roles/utils/bin-version-check/tasks/main.yml
  onecloud/roles/utils/load-images/files/load-bi-images.sh
  onecloud/roles/utils/load-images/files/push-images.sh
  onecloud/roles/utils/load-images/tasks/main.yml
Labels: size/L

#962 Automated cherry pick of #945: 构建双架构registry
  onecloud/install-cluster.yml
  onecloud/roles/pre-install-common/files/yunion-local.repo
  onecloud/roles/primary-master-node/setup_k8s/tasks/main.yml
  onecloud/roles/utils/bin-version-check/tasks/main.yml
  onecloud/roles/utils/load-images/files/load-bi-images.sh
  onecloud/roles/utils/load-images/files/push-images.sh
  onecloud/roles/utils/load-images/tasks/main.yml
Labels: size/L

#963 Automated cherry pick of #945: 构建双架构registry
  onecloud/install-cluster.yml
  onecloud/roles/pre-install-common/files/yunion-local.repo
  onecloud/roles/primary-master-node/setup_k8s/tasks/main.yml
  onecloud/roles/utils/load-images/files/load-bi-images.sh
  onecloud/roles/utils/load-images/files/push-images.sh
  onecloud/roles/utils/load-images/tasks/main.yml
Labels: size/L

#964 Revert "构建双架构registry"
  onecloud/install-cluster.yml
  onecloud/roles/pre-install-common/files/yunion-local.repo
  onecloud/roles/primary-master-node/setup_k8s/tasks/main.yml
  onecloud/roles/utils/bin-version-check/tasks/main.yml
  onecloud/roles/utils/load-images/files/load-bi-images.sh
  onecloud/roles/utils/load-images/files/push-images.sh
  onecloud/roles/utils/load-images/tasks/main.yml
Labels: size/L

#965 Automated cherry pick of #964: Revert "构建双架构registry"
  onecloud/install-cluster.yml
  onecloud/roles/pre-install-common/files/yunion-local.repo
  onecloud/roles/primary-master-node/setup_k8s/tasks/main.yml
  onecloud/roles/utils/bin-version-check/tasks/main.yml
  onecloud/roles/utils/load-images/files/load-bi-images.sh
  onecloud/roles/utils/load-images/files/push-images.sh
  onecloud/roles/utils/load-images/tasks/main.yml
Labels: size/L

#966 Automated cherry pick of #964: Revert "构建双架构registry"
  onecloud/install-cluster.yml
  onecloud/roles/pre-install-common/files/yunion-local.repo
  onecloud/roles/primary-master-node/setup_k8s/tasks/main.yml
  onecloud/roles/utils/bin-version-check/tasks/main.yml
  onecloud/roles/utils/load-images/files/load-bi-images.sh
  onecloud/roles/utils/load-images/files/push-images.sh
  onecloud/roles/utils/load-images/tasks/main.yml
Labels: size/L

#967 Automated cherry pick of #964: Revert "构建双架构registry"
  onecloud/install-cluster.yml
  onecloud/roles/pre-install-common/files/yunion-local.repo
  onecloud/roles/primary-master-node/setup_k8s/tasks/main.yml
  onecloud/roles/utils/load-images/files/load-bi-images.sh
  onecloud/roles/utils/load-images/files/push-images.sh
  onecloud/roles/utils/load-images/tasks/main.yml
Labels: size/L

#968 feat: support --pip-mirror/-m args when use run.py
  run.py
Labels: size/M

#969 Automated cherry pick of #968: feat: support --pip-mirror/-m args when use run.py
  run.py
Labels: size/M

#970 Automated cherry pick of #968: feat: support --pip-mirror/-m args when use run.py
  run.py
Labels: size/M

#971 fix: ubuntu allinone installation
  onecloud/roles/common/tasks/ubuntu_22_x86_64.yml
  onecloud/roles/primary-master-node/setup_cloud/tasks/main.yml
  onecloud/roles/utils/k8s/kubelet/extra-args/tasks/main.yml
  run.py
Labels: size/S

#972 Automated cherry pick of #971: fix: ubuntu allinone installation
  onecloud/roles/common/tasks/ubuntu_22_x86_64.yml
  onecloud/roles/primary-master-node/setup_cloud/tasks/main.yml
  onecloud/roles/utils/k8s/kubelet/extra-args/tasks/main.yml
  run.py
Labels: size/S

#975 fix: add enable_host_on_vm to run.py
  lib/parser.py
  run.py
Labels: size/S

#976 Automated cherry pick of #975: fix: add enable_host_on_vm to run.py
  lib/parser.py
  run.py
Labels: size/S

#977 Automated cherry pick of #975: fix: add enable_host_on_vm to run.py
  lib/parser.py
  run.py
Labels: size/S

#978 fix(ubuntu): disable use DNSStubListener
  onecloud/roles/common/tasks/debian.yml
  onecloud/roles/common/tasks/ubuntu_22_x86_64.yml
  onecloud/roles/common/tasks/utils/config_iptables.yml
  onecloud/roles/common/tasks/utils/fix_ovmf_path.yml
  onecloud/roles/common/tasks/utils/unified_cgroup_hierarchy.yml
  onecloud/roles/common/templates/etc_systemd_resolved.conf.j2
  onecloud/roles/primary-master-node/setup_cloud/tasks/main.yml
  onecloud/roles/utils/config-network-manager/tasks/main.yml
Labels: size/L

#980 Automated cherry pick of #978: fix(ubuntu): disable use DNSStubListener
  onecloud/roles/common/tasks/debian.yml
  onecloud/roles/common/tasks/ubuntu_22_x86_64.yml
  onecloud/roles/common/tasks/utils/config_iptables.yml
  onecloud/roles/common/tasks/utils/fix_ovmf_path.yml
  onecloud/roles/common/tasks/utils/unified_cgroup_hierarchy.yml
  onecloud/roles/common/templates/etc_systemd_resolved.conf.j2
  onecloud/roles/primary-master-node/setup_cloud/tasks/main.yml
  onecloud/roles/utils/config-network-manager/tasks/main.yml
Labels: size/L

#979 Automated cherry pick of #978: fix(ubuntu): disable use DNSStubListener
  onecloud/roles/common/tasks/debian.yml
  onecloud/roles/common/tasks/ubuntu_22_x86_64.yml
  onecloud/roles/common/tasks/utils/config_iptables.yml
  onecloud/roles/common/tasks/utils/fix_ovmf_path.yml
  onecloud/roles/common/tasks/utils/unified_cgroup_hierarchy.yml
  onecloud/roles/common/templates/etc_systemd_resolved.conf.j2
  onecloud/roles/primary-master-node/setup_cloud/tasks/main.yml
  onecloud/roles/utils/config-network-manager/tasks/main.yml
Labels: size/L

#981 fix(ubuntu): add node
  lib/service.py
Labels: size/XS

#982 Automated cherry pick of #981: fix(ubuntu): add node
  lib/service.py
Labels: size/XS

#985 Automated cherry pick of #984: fix(add-node): support add worker node inside vm defaultly
  lib/add_node.py
Labels: size/S

#986 Automated cherry pick of #984: fix(add-node): support add worker node inside vm defaultly
  lib/add_node.py
Labels: size/S

#987 fix: multiple nodes installation
  lib/ocboot.py
  lib/service.py
  onecloud/install-cluster.yml
  run.py
Labels: size/M

#988 Automated cherry pick of #987: fix: multiple nodes installation
  lib/ocboot.py
  lib/service.py
  onecloud/install-cluster.yml
  run.py
Labels: size/M

#989 Automated cherry pick of #987: fix: multiple nodes installation
  lib/ocboot.py
  lib/service.py
  onecloud/install-cluster.yml
  run.py
Labels: size/M

#990 fix: debug msg invalid args
  onecloud/roles/master-node/tasks/main.yml
Labels: size/XS

#991 Automated cherry pick of #990: fix: debug msg invalid args
  onecloud/roles/master-node/tasks/main.yml
Labels: size/XS

#994 minor fix for ce / ee, python pips issue
  lib/utils.py
  onecloud/roles/utils/ce-services/tasks/main.yml
  onecloud/roles/utils/ee-services/tasks/main.yml
  run.py
Labels: size/M

#997 Automated cherry pick of #994: minor fix for ce / ee, python pips issue
  lib/utils.py
  onecloud/roles/utils/ce-services/tasks/main.yml
  onecloud/roles/utils/ee-services/tasks/main.yml
  run.py
Labels: size/M

#998 Automated cherry pick of #994: minor fix for ce / ee, python pips issue
  lib/utils.py
  onecloud/roles/utils/ce-services/tasks/main.yml
  onecloud/roles/utils/ee-services/tasks/main.yml
  run.py
Labels: size/M

#999 fix(var): var test enhance
  onecloud/roles/utils/kernel-check/tasks/centos-x86_64.yml
Labels: size/XS

#1000 Automated cherry pick of #999: fix(var): var test enhance
  onecloud/roles/utils/kernel-check/tasks/centos-x86_64.yml
Labels: size/XS

#1001 Automated cherry pick of #999: fix(var): var test enhance
  onecloud/roles/utils/kernel-check/tasks/centos-x86_64.yml
Labels: size/XS

#1002 fix(package): install latest climc-ee by default
  lib/ocboot.py
  onecloud/roles/utils/detect-os/vars/centos-aarch64.yml
  onecloud/roles/utils/detect-os/vars/centos-x86_64.yml
  onecloud/roles/utils/detect-os/vars/kylin_linux_advanced_server-v10.aarch64.yml
  onecloud/roles/utils/detect-os/vars/kylin_linux_advanced_server-v10.x86_64.yml
  onecloud/roles/utils/detect-os/vars/openeuler-aarch64.yml
  onecloud/roles/utils/detect-os/vars/openeuler-x86_64.yml
  onecloud/roles/utils/detect-os/vars/uniontech-kongzi.yml
  onecloud/roles/utils/detect-os/vars/uniontech_os_server_20_enterprise-20.aarch64.yml
  onecloud/roles/utils/detect-os/vars/uniontech_os_server_20_enterprise-20.x86_64.yml
Labels: size/S

#1003 Automated cherry pick of #1002: fix(package): install latest climc-ee by default
  lib/ocboot.py
  onecloud/roles/utils/detect-os/vars/centos-aarch64.yml
  onecloud/roles/utils/detect-os/vars/centos-x86_64.yml
  onecloud/roles/utils/detect-os/vars/kylin_linux_advanced_server-v10.aarch64.yml
  onecloud/roles/utils/detect-os/vars/kylin_linux_advanced_server-v10.x86_64.yml
  onecloud/roles/utils/detect-os/vars/openeuler-aarch64.yml
  onecloud/roles/utils/detect-os/vars/openeuler-x86_64.yml
  onecloud/roles/utils/detect-os/vars/uniontech-kongzi.yml
  onecloud/roles/utils/detect-os/vars/uniontech_os_server_20_enterprise-20.aarch64.yml
  onecloud/roles/utils/detect-os/vars/uniontech_os_server_20_enterprise-20.x86_64.yml
Labels: size/S

#1004 Automated cherry pick of #1002: fix(package): install latest climc-ee by default
  lib/ocboot.py
  onecloud/roles/utils/detect-os/vars/centos-aarch64.yml
  onecloud/roles/utils/detect-os/vars/centos-x86_64.yml
  onecloud/roles/utils/detect-os/vars/kylin_linux_advanced_server-v10.aarch64.yml
  onecloud/roles/utils/detect-os/vars/kylin_linux_advanced_server-v10.x86_64.yml
  onecloud/roles/utils/detect-os/vars/openeuler-x86_64.yml
  onecloud/roles/utils/detect-os/vars/uniontech-kongzi.yml
  onecloud/roles/utils/detect-os/vars/uniontech_os_server_20_enterprise-20.aarch64.yml
  onecloud/roles/utils/detect-os/vars/uniontech_os_server_20_enterprise-20.x86_64.yml
Labels: size/S

#1005 Automated cherry pick of #1002: fix(package): install latest climc-ee by default
  lib/ocboot.py
  onecloud/roles/utils/detect-os/vars/centos-aarch64.yml
  onecloud/roles/utils/detect-os/vars/centos-x86_64.yml
  onecloud/roles/utils/detect-os/vars/kylin_linux_advanced_server-v10.aarch64.yml
  onecloud/roles/utils/detect-os/vars/kylin_linux_advanced_server-v10.x86_64.yml
  onecloud/roles/utils/detect-os/vars/openeuler-x86_64.yml
  onecloud/roles/utils/detect-os/vars/uniontech_os_server_20_enterprise-20.aarch64.yml
  onecloud/roles/utils/detect-os/vars/uniontech_os_server_20_enterprise-20.x86_64.yml
Labels: size/S

#1006 fix(compose): make apigateway depends on region
  lib/compose/manifest/__init__.py
  lib/compose/services/__init__.py
Labels: size/XS

#1007 Automated cherry pick of #1006: fix(compose): make apigateway depends on region
  lib/compose/manifest/__init__.py
  lib/compose/services/__init__.py
Labels: size/XS

#1008 Automated cherry pick of #1006: fix(compose): make apigateway depends on region
  lib/compose/manifest/__init__.py
  lib/compose/services/__init__.py
Labels: size/XS
