Repository yunionio/ocboot, pull requests merged in 2023-12, with the labels that each got.

#1054 feat(dns): 新增自定义dns入口
  lib/ocboot.py
  lib/utils.py
  onecloud/roles/primary-master-node/setup_cloud/tasks/main.yml
  run.py
Labels: size/M

#1055 Automated cherry pick of #1054: feat(dns): 新增自定义dns入口
  lib/ocboot.py
  lib/utils.py
  onecloud/roles/primary-master-node/setup_cloud/tasks/main.yml
  run.py
Labels: size/M

#1056 Automated cherry pick of #1054: feat(dns): 新增自定义dns入口
  lib/ocboot.py
  lib/utils.py
  onecloud/roles/primary-master-node/setup_cloud/tasks/main.yml
  run.py
Labels: size/M

#1051 feat: ubuntu grub config support
  onecloud/roles/utils/gpu-init/files/gpu_setup.sh
  onecloud/roles/utils/kernel-check/files/hugetlb_setup.sh
Labels: size/XS

#1052 Automated cherry pick of #1051: feat: ubuntu grub config support
  onecloud/roles/utils/gpu-init/files/gpu_setup.sh
  onecloud/roles/utils/kernel-check/files/hugetlb_setup.sh
Labels: size/XS

#1053 Automated cherry pick of #1051: feat: ubuntu grub config support
  onecloud/roles/utils/gpu-init/files/gpu_setup.sh
  onecloud/roles/utils/kernel-check/files/hugetlb_setup.sh
Labels: size/XS

#1059 Automated cherry pick of #1057: fix: wrong NetworkManager configuration of interface-name
  onecloud/roles/utils/config-network-manager/tasks/main.yml
Labels: size/XS

#1063 feat(kylin): kylin sp3 comp
  onecloud/roles/common/tasks/centos_7_x86_64.yml
  onecloud/roles/common/tasks/main.yml
  onecloud/roles/utils/bin-version-check/tasks/main.yml
  onecloud/roles/utils/misc-check/tasks/os.yml
Labels: size/M

#1065 Automated cherry pick of #1063: feat(kylin): kylin sp3 comp
  onecloud/roles/common/tasks/centos_7_x86_64.yml
  onecloud/roles/common/tasks/main.yml
  onecloud/roles/utils/bin-version-check/tasks/main.yml
  onecloud/roles/utils/misc-check/tasks/os.yml
Labels: size/M

#1067 fix: use include_tasks because the include module is deprecated
  onecloud/roles/utils/kernel-check/tasks/main.yml
Labels: size/XS

#1068 Automated cherry pick of #1067: fix: use include_tasks because the include module is deprecated
  onecloud/roles/utils/kernel-check/tasks/main.yml
Labels: size/XS

#1071 feat(ansible): 兼容ansible 2.16
  onecloud/roles/common/tasks/ubuntu_22_x86_64.yml
  onecloud/roles/utils/bin-version-check/tasks/main.yml
  onecloud/roles/utils/bin-version-check/vars/default.yml
  onecloud/roles/utils/misc-check/tasks/os.yml
Labels: size/M

#1072 Automated cherry pick of #1071: feat(ansible): 兼容ansible 2.16
  onecloud/roles/common/tasks/ubuntu_22_x86_64.yml
  onecloud/roles/utils/bin-version-check/tasks/main.yml
  onecloud/roles/utils/bin-version-check/vars/default.yml
  onecloud/roles/utils/misc-check/tasks/os.yml
Labels: size/M

#1073 Automated cherry pick of #1071: feat(ansible): 兼容ansible 2.16
  onecloud/roles/common/tasks/ubuntu_22_x86_64.yml
  onecloud/roles/utils/bin-version-check/tasks/main.yml
  onecloud/roles/utils/bin-version-check/vars/default.yml
  onecloud/roles/utils/misc-check/tasks/os.yml
Labels: size/M

#1074 fix(upgrade): upgrade to 3.11 from 3.10
  onecloud/roles/upgrade/common/tasks/v3_10-v3_11.yml
Labels: size/M

#1075 Automated cherry pick of #1074: fix(upgrade): upgrade to 3.11 from 3.10
  onecloud/roles/upgrade/common/tasks/v3_10-v3_11.yml
Labels: size/M

#1079 fix(add-node): 3.11 兼容 add-node hotfix
  onecloud/roles/common/tasks/v3_11_online.yml
Labels: size/M

#1080 Automated cherry pick of #1079: fix(add-node): 3.11 comp
  onecloud/roles/common/tasks/v3_11_online.yml
Labels: size/M

#1076 fix: set mysql group_concat_max_len=max_allowed_packet
  lib/restore.py
  onecloud/roles/mariadb-ha/templates/my.cnf.j2
  onecloud/roles/mariadb/files/my.cnf
Labels: size/XS

#1081 fix(version): version update from 3.10.7 to 3.10.8
  VERSION
  charts/cloudpods/values-dev.yaml
  charts/cloudpods/values-prod.yaml
  charts/cloudpods/values.yaml
  compose/docker-compose.yml
  generate-compose.py
  run-in-docker.sh
Labels: size/M

#1082 Automated cherry pick of #1081: fix(version): version update from 3.10.7 3.10.8
  VERSION
  charts/cloudpods/values-dev.yaml
  charts/cloudpods/values-prod.yaml
  charts/cloudpods/values.yaml
  compose/docker-compose.yml
  generate-compose.py
  run-in-docker.sh
Labels: size/M

#1083 Automated cherry pick of #1081: fix(version): version update from 3.10.7 3.10.8
  VERSION
  charts/cloudpods/values-dev.yaml
  charts/cloudpods/values-prod.yaml
  charts/cloudpods/values.yaml
  compose/docker-compose.yml
  generate-compose.py
  run-in-docker.sh
Labels: size/M

#1084 fix(ansible): ansible 2.16 compatability
  onecloud/roles/common/tasks/ubuntu_22_x86_64.yml
  onecloud/roles/utils/kernel-check/tasks/centos-x86_64.yml
  run.py
Labels: size/S

#1085 Automated cherry pick of #1084: fix(ansible): ansible 2.16 compatability
  onecloud/roles/common/tasks/ubuntu_22_x86_64.yml
  onecloud/roles/utils/kernel-check/tasks/centos-x86_64.yml
  run.py
Labels: size/S

#1087 feat: ensure climc completion in ~/.bashrc
  onecloud/roles/primary-master-node/setup_cloud/tasks/main.yml
Labels: lgtm

#1088 Automated cherry pick of #1087: feat: ensure climc completion in ~/.bashrc
  onecloud/roles/primary-master-node/setup_cloud/tasks/main.yml
Labels: size/S

#1090 fix(dockerfile): update dockerfile for ansible-base
  Dockerfile
  README.md
Labels: size/S

#1091 Automated cherry pick of #1090: fix(dockerfile): update dockerfile for ansible-base
  Dockerfile
  README.md
Labels: size/S

#1092 Automated cherry pick of #1090: fix(dockerfile): update dockerfile for ansible-base
  Dockerfile
  README.md
Labels: size/S

#1093 fix(ubuntu): ubunbu 22.04 arm64 兼容
  onecloud/roles/common/tasks/ubuntu_22.yml
  onecloud/roles/mariadb/tasks/main.yml
  onecloud/roles/mariadb/tasks/pre-ubuntu-22.aarch64.yml
  onecloud/roles/utils/detect-os/vars/debian.yml
  onecloud/roles/utils/detect-os/vars/ubuntu-22.x86_64.yml
Labels: size/M

#1094 Automated cherry pick of #1093: fix(ubuntu): ubunbu 22.04 arm64 兼容
  onecloud/roles/common/tasks/ubuntu_22.yml
  onecloud/roles/mariadb/tasks/main.yml
  onecloud/roles/mariadb/tasks/pre-ubuntu-22.aarch64.yml
  onecloud/roles/utils/detect-os/vars/debian.yml
  onecloud/roles/utils/detect-os/vars/ubuntu-22.x86_64.yml
Labels: size/M

#1095 Automated cherry pick of #1093: fix(ubuntu): ubunbu 22.04 arm64 兼容
  onecloud/roles/common/tasks/ubuntu_22.yml
  onecloud/roles/mariadb/tasks/main.yml
  onecloud/roles/mariadb/tasks/pre-ubuntu-22.aarch64.yml
  onecloud/roles/utils/detect-os/vars/debian.yml
  onecloud/roles/utils/detect-os/vars/ubuntu-22.x86_64.yml
Labels: size/M

#1096 feat(docker-compose): add esxi-agent and host-deployer services
  compose/docker-compose.yml
  lib/compose/manifest/__init__.py
  lib/compose/object.py
  lib/compose/services/__init__.py
  lib/compose/services/cluster_service.py
  lib/compose/services/host_deployer.py
Labels: size/L

#1097 Automated cherry pick of #1096: feat(docker-compose): add esxi-agent and host-deployer services
  compose/docker-compose.yml
  lib/compose/manifest/__init__.py
  lib/compose/object.py
  lib/compose/services/__init__.py
  lib/compose/services/cluster_service.py
  lib/compose/services/host_deployer.py
Labels: size/L

#1098 Automated cherry pick of #1096: feat(docker-compose): add esxi-agent and host-deployer services
  compose/docker-compose.yml
  lib/compose/manifest/__init__.py
  lib/compose/object.py
  lib/compose/services/__init__.py
  lib/compose/services/cluster_service.py
  lib/compose/services/host_deployer.py
Labels: size/L

#1099 update version to v3.10.9
  VERSION
  charts/cloudpods/values-dev.yaml
  charts/cloudpods/values-prod.yaml
  charts/cloudpods/values.yaml
  compose/docker-compose.yml
  generate-compose.py
  run-in-docker.sh
Labels: size/M

#1100 Automated cherry pick of #1099: update version to v3.10.9
  VERSION
  charts/cloudpods/values-dev.yaml
  charts/cloudpods/values-prod.yaml
  charts/cloudpods/values.yaml
  compose/docker-compose.yml
  generate-compose.py
  run-in-docker.sh
Labels: size/M

#1101 Automated cherry pick of #1099: update version to v3.10.9
  VERSION
  charts/cloudpods/values-dev.yaml
  charts/cloudpods/values-prod.yaml
  charts/cloudpods/values.yaml
  compose/docker-compose.yml
  generate-compose.py
  run-in-docker.sh
Labels: size/M

#1102 fix(version): update version to v3.10.10
  VERSION
  charts/cloudpods/values-dev.yaml
  charts/cloudpods/values-prod.yaml
  charts/cloudpods/values.yaml
  compose/docker-compose.yml
  generate-compose.py
  run-in-docker.sh
Labels: size/M

#1103 Automated cherry pick of #1102: fix(version): update version to v3.10.10
  VERSION
  charts/cloudpods/values-dev.yaml
  charts/cloudpods/values-prod.yaml
  charts/cloudpods/values.yaml
  compose/docker-compose.yml
  generate-compose.py
  run-in-docker.sh
Labels: size/M

#1104 Automated cherry pick of #1102: fix(version): update version to v3.10.10
  VERSION
  charts/cloudpods/values-dev.yaml
  charts/cloudpods/values-prod.yaml
  charts/cloudpods/values.yaml
  compose/docker-compose.yml
  generate-compose.py
  run-in-docker.sh
Labels: size/M
