Repository yunionio/ocboot, pull requests merged in 2023-09, with the labels that each got.

#927 fix(python3): 确保python3执行 py 脚本
  lib/add_lbagent.py
  lib/ansible.py
  lib/auto_backup.py
  lib/backup.py
  lib/cluster.py
  lib/cmd.py
  lib/color.py
  lib/db.py
  lib/install.py
  lib/service.py
  ocboot.py
  tests/test_upgrade.py
Labels: size/M

#928 Automated cherry pick of #927: fix(确保python3执行 py 脚本): 确保python3执行 py 脚本
  lib/ansible.py
  lib/auto_backup.py
  lib/backup.py
  lib/cluster.py
  lib/cmd.py
  lib/color.py
  lib/db.py
  lib/install.py
  lib/service.py
  tests/test_upgrade.py
Labels: size/M

#929 Automated cherry pick of #927: fix(确保python3执行 py 脚本): 确保python3执行 py 脚本
  lib/add_lbagent.py
  lib/ansible.py
  lib/auto_backup.py
  lib/backup.py
  lib/cluster.py
  lib/cmd.py
  lib/color.py
  lib/db.py
  lib/install.py
  lib/service.py
  ocboot.py
  tests/test_upgrade.py
Labels: size/M

#931 Automated cherry pick of #930: fix(debian): add climc-ee bin for debian
  onecloud/roles/utils/detect-os/vars/debian.yml
Labels: size/XS

#930 fix(debian): add climc-ee bin for debian
  onecloud/roles/utils/detect-os/vars/debian.yml
Labels: size/XS

#934 Automated cherry pick of #933: fix(version): 版本号升级到v3.10.5
  VERSION
  charts/cloudpods/values-dev.yaml
  charts/cloudpods/values-prod.yaml
  charts/cloudpods/values.yaml
  compose/docker-compose.yml
  generate-compose.py
  run-in-docker.sh
Labels: size/M

#933 fix(version): 版本号升级到v3.10.5
  VERSION
  charts/cloudpods/values-dev.yaml
  charts/cloudpods/values-prod.yaml
  charts/cloudpods/values.yaml
  compose/docker-compose.yml
  generate-compose.py
  run-in-docker.sh
Labels: size/M

#936 fix(ubuntu): ubuntu repo deb update
  onecloud/roles/utils/detect-os/vars/ubuntu-22.x86_64.yml
Labels: size/XS

#937 Automated cherry pick of #936: fix(ubuntu): ubuntu repo deb update
  onecloud/roles/utils/detect-os/vars/debian.yml
Labels: size/XS

#939 fix(compose): update some service images to v3.10.5
  compose/docker-compose.yml
  lib/compose/manifest/__init__.py
Labels: size/S

#940 Automated cherry pick of #939: fix(compose): update some service images to v3.10.5
  compose/docker-compose.yml
  lib/compose/manifest/__init__.py
Labels: size/S

#941 Automated cherry pick of #939: fix(compose): update some service images to v3.10.5
  compose/docker-compose.yml
  lib/compose/manifest/__init__.py
Labels: size/S
