Repository yunionio/ocboot, pull requests merged in 2023-02, with the labels that each got.

#659 feat: clear component when upgrading
  onecloud/roles/upgrade/primary_master_node/files/turn-off-operator-clear-component.patch.yml
  onecloud/roles/upgrade/primary_master_node/files/turn-on-operator-clear-component.patch.yml
  onecloud/roles/upgrade/primary_master_node/tasks/main.yml
Labels: size/M

#661 Automated cherry pick of #659: feat: clear component when upgrading
  onecloud/roles/upgrade/primary_master_node/files/turn-off-operator-clear-component.patch.yml
  onecloud/roles/upgrade/primary_master_node/files/turn-on-operator-clear-component.patch.yml
  onecloud/roles/upgrade/primary_master_node/tasks/main.yml
Labels: size/M

#660 Automated cherry pick of #659: feat: clear component when upgrading
  onecloud/roles/upgrade/primary_master_node/files/turn-off-operator-clear-component.patch.yml
  onecloud/roles/upgrade/primary_master_node/files/turn-on-operator-clear-component.patch.yml
  onecloud/roles/upgrade/primary_master_node/tasks/main.yml
Labels: size/M

#662 fix(host,node): 添加计算节点时，启用host agent的逻辑应该和控制节点的一致
  lib/add_node.py
  lib/ocboot.py
Labels: size/XS

#663 Automated cherry pick of #662: fix(host,node): 添加计算节点时，启用host agent的逻辑应该和控制节点的一致
  lib/add_node.py
  lib/ocboot.py
Labels: size/XS

#664 Automated cherry pick of #662: fix(host,node): 添加计算节点时，启用host agent的逻辑应该和控制节点的一致
  lib/add_node.py
  lib/ocboot.py
Labels: size/XS

#665 feat(upgrade,cloudpack): 升级相关：兼容cloudpack的升级策略
  onecloud/roles/upgrade/primary_master_node/tasks/main.yml
  onecloud/roles/utils/detect-os/tasks/main.yml
Labels: size/S

#666 Automated cherry pick of #665: feat(upgrade,cloudpack): 升级相关：兼容cloudpack的升级策略
  onecloud/roles/upgrade/primary_master_node/tasks/main.yml
  onecloud/roles/utils/detect-os/tasks/main.yml
Labels: size/S

#667 Automated cherry pick of #665: feat(upgrade,cloudpack): 升级相关：兼容cloudpack的升级策略
  onecloud/roles/upgrade/primary_master_node/tasks/main.yml
  onecloud/roles/utils/detect-os/tasks/main.yml
Labels: size/S

#668 fix(add-node): add enable-host-on-vm option
  lib/add_node.py
Labels: size/S

#669 Automated cherry pick of #668: fix(add-node): add enable-host-on-vm option
  lib/add_node.py
Labels: size/S

#670 Automated cherry pick of #668: fix(add-node): add enable-host-on-vm option
  lib/add_node.py
Labels: size/S

#671 feat: add-lbagent
  README.md
  lib/add_lbagent.py
  lib/add_node.py
  lib/ocboot.py
  lib/parser.py
  lib/service.py
  ocboot.py
  onecloud/add-node.yml
  onecloud/roles/utils/kernel-check/tasks/main.yml
  onecloud/roles/worker-node/lbagent/tasks/main.yml
  onecloud/roles/worker-node/lbagent/templates/lbagent.conf.j2
  onecloud/roles/worker-node/tasks/main.yml
Labels: size/L

#672 Automated cherry pick of #671: feat: add-lbagent
  README.md
  lib/add_lbagent.py
  lib/add_node.py
  lib/ocboot.py
  lib/parser.py
  lib/service.py
  ocboot.py
  onecloud/add-node.yml
  onecloud/roles/utils/kernel-check/tasks/main.yml
  onecloud/roles/worker-node/lbagent/tasks/main.yml
  onecloud/roles/worker-node/lbagent/templates/lbagent.conf.j2
  onecloud/roles/worker-node/tasks/main.yml
Labels: size/L

#673 fix: set grub cmdline by order
  onecloud/roles/utils/gpu-init/files/gpu_setup.sh
  onecloud/roles/utils/kernel-check/files/hugetlb_setup.sh
Labels: size/M

#674 Automated cherry pick of #673: fix: set grub cmdline by order
  onecloud/roles/utils/gpu-init/files/gpu_setup.sh
  onecloud/roles/utils/kernel-check/files/hugetlb_setup.sh
Labels: size/M

#675 Automated cherry pick of #673: fix: set grub cmdline by order
  onecloud/roles/utils/gpu-init/files/gpu_setup.sh
Labels: size/S

#679 fix(cloudpack): cloudpack 升级优化
  onecloud/roles/upgrade/primary_master_node/tasks/main.yml
Labels: size/S

#680 Automated cherry pick of #679: fix(cloudpack): cloudpack 升级优化
  onecloud/roles/upgrade/primary_master_node/tasks/main.yml
Labels: size/S

#681 Automated cherry pick of #679: fix(cloudpack): cloudpack 升级优化
  onecloud/roles/upgrade/primary_master_node/tasks/main.yml
Labels: size/S

#682 fix(iso,cloudpack): iso普通模式安装判断是否启用hyperImage逻辑更新
  onecloud/roles/primary-master-node/setup_cloud/tasks/main.yml
Labels: size/S

#683 Automated cherry pick of #682: fix(iso,cloudpack): iso普通模式安装判断是否启用hyperImage逻辑更新
  onecloud/roles/primary-master-node/setup_cloud/tasks/main.yml
Labels: size/S

#684 Automated cherry pick of #682: fix(iso,cloudpack): iso普通模式安装判断是否启用hyperImage逻辑更新
  onecloud/roles/primary-master-node/setup_cloud/tasks/main.yml
Labels: size/S

#685 fix(upgrade): change backup dir
  onecloud/roles/upgrade/primary_master_node/tasks/main.yml
Labels: size/XS

#686 Automated cherry pick of #685: fix(upgrade): change backup dir
  onecloud/roles/upgrade/primary_master_node/tasks/main.yml
Labels: size/XS

#688 fix(upgrade): use sed clean metadata of k8s object
  onecloud/roles/upgrade/primary_master_node/files/clean_k8s_obj.sed
  onecloud/roles/upgrade/primary_master_node/tasks/main.yml
Labels: size/S

#693 kernel boot params add mgag200.modeset=0
  onecloud/roles/utils/gpu-init/files/gpu_setup.sh
Labels: size/XS
