Repository yunionio/ocboot, pull requests merged in 2023-03, with the labels that each got.

#698 fix: toggle -sync-user option when installing cluster
  onecloud/roles/primary-master-node/setup_cloud/tasks/main.yml
Labels: size/S

#699 Automated cherry pick of #698: fix: toggle -sync-user option when installing cluster
  onecloud/roles/primary-master-node/setup_cloud/tasks/main.yml
Labels: size/S

#701 fix: set KUBECONFIG for turn-off sync-user
  onecloud/roles/utils/sync-user/off/tasks/main.yml
Labels: size/XS

#703 Automated cherry pick of #701: fix: set KUBECONFIG for turn-off sync-user
  onecloud/roles/utils/sync-user/off/tasks/main.yml
Labels: size/XS

#704 fix(gpu_setup): set intel_iommu=on when CPU is intel model
  onecloud/roles/utils/gpu-init/files/gpu_setup.sh
Labels: size/S

#705 Automated cherry pick of #704: fix(gpu_setup): set intel_iommu=on when CPU is intel model
  onecloud/roles/utils/gpu-init/files/gpu_setup.sh
Labels: size/S

#706 Automated cherry pick of #704: fix(gpu_setup): set intel_iommu=on when CPU is intel model
  onecloud/roles/utils/gpu-init/files/gpu_setup.sh
Labels: size/S

#707 update VERSION to v3.8.8
  VERSION
Labels: size/XS

#708 Automated cherry pick of #707: update VERSION to v3.8.8
  VERSION
Labels: size/XS

#709 Automated cherry pick of #707: update VERSION to v3.8.8
  VERSION
Labels: size/XS

#710 fix: upgrade chart version to v3.9.8
  charts/cloudpods/Chart.yaml
  charts/cloudpods/values-dev.yaml
  charts/cloudpods/values-prod.yaml
  charts/cloudpods/values.yaml
Labels: size/S

#711 Automated cherry pick of #710: fix: upgrade chart version to v3.9.8
  charts/cloudpods/Chart.yaml
  charts/cloudpods/values-dev.yaml
  charts/cloudpods/values-prod.yaml
  charts/cloudpods/values.yaml
Labels: size/S

#712 Automated cherry pick of #710: fix: upgrade chart version to v3.9.8
  charts/cloudpods/Chart.yaml
  charts/cloudpods/values-dev.yaml
  charts/cloudpods/values-prod.yaml
  charts/cloudpods/values.yaml
Labels: size/S

#716 fix(clickhouse): 更新clickhouse server 内存配置
  onecloud/roles/clickhouse/install/tasks/main.yml
Labels: size/XS

#717 Automated cherry pick of #716: fix(clickhouse): 更新内存配置
  onecloud/roles/clickhouse/install/tasks/main.yml
Labels: size/XS

#718 Automated cherry pick of #716: fix(clickhouse): 更新内存配置
  onecloud/roles/clickhouse/install/tasks/main.yml
Labels: size/XS

#713 新增ee/ce切换的入口
  lib/ce.py
  lib/ee.py
  ocboot.py
  onecloud/ce-services.yml
  onecloud/ee-services.yml
  onecloud/roles/utils/ce-services/tasks/main.yml
  onecloud/roles/utils/ee-services/tasks/main.yml
Labels: size/M

#714 Automated cherry pick of #713: 新增ee/ce切换的入口
  lib/ce.py
  lib/ee.py
  ocboot.py
  onecloud/ce-services.yml
  onecloud/ee-services.yml
  onecloud/roles/utils/ce-services/tasks/main.yml
  onecloud/roles/utils/ee-services/tasks/main.yml
Labels: size/M

#715 Automated cherry pick of #713: 新增ee/ce切换的入口
  lib/ce.py
  lib/ee.py
  ocboot.py
  onecloud/ce-services.yml
  onecloud/ee-services.yml
  onecloud/roles/utils/ce-services/tasks/main.yml
  onecloud/roles/utils/ee-services/tasks/main.yml
Labels: size/M

#719 fix: update README version to v3.9.8
  README.md
  config-example-allinone.yml
  config-example-nodes.yml
Labels: size/S

#720 Automated cherry pick of #719: fix: update README version to v3.9.8
  README.md
  config-example-allinone.yml
  config-example-nodes.yml
Labels: size/S

#722 fix(update,openvswitch): 3.9升级到3.10的时候需要升级 openvswith rpm包到 2.12.4-1
  onecloud/roles/upgrade/common/tasks/v3_9-v3_10.yml
Labels: size/XS

#723 Automated cherry pick of #722: fix(update,openvswitch): 3.9升级到3.10的时候需要升级 openvswith rpm包到 2.12.4-1
  onecloud/roles/upgrade/common/tasks/v3_9-v3_10.yml
Labels: size/XS

#729 use mariadb 10.9.5
  charts/cloudpods/templates/mysql.yaml
  charts/cloudpods/values-dev.yaml
  charts/cloudpods/values-prod.yaml
  charts/cloudpods/values.yaml
  compose/docker-compose.yml
  lib/compose/services/mysql.py
Labels: size/M

#730 Automated cherry pick of #729: use mariadb 10.9.5
  charts/cloudpods/templates/mysql.yaml
  charts/cloudpods/values-dev.yaml
  charts/cloudpods/values-prod.yaml
  charts/cloudpods/values.yaml
  compose/docker-compose.yml
  lib/compose/services/mysql.py
Labels: size/M

#731 feat(compose): add cloudmon service
  compose/docker-compose.yml
  lib/compose/manifest/__init__.py
  lib/compose/services/__init__.py
  lib/compose/services/cluster_service.py
Labels: size/L

#732 Automated cherry pick of #731: feat(compose): add cloudmon service
  compose/docker-compose.yml
  lib/compose/manifest/__init__.py
  lib/compose/services/__init__.py
  lib/compose/services/cluster_service.py
Labels: size/L
