Repository yunionio/ocboot, pull requests merged in 2023-07, with the labels that each got.

#823 fix(os): os发行版判断相关hotfix
  onecloud/roles/common/tasks/v3_10_online.yml
  onecloud/roles/common/tasks/v3_9_online.yml
  onecloud/roles/mariadb-ha/tasks/main.yml
  onecloud/roles/registry/tasks/main.yml
  onecloud/roles/utils/detect-os/vars/centos-aarch64.yml
  onecloud/roles/utils/detect-os/vars/centos-x86_64.yml
  onecloud/roles/utils/detect-os/vars/kylin_linux_advanced_server-v10.aarch64.yml
  onecloud/roles/utils/detect-os/vars/kylin_linux_advanced_server-v10.x86_64.yml
  onecloud/roles/utils/detect-os/vars/openeuler-x86_64.yml
  onecloud/roles/utils/gpu-init/tasks/main.yml
  onecloud/roles/utils/kernel-check/tasks/main.yml
  onecloud/roles/utils/misc-check/tasks/main.yml
Labels: size/S

#821 fix(deploy): debian compatible gpu setup and hugetlb setup
  onecloud/roles/utils/gpu-init/files/gpu_setup.sh
  onecloud/roles/utils/kernel-check/files/hugetlb_setup.sh
Labels: size/L

#822 Automated cherry pick of #821 upstream release 3.10
  onecloud/roles/utils/gpu-init/files/gpu_setup.sh
  onecloud/roles/utils/kernel-check/files/hugetlb_setup.sh
Labels: size/L

#826 fix(deploy): add debug msg to show init args
  onecloud/roles/primary-master-node/setup_k8s/tasks/main.yml
Labels: size/XS

#827 Automated cherry pick of #826: fix(deploy): add debug msg to show init args
  onecloud/roles/primary-master-node/setup_k8s/tasks/main.yml
Labels: size/XS

#828 release v3.10.3
  VERSION
  charts/cloudpods/values-dev.yaml
  charts/cloudpods/values-prod.yaml
  charts/cloudpods/values.yaml
  compose/docker-compose.yml
  generate-compose.py
  run-in-docker.sh
Labels: size/M

#831 fix(debian): install libcapstone4 for qemu under debian 11
  onecloud/roles/common/tasks/debian.yml
Labels: size/XS

#832 Automated cherry pick of #831: fix(debian): install libcapstone4 for qemu under debian 11
  onecloud/roles/common/tasks/debian.yml
Labels: size/XS

#833 fix(networkmanager): 在重启networkmanager 前后，确保resolev.conf 不改变
  onecloud/roles/utils/config-network-manager/handlers/main.yml
  onecloud/roles/utils/config-network-manager/tasks/main.yml
Labels: size/XS

#834 Automated cherry pick of #833: fix(networkmanager): 在重启networkmanager 前后，确保resolev.conf 不改变
  onecloud/roles/utils/config-network-manager/handlers/main.yml
  onecloud/roles/utils/config-network-manager/tasks/main.yml
Labels: size/XS

#835 Automated cherry pick of #833: fix(networkmanager): 在重启networkmanager 前后，确保resolev.conf 不改变
  onecloud/roles/utils/config-network-manager/handlers/main.yml
  onecloud/roles/utils/config-network-manager/tasks/main.yml
Labels: size/S

#836 fix(repo): 对在线、离线安装，启用不同的repo
  onecloud/roles/clickhouse/install/tasks/centos.yml
  onecloud/roles/clickhouse/install/tasks/kylin_linux_advanced_server.yml
  onecloud/roles/common/tasks/centos_7_x86_64.yml
  onecloud/roles/common/tasks/master.yml
  onecloud/roles/common/tasks/v3_8.yml
  onecloud/roles/mariadb/tasks/centos-x86_64.yml
  onecloud/roles/mariadb/tasks/kylin_linux_advanced_server-aarch64.yml
  onecloud/roles/mariadb/tasks/kylin_linux_advanced_server-x86_64.yml
  onecloud/roles/upgrade/common/tasks/v3_4-v3_6.yml
  onecloud/roles/upgrade/common/tasks/v3_6-v3_7.yml
  onecloud/roles/upgrade/common/tasks/v3_7-v3_8.yml
  onecloud/roles/upgrade/common/tasks/v3_8-v3_9.yml
  onecloud/roles/upgrade/common/tasks/v3_9-v3_10.yml
  onecloud/roles/upgrade/primary_master_node/tasks/main.yml
  onecloud/roles/utils/detect-os/tasks/main.yml
  onecloud/roles/utils/kernel-check/tasks/centos-aarch64.yml
  onecloud/roles/utils/kernel-check/tasks/centos-x86_64.yml
  run.py
Labels: size/M

#837 Automated cherry pick of #836: fix(repo): 对在线、离线安装，启用不同的repo
  onecloud/roles/clickhouse/install/tasks/centos.yml
  onecloud/roles/clickhouse/install/tasks/kylin_linux_advanced_server.yml
  onecloud/roles/common/tasks/centos_7_x86_64.yml
  onecloud/roles/common/tasks/master.yml
  onecloud/roles/common/tasks/v3_8.yml
  onecloud/roles/mariadb/tasks/centos-x86_64.yml
  onecloud/roles/mariadb/tasks/kylin_linux_advanced_server-aarch64.yml
  onecloud/roles/mariadb/tasks/kylin_linux_advanced_server-x86_64.yml
  onecloud/roles/upgrade/common/tasks/v3_4-v3_6.yml
  onecloud/roles/upgrade/common/tasks/v3_6-v3_7.yml
  onecloud/roles/upgrade/common/tasks/v3_7-v3_8.yml
  onecloud/roles/upgrade/common/tasks/v3_8-v3_9.yml
  onecloud/roles/upgrade/common/tasks/v3_9-v3_10.yml
  onecloud/roles/upgrade/primary_master_node/tasks/main.yml
  onecloud/roles/utils/detect-os/tasks/main.yml
  onecloud/roles/utils/kernel-check/tasks/centos-aarch64.yml
  onecloud/roles/utils/kernel-check/tasks/centos-x86_64.yml
  run.py
Labels: size/M

#838 Automated cherry pick of #836: fix(repo): 对在线、离线安装，启用不同的repo
  onecloud/roles/clickhouse/install/tasks/centos.yml
  onecloud/roles/clickhouse/install/tasks/kylin_linux_advanced_server.yml
  onecloud/roles/common/tasks/centos_7_x86_64.yml
  onecloud/roles/common/tasks/master.yml
  onecloud/roles/common/tasks/v3_8.yml
  onecloud/roles/mariadb/tasks/centos-x86_64.yml
  onecloud/roles/mariadb/tasks/kylin_linux_advanced_server-aarch64.yml
  onecloud/roles/mariadb/tasks/kylin_linux_advanced_server-x86_64.yml
  onecloud/roles/upgrade/common/tasks/v3_4-v3_6.yml
  onecloud/roles/upgrade/common/tasks/v3_6-v3_7.yml
  onecloud/roles/upgrade/common/tasks/v3_7-v3_8.yml
  onecloud/roles/upgrade/common/tasks/v3_8-v3_9.yml
  onecloud/roles/upgrade/common/tasks/v3_9-v3_10.yml
  onecloud/roles/upgrade/primary_master_node/tasks/main.yml
  onecloud/roles/utils/detect-os/tasks/main.yml
  onecloud/roles/utils/kernel-check/tasks/centos-aarch64.yml
  onecloud/roles/utils/kernel-check/tasks/centos-x86_64.yml
  run.py
Labels: size/M

#839 fix(repo): 优化redhat家族os在线/离线安装时的repo判断问题
  onecloud/roles/clickhouse/install/tasks/centos.yml
  onecloud/roles/clickhouse/install/tasks/kylin_linux_advanced_server.yml
  onecloud/roles/common/tasks/centos_7_x86_64.yml
  onecloud/roles/common/tasks/master.yml
  onecloud/roles/common/tasks/v3_8.yml
  onecloud/roles/mariadb/tasks/centos-x86_64.yml
  onecloud/roles/mariadb/tasks/kylin_linux_advanced_server-aarch64.yml
  onecloud/roles/mariadb/tasks/kylin_linux_advanced_server-x86_64.yml
  onecloud/roles/registry/tasks/main.yml
  onecloud/roles/upgrade/common/tasks/v3_4-v3_6.yml
  onecloud/roles/upgrade/common/tasks/v3_6-v3_7.yml
  onecloud/roles/upgrade/common/tasks/v3_7-v3_8.yml
  onecloud/roles/upgrade/common/tasks/v3_8-v3_9.yml
  onecloud/roles/upgrade/common/tasks/v3_9-v3_10.yml
  onecloud/roles/upgrade/primary_master_node/tasks/main.yml
  onecloud/roles/utils/detect-os/tasks/main.yml
  onecloud/roles/utils/kernel-check/tasks/centos-aarch64.yml
  onecloud/roles/utils/kernel-check/tasks/centos-x86_64.yml
  run.py
Labels: size/M

#840 Automated cherry pick of #839: fix(repo): 优化redhat家族os在线/离线安装时的repo判断问题
  onecloud/roles/clickhouse/install/tasks/centos.yml
  onecloud/roles/clickhouse/install/tasks/kylin_linux_advanced_server.yml
  onecloud/roles/common/tasks/centos_7_x86_64.yml
  onecloud/roles/common/tasks/master.yml
  onecloud/roles/common/tasks/v3_8.yml
  onecloud/roles/mariadb/tasks/centos-x86_64.yml
  onecloud/roles/mariadb/tasks/kylin_linux_advanced_server-aarch64.yml
  onecloud/roles/mariadb/tasks/kylin_linux_advanced_server-x86_64.yml
  onecloud/roles/registry/tasks/main.yml
  onecloud/roles/upgrade/common/tasks/v3_4-v3_6.yml
  onecloud/roles/upgrade/common/tasks/v3_6-v3_7.yml
  onecloud/roles/upgrade/common/tasks/v3_7-v3_8.yml
  onecloud/roles/upgrade/common/tasks/v3_8-v3_9.yml
  onecloud/roles/upgrade/common/tasks/v3_9-v3_10.yml
  onecloud/roles/upgrade/primary_master_node/tasks/main.yml
  onecloud/roles/utils/detect-os/tasks/main.yml
  onecloud/roles/utils/kernel-check/tasks/centos-aarch64.yml
  onecloud/roles/utils/kernel-check/tasks/centos-x86_64.yml
  run.py
Labels: size/M

#841 Automated cherry pick of #839: fix(repo): 优化redhat家族os在线/离线安装时的repo判断问题
  onecloud/roles/clickhouse/install/tasks/centos.yml
  onecloud/roles/clickhouse/install/tasks/kylin_linux_advanced_server.yml
  onecloud/roles/common/tasks/centos_7_x86_64.yml
  onecloud/roles/common/tasks/master.yml
  onecloud/roles/common/tasks/v3_8.yml
  onecloud/roles/mariadb/tasks/centos-x86_64.yml
  onecloud/roles/mariadb/tasks/kylin_linux_advanced_server-aarch64.yml
  onecloud/roles/mariadb/tasks/kylin_linux_advanced_server-x86_64.yml
  onecloud/roles/registry/tasks/main.yml
  onecloud/roles/upgrade/common/tasks/v3_4-v3_6.yml
  onecloud/roles/upgrade/common/tasks/v3_6-v3_7.yml
  onecloud/roles/upgrade/common/tasks/v3_7-v3_8.yml
  onecloud/roles/upgrade/common/tasks/v3_8-v3_9.yml
  onecloud/roles/upgrade/common/tasks/v3_9-v3_10.yml
  onecloud/roles/upgrade/primary_master_node/tasks/main.yml
  onecloud/roles/utils/detect-os/tasks/main.yml
  onecloud/roles/utils/kernel-check/tasks/centos-aarch64.yml
  onecloud/roles/utils/kernel-check/tasks/centos-x86_64.yml
  run.py
Labels: size/M

#842 严格界定所支持的os（centos/kylin/debian/uos/euler）及其版本范围
  onecloud/roles/utils/misc-check/tasks/main.yml
  onecloud/roles/utils/misc-check/tasks/os.yml
Labels: size/M

#843 Automated cherry pick of #842: 严格界定所支持的os（centos/kylin/debian/uos/euler）及其版本范围
  onecloud/roles/utils/misc-check/tasks/main.yml
  onecloud/roles/utils/misc-check/tasks/os.yml
Labels: size/M

#844 Automated cherry pick of #842: fix(centos): 严格界定所支持的os（centos/kylin/debian/uos/euler）及其版本范围
  onecloud/roles/utils/misc-check/tasks/main.yml
  onecloud/roles/utils/misc-check/tasks/os.yml
Labels: size/M

#845 fix(os): 解决语法兼容问题bool
  onecloud/roles/utils/misc-check/tasks/os.yml
Labels: size/XS

#846 Automated cherry pick of #845: fix(os): 解决语法兼容问题bool
  onecloud/roles/utils/misc-check/tasks/os.yml
Labels: size/XS

#847 Automated cherry pick of #845: fix(os): 解决语法兼容问题bool
  onecloud/roles/utils/misc-check/tasks/os.yml
Labels: size/XS

#848 minor update version for 3.9 to v3.9.12
  VERSION
Labels: size/XS

#849 fix(mariadb,kylin): mariadb init issue
  onecloud/roles/mariadb/tasks/main.yml
Labels: size/XS

#850 Automated cherry pick of #849: fix(mariadb,kylin): mariadb init issue
  onecloud/roles/mariadb/tasks/main.yml
Labels: size/XS

#851 fix for master iso deploy
  lib/utils.py
  onecloud/roles/common/tasks/master_offline.yml
  onecloud/roles/common/tasks/master_online.yml
Labels: size/M

#852 fix(typo): 变量名typo修复
  README.md
Labels: size/XS

#853 Automated cherry pick of #852: fix(typo): 变量名typo修复
  README.md
Labels: size/XS

#856 fix: grub update support openeuler
  onecloud/roles/utils/gpu-init/files/gpu_setup.sh
  onecloud/roles/utils/kernel-check/files/hugetlb_setup.sh
Labels: size/S

#857 Automated cherry pick of #856: fix: grub update support openeuler
  onecloud/roles/utils/gpu-init/files/gpu_setup.sh
  onecloud/roles/utils/kernel-check/files/hugetlb_setup.sh
Labels: size/S

#859 add support for uos 1050 u2a kongzi
  onecloud/roles/common/tasks/main.yml
  onecloud/roles/common/tasks/uniontech-kongzi.yml
  onecloud/roles/mariadb/tasks/main.yml
  onecloud/roles/mariadb/tasks/uniontech-kongzi.yml
  onecloud/roles/utils/detect-os/vars/uniontech-kongzi.yml
  onecloud/roles/utils/misc-check/tasks/os.yml
Labels: size/L

#860 Automated cherry pick of #859: add support for uos 1050 u2a
  onecloud/roles/common/tasks/main.yml
  onecloud/roles/common/tasks/uniontech-kongzi.yml
  onecloud/roles/mariadb/tasks/main.yml
  onecloud/roles/mariadb/tasks/uniontech-kongzi.yml
  onecloud/roles/utils/detect-os/vars/uniontech-kongzi.yml
  onecloud/roles/utils/misc-check/tasks/os.yml
Labels: size/L

#861 fix(mariadb): centos mariadb issue
  onecloud/roles/common/tasks/centos_7_x86_64.yml
  onecloud/roles/mariadb/tasks/centos-aarch64.yml
  onecloud/roles/mariadb/tasks/centos.yml
  onecloud/roles/mariadb/tasks/main.yml
  onecloud/roles/utils/detect-os/tasks/main.yml
Labels: size/M

#862 Automated cherry pick of #861: centos mariadb issue
  onecloud/roles/common/tasks/centos_7_x86_64.yml
  onecloud/roles/mariadb/tasks/centos-aarch64.yml
  onecloud/roles/mariadb/tasks/centos.yml
  onecloud/roles/mariadb/tasks/main.yml
  onecloud/roles/utils/detect-os/tasks/main.yml
Labels: size/M

#865 feat(mariadb): refactor os specific mariadb tasks into vars
  onecloud/roles/common/tasks/debian.yml
  onecloud/roles/mariadb/tasks/centos.yml
  onecloud/roles/mariadb/tasks/debian-aarch64.yml
  onecloud/roles/mariadb/tasks/debian-x86_64.yml
  onecloud/roles/mariadb/tasks/kylin_linux_advanced_server-aarch64.yml
  onecloud/roles/mariadb/tasks/kylin_linux_advanced_server-x86_64.yml
  onecloud/roles/mariadb/tasks/main.yml
  onecloud/roles/mariadb/tasks/openeuler-aarch64.yml
  onecloud/roles/mariadb/tasks/openeuler-x86_64.yml
  onecloud/roles/mariadb/tasks/uniontech-kongzi.yml
  onecloud/roles/mariadb/vars/centos.yml
  onecloud/roles/mariadb/vars/debian.yml
  onecloud/roles/mariadb/vars/kylin_linux_advanced_server.yml
  onecloud/roles/mariadb/vars/openeuler.yml
  onecloud/roles/mariadb/vars/uniontech-kongzi.yml
  onecloud/roles/utils/detect-os/tasks/main.yml
  onecloud/roles/utils/misc-check/tasks/main.yml
Labels: size/L

#866 Automated cherry pick of #865: centos mariadb issue
  onecloud/roles/common/tasks/debian.yml
  onecloud/roles/mariadb/tasks/centos.yml
  onecloud/roles/mariadb/tasks/debian-aarch64.yml
  onecloud/roles/mariadb/tasks/debian-x86_64.yml
  onecloud/roles/mariadb/tasks/kylin_linux_advanced_server-aarch64.yml
  onecloud/roles/mariadb/tasks/kylin_linux_advanced_server-x86_64.yml
  onecloud/roles/mariadb/tasks/main.yml
  onecloud/roles/mariadb/tasks/uniontech-kongzi.yml
  onecloud/roles/mariadb/vars/centos.yml
  onecloud/roles/mariadb/vars/debian.yml
  onecloud/roles/mariadb/vars/kylin_linux_advanced_server.yml
  onecloud/roles/mariadb/vars/openeuler.yml
  onecloud/roles/mariadb/vars/uniontech-kongzi.yml
  onecloud/roles/utils/detect-os/tasks/main.yml
  onecloud/roles/utils/misc-check/tasks/main.yml
Labels: size/L

#867 Automated cherry pick of #865: centos mariadb issue
  onecloud/roles/mariadb/tasks/centos.yml
  onecloud/roles/mariadb/tasks/debian-aarch64.yml
  onecloud/roles/mariadb/tasks/debian-x86_64.yml
  onecloud/roles/mariadb/tasks/kylin_linux_advanced_server-aarch64.yml
  onecloud/roles/mariadb/tasks/kylin_linux_advanced_server-x86_64.yml
  onecloud/roles/mariadb/tasks/main.yml
  onecloud/roles/mariadb/vars/centos.yml
  onecloud/roles/mariadb/vars/debian.yml
  onecloud/roles/mariadb/vars/kylin_linux_advanced_server.yml
  onecloud/roles/mariadb/vars/openeuler.yml
  onecloud/roles/mariadb/vars/uniontech-kongzi.yml
  onecloud/roles/utils/detect-os/tasks/main.yml
  onecloud/roles/utils/misc-check/tasks/main.yml
Labels: size/L

#868 hotfix var def issue
  onecloud/roles/utils/misc-check/tasks/main.yml
Labels: size/XS

#869 Automated cherry pick of #868: hotfix var def issue
  onecloud/roles/utils/misc-check/tasks/main.yml
Labels: size/XS

#871 fix(docker-compose): source rcadmin before climc starts
  compose/docker-compose.yml
  lib/compose/object.py
  lib/compose/services/climc.py
Labels: size/S

#872 Automated cherry pick of #871: fix(docker-compose): source rcadmin before climc starts
  compose/docker-compose.yml
  lib/compose/object.py
  lib/compose/services/climc.py
Labels: size/S

#873 fix(docker-compose): source rcadmin before climc starts
  compose/docker-compose.yml
  lib/compose/manifest/__init__.py
  lib/compose/services/climc.py
Labels: size/S

#875 Automated cherry pick of #873: fix(docker-compose): source rcadmin before climc starts
  compose/docker-compose.yml
  lib/compose/manifest/__init__.py
  lib/compose/services/climc.py
Labels: size/S
