Repository yunionio/ocboot, pull requests merged in 2023-01, with the labels that each got.

#633 feat(kernel,arm64): 升级centos arm 内核到5.4.199版本
  onecloud/roles/utils/kernel-check/tasks/centos-aarch64.yml
Labels: size/XS

#634 Automated cherry pick of #633: feat(kernel,arm64): 升级centos arm 内核到5.4.199版本
  onecloud/roles/utils/kernel-check/tasks/centos-aarch64.yml
Labels: size/XS

#635 Automated cherry pick of #633: feat(kernel,arm64): 升级centos arm 内核到5.4.199版本
  onecloud/roles/utils/kernel-check/tasks/centos-aarch64.yml
Labels: size/XS

#636 fix(chart): update operator tag
  charts/cloudpods/Chart.yaml
  charts/cloudpods/values-dev.yaml
  charts/cloudpods/values-prod.yaml
  charts/cloudpods/values.yaml
Labels: size/S

#637 Automated cherry pick of #636: fix(chart): update operator tag
  charts/cloudpods/Chart.yaml
  charts/cloudpods/values-dev.yaml
  charts/cloudpods/values-prod.yaml
  charts/cloudpods/values.yaml
Labels: size/S

#638 Automated cherry pick of #636: fix(chart): update operator tag
  charts/cloudpods/Chart.yaml
  charts/cloudpods/values-dev.yaml
  charts/cloudpods/values-prod.yaml
  charts/cloudpods/values.yaml
Labels: size/S

#639 fix(kubelet): add systemd cgroups args
  onecloud/roles/utils/k8s/kubelet/extra-args/files/etc_sysconfig_kubelet
Labels: size/XS

#641 Automated cherry pick of #639: fix(kubelet): add systemd cgroups args
  onecloud/roles/utils/k8s/kubelet/extra-args/files/etc_sysconfig_kubelet
Labels: size/XS

#640 Automated cherry pick of #639: fix(kubelet): add systemd cgroups args
  onecloud/roles/utils/k8s/kubelet/extra-args/files/etc_sysconfig_kubelet
Labels: size/XS

#642 fix(backup): 备份：更新备份文件名、readme，增加精简备份模式
  README.md
  lib/backup.py
  lib/db.py
  lib/restore.py
Labels: size/M

#643 Automated cherry pick of #642: fix(backup): 备份：更新备份文件名、readme，增加精简备份模式
  README.md
  lib/backup.py
  lib/db.py
  lib/restore.py
Labels: size/M

#644 Automated cherry pick of #642: fix(backup): 备份：更新备份文件名、readme，增加精简备份模式
  README.md
  lib/backup.py
  lib/db.py
  lib/restore.py
Labels: size/M

#646 fix(backup): 备份前确保备份路径存在
  lib/db.py
Labels: size/XS

#647 Automated cherry pick of #646: fix(backup): 备份前确保备份路径存在
  lib/db.py
Labels: size/XS

#648 Automated cherry pick of #646: fix(backup): 备份前确保备份路径存在
  lib/db.py
Labels: size/XS

#649 Automated cherry pick of #646: fix(backup): 备份前确保备份路径存在
  lib/db.py
Labels: size/XS

#651 fix: hugetlb script add executable perm
  onecloud/roles/utils/kernel-check/tasks/main.yml
Labels: size/XS

#650 feat(iso,deploy): 增加使用大镜像选项useHyperImage
  onecloud/roles/primary-master-node/setup_cloud/tasks/main.yml
Labels: size/S

#653 Automated cherry pick of #650: feat(iso,deploy): 增加使用大镜像选项useHyperImage
  onecloud/roles/primary-master-node/setup_cloud/tasks/main.yml
Labels: size/S

#654 Automated cherry pick of #650: feat(iso,deploy): 增加使用大镜像选项useHyperImage
  onecloud/roles/primary-master-node/setup_cloud/tasks/main.yml
Labels: size/S

#655 fix(deploy,images): 部署阶段拉取镜像重试机制
  onecloud/roles/primary-master-node/setup_k8s/tasks/main.yml
Labels: size/XS

#656 Automated cherry pick of #655: fix(deploy,images): 部署阶段拉取镜像重试机制
  onecloud/roles/primary-master-node/setup_k8s/tasks/main.yml
Labels: size/XS

#657 Automated cherry pick of #655: fix(deploy,images): 部署阶段拉取镜像重试机制
  onecloud/roles/primary-master-node/setup_k8s/tasks/main.yml
Labels: size/XS

#658 Automated cherry pick of #655: fix(deploy,images): 部署阶段拉取镜像重试机制
  onecloud/roles/primary-master-node/setup_k8s/tasks/main.yml
Labels: size/XS
