Repository yunionio/ocboot, pull requests merged in 2023-11, with the labels that each got.

#1009 fix(deploy,stack): stack选项相关改进
  lib/cmd.py
  lib/ocboot.py
  lib/utils.py
  run.py
Labels: size/L

#1011 Automated cherry pick of #1009: fix(deploy,stack): stack选项相关改进
  lib/cmd.py
  lib/ocboot.py
  lib/utils.py
  run.py
Labels: size/L

#1012 Automated cherry pick of #1009: fix(deploy,stack): stack选项相关改进
  lib/cmd.py
  lib/ocboot.py
  lib/utils.py
  run.py
Labels: size/L

#1013 fix(ssh): 解决自动配置sshkey不生效的问题
  run.py
Labels: size/XS

#1014 Automated cherry pick of #1013: fix(ssh): 解决自动配置sshkey不生效的问题
  run.py
Labels: size/XS

#1015 Automated cherry pick of #1013: fix(ssh): 解决自动配置sshkey不生效的问题
  run.py
Labels: size/XS

#1016 fix: add lbagent failed on ubuntu system
  onecloud/roles/worker-node/lbagent/tasks/main.yml
Labels: size/XS

#1017 Automated cherry pick of #1016: fix: add lbagent failed on ubuntu system
  onecloud/roles/worker-node/lbagent/tasks/main.yml
Labels: size/XS

#1018 Automated cherry pick of #1016: fix: add lbagent failed on ubuntu system
  onecloud/roles/worker-node/lbagent/tasks/main.yml
Labels: size/XS

#1019 fix(comp): minor: 容错处理
  onecloud/roles/common/tasks/main.yml
  onecloud/roles/pre-install-common/tasks/main.yml
Labels: size/XS

#1020 Automated cherry pick of #1019: fix(comp): minor: 容错处理
  onecloud/roles/common/tasks/main.yml
  onecloud/roles/pre-install-common/tasks/main.yml
Labels: size/XS

#1021 Automated cherry pick of #1019: fix(comp): minor: 容错处理
  onecloud/roles/common/tasks/main.yml
  onecloud/roles/pre-install-common/tasks/main.yml
Labels: size/XS

#1022 Automated cherry pick of #1019: fix(comp): minor: 容错处理
  onecloud/roles/common/tasks/main.yml
  onecloud/roles/pre-install-common/tasks/main.yml
Labels: size/XS

#1027 feat: make ip_conf optional when start run.py
  run.py
Labels: size/S

#1028 Automated cherry pick of #1027: feat: make ip_conf optional when start run.py
  run.py
Labels: size/S

#1029 Automated cherry pick of #1027: feat: make ip_conf optional when start run.py
  run.py
Labels: size/S

#1030 fix(compose): add cloudid service
  compose/docker-compose.yml
  lib/compose/manifest/__init__.py
  lib/compose/services/__init__.py
  lib/compose/services/cluster_service.py
Labels: size/L

#1031 Automated cherry pick of #1030: fix(compose): add cloudid service
  compose/docker-compose.yml
  lib/compose/manifest/__init__.py
  lib/compose/services/__init__.py
  lib/compose/services/cluster_service.py
Labels: size/L

#1023 fix(comp): minor: 容错处理02
  onecloud/roles/utils/enable-eip/tasks/main.yml
Labels: size/XS

#1024 Automated cherry pick of #1023: fix(comp): minor: 容错处理02
  onecloud/roles/utils/enable-eip/tasks/main.yml
Labels: size/XS

#1025 Automated cherry pick of #1023: fix(comp): minor: 容错处理02
  onecloud/roles/utils/enable-eip/tasks/main.yml
Labels: size/XS

#1026 Automated cherry pick of #1023: fix(comp): minor: 容错处理02
  onecloud/roles/utils/enable-eip/tasks/main.yml
Labels: size/XS

#1033 参数解析hotfix
  run.py
Labels: size/XS

#1034 Automated cherry pick of #1033: 参数解析hotfix
  run.py
Labels: size/XS

#1035 Automated cherry pick of #1033: 参数解析hotfix
  run.py
Labels: size/XS

#1036 fix(version): update version from 3.10.6 to 3.10.7
  VERSION
  charts/cloudpods/values-dev.yaml
  charts/cloudpods/values-prod.yaml
  charts/cloudpods/values.yaml
  compose/docker-compose.yml
  generate-compose.py
  run-in-docker.sh
Labels: size/M

#1037 Automated cherry pick of #1036: fix(version): update version from 3.10.6 to 3.10.7
  VERSION
  charts/cloudpods/values-dev.yaml
  charts/cloudpods/values-prod.yaml
  charts/cloudpods/values.yaml
  compose/docker-compose.yml
  generate-compose.py
  run-in-docker.sh
Labels: size/M

#1038 Automated cherry pick of #1036: fix(version): update version from 3.10.6 to 3.10.7
  VERSION
  charts/cloudpods/values-dev.yaml
  charts/cloudpods/values-prod.yaml
  charts/cloudpods/values.yaml
  compose/docker-compose.yml
  generate-compose.py
  run-in-docker.sh
Labels: size/M

#1039 feat(os): comp for openeuler and uos fou
  onecloud/roles/common/tasks/uniontech_os_server_20-fou.yml
  onecloud/roles/mariadb/tasks/main.yml
  onecloud/roles/mariadb/tasks/uniontech_os_server_20-fou.yml
  onecloud/roles/mariadb/vars/ubuntu.yml
  onecloud/roles/mariadb/vars/uniontech_os_server_20-fou.yml
  onecloud/roles/utils/config-network-manager/handlers/main.yml
  onecloud/roles/utils/detect-os/vars/openeuler-aarch64.yml
  onecloud/roles/utils/detect-os/vars/openeuler-x86_64.yml
  onecloud/roles/utils/detect-os/vars/uniontech os server 20 " -aarch64.yml
  onecloud/roles/utils/detect-os/vars/uniontech_os_server_20-fou.yml
  onecloud/roles/utils/detect-os/vars/uniontech_os_server_20_"_-x86_64.yml
Labels: size/L

#1040 Automated cherry pick of #1039: feat(os): comp for openeuler and uos fou
  onecloud/roles/common/tasks/uniontech_os_server_20-fou.yml
  onecloud/roles/mariadb/tasks/main.yml
  onecloud/roles/mariadb/tasks/uniontech_os_server_20-fou.yml
  onecloud/roles/mariadb/vars/ubuntu.yml
  onecloud/roles/mariadb/vars/uniontech_os_server_20-fou.yml
  onecloud/roles/utils/config-network-manager/handlers/main.yml
  onecloud/roles/utils/detect-os/vars/openeuler-aarch64.yml
  onecloud/roles/utils/detect-os/vars/openeuler-x86_64.yml
  onecloud/roles/utils/detect-os/vars/uniontech os server 20 " -aarch64.yml
  onecloud/roles/utils/detect-os/vars/uniontech_os_server_20-fou.yml
  onecloud/roles/utils/detect-os/vars/uniontech_os_server_20_"_-x86_64.yml
Labels: size/L

#1041 Automated cherry pick of #1039: feat(os): comp for openeuler and uos fou
  onecloud/roles/common/tasks/uniontech_os_server_20-fou.yml
  onecloud/roles/mariadb/tasks/main.yml
  onecloud/roles/mariadb/tasks/uniontech_os_server_20-fou.yml
  onecloud/roles/mariadb/vars/ubuntu.yml
  onecloud/roles/mariadb/vars/uniontech_os_server_20-fou.yml
  onecloud/roles/utils/config-network-manager/handlers/main.yml
  onecloud/roles/utils/detect-os/vars/kylin_linux_advanced_server-v10.x86_64.yml
  onecloud/roles/utils/detect-os/vars/openeuler-x86_64.yml
  onecloud/roles/utils/detect-os/vars/uniontech os server 20 " -aarch64.yml
  onecloud/roles/utils/detect-os/vars/uniontech_os_server_20-fou.yml
  onecloud/roles/utils/detect-os/vars/uniontech_os_server_20_"_-x86_64.yml
Labels: size/L

#1042 fix(conf): 通过iso安装时，tui界面未勾选enable host agent 选项，部署完成后不应该启用 host agent
  run.py
Labels: size/XS

#1043 Automated cherry pick of #1042: fix(conf): 通过iso安装时，tui界面未勾选enable host agent 选项，部署完成后不应该启用 host agent
  run.py
Labels: size/XS

#1044 Automated cherry pick of #1042: fix(conf): 通过iso安装时，tui界面未勾选enable host agent 选项，部署完成后不应该启用 host agent
  run.py
Labels: size/XS

#1045 fix(host,iso): iso 新增计算节点hotfix
  run.py
Labels: size/XS

#1047 Automated cherry pick of #1045: fix(host,iso): iso 新增计算节点hotfix
  run.py
Labels: size/XS

#1046 Automated cherry pick of #1045: fix(host,iso): iso 新增计算节点hotfix
  run.py
Labels: size/XS

#1048 fix: use shell environment directly when using kubectl patches resource
  onecloud/roles/utils/k8s/addons/patch/tasks/main.yml
Labels: size/XS
