Repository yunionio/ocboot, pull requests merged in 2023-05, with the labels that each got.

#775 Update README.md
  README.md
Labels: size/L

#778 update docker-compose to v3.10.1
  compose/docker-compose.yml
Labels: size/M

#780 feat(helm): upgrade to v3.10.1
  charts/cloudpods/Chart.yaml
  charts/cloudpods/values-dev.yaml
  charts/cloudpods/values-prod.yaml
  charts/cloudpods/values.yaml
Labels: size/S

#781 Automated cherry pick of #780: feat(helm): upgrade to v3.10.1
  charts/cloudpods/Chart.yaml
  charts/cloudpods/values-dev.yaml
  charts/cloudpods/values-prod.yaml
  charts/cloudpods/values.yaml
Labels: size/S

#782 fix(run-in-docker): update version to v3.10.1
  run-in-docker.sh
Labels: size/XS

#784 remove duplicated content
  README.md
Labels: size/L

#774 fix(euler,clickhouse): x86 欧拉 ISO 启用clickhouse 模块
  onecloud/roles/clickhouse/deploy/tasks/main.yml
  onecloud/roles/clickhouse/install/tasks/main.yml
  onecloud/roles/clickhouse/install/tasks/openeuler.yml
  onecloud/roles/common/tasks/centos_7_x86_64.yml
  onecloud/roles/primary-master-node/setup_k8s/tasks/main.yml
Labels: size/M

#788 fix(compose): 更新compose 版本号
  compose/docker-compose.yml
  lib/compose/services/kubeserver.py
Labels: size/XS

#789 Automated cherry pick of #788: fix(compose): 更新compose 版本号
  compose/docker-compose.yml
  lib/compose/services/kubeserver.py
Labels: size/XS

#790 fix(version): 更新版本号到3.9.10
  VERSION
Labels: size/XS

#791 Feature/rex disable telegraf
  onecloud/roles/utils/detect-os/tasks/main.yml
  onecloud/roles/utils/disable-telegraf-service/tasks/main.yml
  onecloud/roles/worker-node/lbagent/tasks/main.yml
Labels: size/S

#792 Automated cherry pick of #791: feat(host,lbagent): 部署lbagent或者host时禁用telegraf并且禁止重新启动
  onecloud/roles/utils/detect-os/tasks/main.yml
  onecloud/roles/utils/disable-telegraf-service/tasks/main.yml
  onecloud/roles/worker-node/lbagent/tasks/main.yml
Labels: size/S

#793 Feature/rex add step for update record
  onecloud/roles/upgrade/primary_master_node/tasks/main.yml
Labels: size/S

#794 Automated cherry pick of #793: feat(upgrade): ocboot新增升级记录
  onecloud/roles/upgrade/primary_master_node/tasks/main.yml
Labels: size/S

#795 feat(deploy,debian,arm/x86): 增加对debian 11 的部署支持
  onecloud/roles/common/tasks/debian.yml
  onecloud/roles/common/tasks/debian_10_aarch64.yml
  onecloud/roles/common/tasks/main.yml
  onecloud/roles/common/tasks/v3_7.yml
  onecloud/roles/utils/config-network-manager/handlers/main.yml
  onecloud/roles/utils/config-network-manager/tasks/main.yml
  onecloud/roles/utils/detect-os/vars/debian-10.x86_64.yml
  onecloud/roles/utils/detect-os/vars/debian.yml
Labels: size/L

#796 Automated cherry pick of #795: feat(deploy,debian,arm/x86): 增加对debian 11 的部署支持
  onecloud/roles/common/tasks/debian.yml
  onecloud/roles/common/tasks/debian_10_aarch64.yml
  onecloud/roles/common/tasks/main.yml
  onecloud/roles/common/tasks/v3_7.yml
  onecloud/roles/utils/config-network-manager/handlers/main.yml
  onecloud/roles/utils/config-network-manager/tasks/main.yml
  onecloud/roles/utils/detect-os/vars/debian-10.x86_64.yml
  onecloud/roles/utils/detect-os/vars/debian.yml
Labels: size/L

#797 fix(deploy,networkmanager): 在部署networkmanger阶段容错
  onecloud/roles/utils/config-network-manager/tasks/main.yml
Labels: size/XS
