Repository yunionio/ocboot, pull requests merged in 2023-04, with the labels that each got.

#733 解决3.9升级问题 py 库依赖
  lib/ocboot.py
  lib/parser.py
Labels: size/M

#736 修复3.9升级问题
  lib/service.py
Labels: size/L

#734 fix: hugepage setup strategy
  README.md
  lib/ocboot.py
  onecloud/roles/utils/kernel-check/files/oc-hugetlb-reserve-pages.sh
Labels: size/S

#735 Automated cherry pick of #734: fix: hugepage setup strategy
  README.md
  lib/ocboot.py
  onecloud/roles/utils/kernel-check/files/oc-hugetlb-reserve-pages.sh
Labels: size/S

#737 feat(db,backup): 自动备份数据库、k8s oc, deployment, ETCD.
  lib/auto_backup.py
  lib/backup.py
  lib/parser.py
  lib/service.py
  ocboot.py
  onecloud/auto-backup-services.yml
  onecloud/roles/utils/auto-backup-services/files/db_backup.sh
  onecloud/roles/utils/auto-backup-services/tasks/main.yml
  onecloud/roles/utils/cronjobs/tasks/main.yml
Labels: size/L

#738 Automated cherry pick of #737: feat(db,backup): 自动备份数据库
  lib/auto_backup.py
  lib/backup.py
  lib/parser.py
  lib/service.py
  ocboot.py
  onecloud/auto-backup-services.yml
  onecloud/roles/utils/auto-backup-services/files/db_backup.sh
  onecloud/roles/utils/auto-backup-services/tasks/main.yml
  onecloud/roles/utils/cronjobs/tasks/main.yml
Labels: size/L

#739 Automated cherry pick of #737: feat(db,backup): 自动备份数据库
  lib/auto_backup.py
  lib/backup.py
  lib/ocboot.py
  lib/parser.py
  lib/service.py
  ocboot.py
  onecloud/auto-backup-services.yml
  onecloud/roles/utils/auto-backup-services/files/db_backup.sh
  onecloud/roles/utils/auto-backup-services/tasks/main.yml
  onecloud/roles/utils/cronjobs/tasks/main.yml
Labels: size/L

#740 fix(autobackup): 自动备份，参数修正
  lib/parser.py
Labels: size/XS

#741 Automated cherry pick of #740: 自动备份，参数修正
  lib/parser.py
Labels: size/XS

#742 Automated cherry pick of #740: 自动备份，参数修正
  lib/parser.py
Labels: size/XS

#743 fix(clickhouse,meter): 解决clickhouse的meter部署问题
  onecloud/roles/clickhouse/deploy/tasks/main.yml
Labels: size/S

#744 Automated cherry pick of #743: fix(clickhouse,meter): 解决clickhouse的meter部署问题
  onecloud/roles/clickhouse/deploy/tasks/main.yml
Labels: size/S

#745 Automated cherry pick of #743: fix(clickhouse,meter): 解决clickhouse的meter部署问题
  onecloud/roles/clickhouse/deploy/tasks/main.yml
Labels: size/S

#746 fix(clickhouse): 检测所有相关服务的clickhouse配置
  onecloud/roles/clickhouse/deploy/tasks/main.yml
Labels: size/S

#748 Automated cherry pick of #746: fix(clickhouse): 检测所有相关服务的clickhouse配置
  onecloud/roles/clickhouse/deploy/tasks/main.yml
Labels: size/S

#749 fix(backup): enable auto backup for ee users
  onecloud/roles/utils/auto-backup-services/tasks/main.yml
  onecloud/roles/utils/cronjobs/tasks/main.yml
Labels: size/S

#750 Automated cherry pick of #749: fix(backup): enable auto backup for ee users
  onecloud/roles/utils/auto-backup-services/tasks/main.yml
  onecloud/roles/utils/cronjobs/tasks/main.yml
Labels: size/S

#751 Automated cherry pick of #749: fix(backup): enable auto backup for ee users
  onecloud/roles/utils/auto-backup-services/tasks/main.yml
  onecloud/roles/utils/cronjobs/tasks/main.yml
Labels: size/S

#753 fix(upgrade): 升级时检验镜像状态并重试
  onecloud/roles/upgrade/primary_master_node/tasks/main.yml
Labels: size/XS

#754 Automated cherry pick of #753: fix(upgrade): 升级时检验镜像状态并重试
  onecloud/roles/upgrade/primary_master_node/tasks/main.yml
Labels: size/XS

#755 Automated cherry pick of #753: fix(upgrade): 升级时检验镜像状态并重试
  onecloud/roles/upgrade/primary_master_node/tasks/main.yml
Labels: size/XS

#756 fix(backup): 自动备份:删除某些配置行
  onecloud/roles/utils/auto-backup-services/files/db_backup.sh
  onecloud/roles/utils/auto-backup-services/tasks/main.yml
Labels: size/S

#758 Automated cherry pick of #756: fix(backup): 自动备份:删除某些配置行
  onecloud/roles/utils/auto-backup-services/files/db_backup.sh
  onecloud/roles/utils/auto-backup-services/tasks/main.yml
Labels: size/S

#757 Automated cherry pick of #756: fix(backup): 自动备份:删除某些配置行
  onecloud/roles/utils/auto-backup-services/files/db_backup.sh
  onecloud/roles/utils/auto-backup-services/tasks/main.yml
Labels: size/S

#759 fix(backup): 自动备份检测条件修正
  onecloud/roles/utils/cronjobs/tasks/main.yml
Labels: size/XS

#760 Automated cherry pick of #759: fix(backup): 自动备份检测条件修正
  onecloud/roles/utils/cronjobs/tasks/main.yml
Labels: size/XS

#761 Automated cherry pick of #759: fix(backup): 自动备份检测条件修正
  onecloud/roles/utils/cronjobs/tasks/main.yml
Labels: size/XS

#765 Automated cherry pick of #762: update version for 3.10.0
  VERSION
Labels: size/XS

#766 fix(kernel,reboot): 优化kernel检测与重启的逻辑
  onecloud/roles/utils/kernel-check/tasks/main.yml
Labels: size/XS

#767 Automated cherry pick of #766: fix(kernel,reboot): 优化kernel检测与重启的逻辑
  onecloud/roles/utils/kernel-check/tasks/main.yml
Labels: size/XS

#768 Automated cherry pick of #766: fix(kernel,reboot): 优化kernel检测与重启的逻辑
  onecloud/roles/utils/kernel-check/tasks/main.yml
Labels: size/XS

#769 feat: update compose file version to v3.10.0
  Makefile
  compose/docker-compose.yml
  generate-compose.py
Labels: size/M

#773 兼容欧拉2022 LTS Sp1
  onecloud/ansible.cfg
  onecloud/roles/common/tasks/centos_7_x86_64.yml
  onecloud/roles/common/tasks/main.yml
  onecloud/roles/common/tasks/openeuler_22_aarch64.yml
  onecloud/roles/common/tasks/openeuler_22_x86_64.yml
  onecloud/roles/common/tasks/v3_10_online.yml
  onecloud/roles/common/tasks/v3_9_online.yml
  onecloud/roles/mariadb/tasks/centos-x86_64.yml
  onecloud/roles/mariadb/tasks/debian-aarch64.yml
  onecloud/roles/mariadb/tasks/debian-x86_64.yml
  onecloud/roles/mariadb/tasks/kylin_linux_advanced_server-aarch64.yml
  onecloud/roles/mariadb/tasks/kylin_linux_advanced_server-x86_64.yml
  onecloud/roles/mariadb/tasks/main.yml
  onecloud/roles/mariadb/tasks/openeuler-aarch64.yml
  onecloud/roles/mariadb/tasks/openeuler-x86_64.yml
  onecloud/roles/primary-master-node/setup_k8s/tasks/main.yml
  onecloud/roles/utils/detect-os/vars/openeuler-aarch64.yml
  onecloud/roles/utils/detect-os/vars/openeuler-x86_64.yml
  onecloud/roles/utils/kernel-check/tasks/main.yml
  run.py
Labels: size/L
