Repository yunionio/ocboot, pull requests merged in 2024-07, with the labels that each got.

#1315 hotfix: k3s add lbagent allow 1c1g; refine add command
  onecloud/roles/utils/misc-check/tasks/main.yml
  onecloud/roles/worker-node/lbagent/tasks/main.yml
Labels: size/XS

#1317 fix: change apiserver args setting order
  onecloud/install-cluster.yml
  onecloud/roles/utils/k8s/apiserver/args/tasks/main.yml
  onecloud/roles/utils/k8s/kubelet/extra-args/tasks/main.yml
  onecloud/upgrade-cluster.yml
Labels: size/M, lgtm

#1318 Automated cherry pick of #1317: fix: change apiserver args setting order
  onecloud/install-cluster.yml
  onecloud/roles/utils/k8s/apiserver/args/tasks/main.yml
  onecloud/roles/utils/k8s/kubelet/extra-args/tasks/main.yml
  onecloud/upgrade-cluster.yml
Labels: size/M

#1319 Automated cherry pick of #1317: fix: change apiserver args setting order
  onecloud/install-cluster.yml
  onecloud/roles/utils/k8s/apiserver/args/tasks/main.yml
  onecloud/roles/utils/k8s/kubelet/extra-args/tasks/main.yml
  onecloud/upgrade-cluster.yml
Labels: size/M

#1320 Automated cherry pick of #1317: fix: change apiserver args setting order
  onecloud/install-cluster.yml
  onecloud/roles/utils/k8s/apiserver/args/tasks/main.yml
  onecloud/roles/utils/k8s/kubelet/extra-args/tasks/main.yml
  onecloud/upgrade-cluster.yml
Labels: size/M

#1321 feat(compose): update to v3.11.5
  VERSION
  compose/docker-compose.yml
  lib/compose/services/cluster_service.py
  lib/compose/services/host_deployer.py
Labels: size/L

#1322 Automated cherry pick of #1321: feat(compose): update to v3.11.5
  VERSION
  compose/docker-compose.yml
  lib/compose/services/cluster_service.py
  lib/compose/services/host_deployer.py
Labels: size/L

#1324 feat: update chart to v3.11.5
  charts/cloudpods/values-dev.yaml
  charts/cloudpods/values-prod.yaml
  charts/cloudpods/values.yaml
  generate-compose.py
Labels: size/S

#1325 Automated cherry pick of #1324: feat: update chart to v3.11.5
  charts/cloudpods/values-dev.yaml
  charts/cloudpods/values-prod.yaml
  charts/cloudpods/values.yaml
  generate-compose.py
Labels: size/S

#1326 Automated cherry pick of #1324: feat: update chart to v3.11.5
  charts/cloudpods/values-dev.yaml
  charts/cloudpods/values-prod.yaml
  charts/cloudpods/values.yaml
  generate-compose.py
Labels: size/S

#1327 add lbagent node allow tcp_mtu_probing
  onecloud/roles/utils/kernel-modules/files/yunion-ipvs-modules.sh
Labels: size/XS, lgtm

#1329 Automated cherry pick of #1327: add lbagent node allow tcp_mtu_probing
  onecloud/roles/utils/kernel-modules/files/yunion-ipvs-modules.sh
Labels: size/XS

#1330 Automated cherry pick of #1327: add lbagent node allow tcp_mtu_probing
  onecloud/roles/utils/kernel-modules/files/yunion-ipvs-modules.sh
Labels: size/XS

#1331 fix(ocboot): update operator image for k3s and use IMAGE_REPOSITORY env
  ocboot.sh
  onecloud/roles/primary-master-node/setup_cloud/templates/onecloud-manifests.yaml.j2
  scripts/install-buildah.sh
Labels: lgtm, size/S

#1333 fix: no reboot on controller node
  lib/install.py
  lib/ocboot.py
  onecloud/roles/common/tasks/utils/unified_cgroup_hierarchy.yml
  onecloud/roles/utils/gpu-init/files/gpu_setup.sh
  onecloud/roles/utils/kernel-check/files/hugetlb_setup.sh
  onecloud/roles/utils/kernel-check/tasks/main.yml
  onecloud/roles/utils/kernel-check/tasks/unified_cgroup_hierarchy.yml
Labels: size/M, lgtm

#1336 Automated cherry pick of #1333: fix: no reboot on controller node
  lib/install.py
  lib/ocboot.py
  onecloud/roles/common/tasks/utils/unified_cgroup_hierarchy.yml
  onecloud/roles/utils/gpu-init/files/gpu_setup.sh
  onecloud/roles/utils/kernel-check/files/hugetlb_setup.sh
  onecloud/roles/utils/kernel-check/tasks/main.yml
  onecloud/roles/utils/kernel-check/tasks/unified_cgroup_hierarchy.yml
Labels: size/M

#1335 Automated cherry pick of #1333: fix: no reboot on controller node
  lib/install.py
  lib/ocboot.py
  onecloud/roles/common/tasks/utils/unified_cgroup_hierarchy.yml
  onecloud/roles/utils/gpu-init/files/gpu_setup.sh
  onecloud/roles/utils/kernel-check/files/hugetlb_setup.sh
  onecloud/roles/utils/kernel-check/tasks/main.yml
  onecloud/roles/utils/kernel-check/tasks/unified_cgroup_hierarchy.yml
Labels: size/M

#1334 Automated cherry pick of #1333: fix: no reboot on controller node
  lib/install.py
  lib/ocboot.py
  onecloud/roles/common/tasks/utils/unified_cgroup_hierarchy.yml
  onecloud/roles/utils/gpu-init/files/gpu_setup.sh
  onecloud/roles/utils/kernel-check/files/hugetlb_setup.sh
  onecloud/roles/utils/kernel-check/tasks/main.yml
  onecloud/roles/utils/kernel-check/tasks/unified_cgroup_hierarchy.yml
Labels: size/M
