Repository yunionio/ocboot, pull requests merged in 2024-12, with the labels that each got.

#1389 fix: offline ha setup fixes
  onecloud/roles/clickhouse/deploy/tasks/main.yml
  onecloud/roles/clickhouse/install/files/system_logs.xml
  onecloud/roles/clickhouse/install/tasks/main.yml
  onecloud/roles/primary-master-node/setup_k8s/tasks/main.yml
  onecloud/roles/registry/templates/registry.yml
  onecloud/roles/utils/load-images/tasks/main.yml
Labels: size/L

#1391 Automated cherry pick of #1389: fix: offline ha setup fixes
  onecloud/roles/clickhouse/deploy/tasks/main.yml
  onecloud/roles/clickhouse/install/files/system_logs.xml
  onecloud/roles/clickhouse/install/tasks/main.yml
  onecloud/roles/primary-master-node/setup_k8s/tasks/main.yml
  onecloud/roles/registry/templates/registry.yml
  onecloud/roles/utils/load-images/tasks/main.yml
Labels: size/L

#1390 Automated cherry pick of #1389: fix: offline ha setup fixes
  onecloud/roles/clickhouse/deploy/tasks/main.yml
  onecloud/roles/clickhouse/install/files/system_logs.xml
  onecloud/roles/clickhouse/install/tasks/main.yml
  onecloud/roles/primary-master-node/setup_k8s/tasks/main.yml
  onecloud/roles/registry/templates/registry.yml
  onecloud/roles/utils/load-images/tasks/main.yml
Labels: size/L

#1393 fix: set clickhouse query_log etc. ttl
  onecloud/roles/clickhouse/install/files/system_logs.xml
  onecloud/roles/clickhouse/install/tasks/main.yml
Labels: size/M

#1394 Automated cherry pick of #1393: fix: set clickhouse query_log etc. ttl
  onecloud/roles/clickhouse/install/files/system_logs.xml
  onecloud/roles/clickhouse/install/tasks/main.yml
Labels: size/M

#1395 Automated cherry pick of #1393: fix: set clickhouse query_log etc. ttl
  onecloud/roles/clickhouse/install/files/system_logs.xml
  onecloud/roles/clickhouse/install/tasks/main.yml
Labels: size/M

#1396 Automated cherry pick of #1393: fix: set clickhouse query_log etc. ttl
  onecloud/roles/clickhouse/install/files/system_logs.xml
  onecloud/roles/clickhouse/install/tasks/main.yml
Labels: size/M

#1397 🐛 fix: Modify the lbagent tasks Ansible playbook file to fix the error cau…
  onecloud/roles/worker-node/lbagent/tasks/main.yml
Labels: size/XS

#1387 fix(k3s): install systemd service by is_k3s_server variable
  onecloud/roles/k3s/airgap/tasks/main.yml
  onecloud/roles/master-node/tasks/k3s.yml
  onecloud/roles/primary-master-node/setup_k3s/tasks/main.yml
  onecloud/roles/worker-node/tasks/k3s.yml
Labels: size/S

#1398 K3s ha endpoint
  generate-ha-config.sh
  lib/ocboot.py
  onecloud/roles/primary-master-node/setup_cloud/templates/onecloud-manifests.yaml.j2
Labels: size/L

#1399 feat: add clickhouse step
  lib/clickhouse.py
  lib/parser.py
  lib/service.py
  ocboot.py
  ocboot.sh
  onecloud/clickhouse-services.yml
Labels: size/L

#1400 Automated cherry pick of #1399: feat: add clickhouse step
  lib/clickhouse.py
  lib/ocboot.py
  lib/parser.py
  lib/service.py
  ocboot.py
  ocboot.sh
  onecloud/clickhouse-services.yml
  onecloud/roles/clickhouse/deploy/tasks/main.yml
Labels: size/L

#1403 feat: release v3.11.9
  VERSION
  charts/cloudpods/values-dev.yaml
  charts/cloudpods/values-prod.yaml
  charts/cloudpods/values.yaml
  compose/baremetal/docker-compose.yml
  compose/docker-compose.yml
  generate-compose.py
Labels: size/L
