Repository yunionio/ocboot, pull requests merged in 2024-05, with the labels that each got.

#1229 fix(backup): 备份失败时，删除以时间戳结尾的空备份路径
  onecloud/roles/utils/auto-backup-services/files/db_backup.sh
Labels: size/XS

#1230 Automated cherry pick of #1229: fix(backup): 备份失败时，删除以时间戳结尾的空备份路径
  onecloud/roles/utils/auto-backup-services/files/db_backup.sh
Labels: size/XS

#1231 Automated cherry pick of #1229: fix(backup): 备份失败时，删除以时间戳结尾的空备份路径
  onecloud/roles/utils/auto-backup-services/files/db_backup.sh
Labels: size/XS

#1232 Automated cherry pick of #1229: fix(backup): 备份失败时，删除以时间戳结尾的空备份路径
  onecloud/roles/utils/auto-backup-services/files/db_backup.sh
Labels: size/XS

#1233 fix(ubuntu): 更新ubuntu/debian软件名模式
  onecloud/roles/common/tasks/os/debian_family.yml
Labels: size/XS

#1234 Automated cherry pick of #1233: fix(ubuntu): 更新ubuntu/debian软件名模式
  onecloud/roles/common/tasks/os/debian_family.yml
Labels: size/XS

#1235 Automated cherry pick of #1233: fix(ubuntu): 更新ubuntu/debian软件名模式
  onecloud/roles/common/tasks/os/debian_family.yml
Labels: size/XS

#1236 Automated cherry pick of #1233: fix(ubuntu): 更新ubuntu/debian软件名模式
  onecloud/roles/common/tasks/os/debian_family.yml
Labels: size/XS

#1237 fix(lbagent): 添加lbagent节点时debian系列不启动openvswitch服务
  onecloud/roles/worker-node/lbagent/tasks/main.yml
Labels: size/XS

#1239 Automated cherry pick of #1237: fix(lbagent): 添加lbagent节点时debian系列不启动openvswitch服务
  onecloud/roles/worker-node/lbagent/tasks/main.yml
Labels: size/XS

#1240 Automated cherry pick of #1237: fix(lbagent): 添加lbagent节点时debian系列不启动openvswitch服务
  onecloud/roles/worker-node/lbagent/tasks/main.yml
Labels: size/XS

#1241 reboot for local and ssh connections
  onecloud/roles/utils/kernel-check/tasks/main.yml
Labels: size/S

#1242 Automated cherry pick of #1241: reboot for local and ssh connections
  onecloud/roles/utils/kernel-check/tasks/main.yml
Labels: size/S

#1243 Automated cherry pick of #1241: reboot for local and ssh connections
  onecloud/roles/utils/kernel-check/tasks/main.yml
Labels: size/S

#1244 Automated cherry pick of #1241: reboot for local and ssh connections
  onecloud/roles/utils/kernel-check/tasks/main.yml
Labels: size/S

#1247 Automated cherry pick of #1246: CE模式默认不安装climc-ee相关rpm/deb
  onecloud/roles/utils/detect-os/tasks/main.yml
  onecloud/roles/utils/detect-os/vars/centos-8.yml
  onecloud/roles/utils/detect-os/vars/debian.yml
  onecloud/roles/utils/detect-os/vars/opencloudos-8.yml
  onecloud/roles/utils/detect-os/vars/openeuler-x86_64.yml
  onecloud/roles/utils/detect-os/vars/uniontech_os_server_20_enterprise-20.aarch64.yml
Labels: size/L

#1248 Automated cherry pick of #1246: CE模式默认不安装climc-ee相关rpm/deb
  onecloud/roles/utils/detect-os/tasks/main.yml
  onecloud/roles/utils/detect-os/vars/centos-8.yml
  onecloud/roles/utils/detect-os/vars/debian.yml
  onecloud/roles/utils/detect-os/vars/opencloudos-8.yml
  onecloud/roles/utils/detect-os/vars/openeuler-x86_64.yml
  onecloud/roles/utils/detect-os/vars/uniontech_os_server_20_enterprise-20.aarch64.yml
Labels: size/L

#1249 Automated cherry pick of #1246: CE模式默认不安装climc-ee相关rpm/deb
  onecloud/roles/utils/detect-os/tasks/main.yml
  onecloud/roles/utils/detect-os/vars/centos-8.yml
  onecloud/roles/utils/detect-os/vars/debian.yml
  onecloud/roles/utils/detect-os/vars/opencloudos-8.yml
  onecloud/roles/utils/detect-os/vars/openeuler-x86_64.yml
  onecloud/roles/utils/detect-os/vars/uniontech_os_server_20_enterprise-20.aarch64.yml
Labels: size/L

#1245 新增buildah安装脚本
  scripts/install-buildah.sh
  scripts/uninstall-k3s.sh
Labels: size/L

#1250 update version to v3.10.15
  VERSION
  compose/docker-compose.yml
Labels: size/M

#1251 在 centos 之外的 os 上不安装kmod-openvswith软件包
  onecloud/roles/utils/detect-os/vars/almalinux-8.yml
  onecloud/roles/utils/detect-os/vars/anolis_os.yml
  onecloud/roles/utils/detect-os/vars/centos-8.yml
  onecloud/roles/utils/detect-os/vars/kylin_linux_advanced_server-v10.aarch64.yml
  onecloud/roles/utils/detect-os/vars/kylin_linux_advanced_server-v10.x86_64.yml
  onecloud/roles/utils/detect-os/vars/opencloudos-8.yml
  onecloud/roles/utils/detect-os/vars/openeuler-aarch64.yml
  onecloud/roles/utils/detect-os/vars/openeuler-x86_64.yml
  onecloud/roles/utils/detect-os/vars/rocky-8.yml
  onecloud/roles/utils/detect-os/vars/uniontech-kongzi.yml
Labels: size/S

#1252 Automated cherry pick of #1251: 在 centos 之外的 os 上不安装kmod-openvswith软件包
  onecloud/roles/utils/detect-os/vars/almalinux-8.yml
  onecloud/roles/utils/detect-os/vars/anolis_os.yml
  onecloud/roles/utils/detect-os/vars/centos-8.yml
  onecloud/roles/utils/detect-os/vars/kylin_linux_advanced_server-v10.aarch64.yml
  onecloud/roles/utils/detect-os/vars/kylin_linux_advanced_server-v10.x86_64.yml
  onecloud/roles/utils/detect-os/vars/opencloudos-8.yml
  onecloud/roles/utils/detect-os/vars/openeuler-aarch64.yml
  onecloud/roles/utils/detect-os/vars/openeuler-x86_64.yml
  onecloud/roles/utils/detect-os/vars/rocky-8.yml
  onecloud/roles/utils/detect-os/vars/uniontech-kongzi.yml
Labels: size/S

#1253 Automated cherry pick of #1251: 在 centos 之外的 os 上不安装kmod-openvswith软件包
  onecloud/roles/utils/detect-os/vars/almalinux-8.yml
  onecloud/roles/utils/detect-os/vars/anolis_os.yml
  onecloud/roles/utils/detect-os/vars/centos-8.yml
  onecloud/roles/utils/detect-os/vars/kylin_linux_advanced_server-v10.aarch64.yml
  onecloud/roles/utils/detect-os/vars/kylin_linux_advanced_server-v10.x86_64.yml
  onecloud/roles/utils/detect-os/vars/opencloudos-8.yml
  onecloud/roles/utils/detect-os/vars/openeuler-aarch64.yml
  onecloud/roles/utils/detect-os/vars/openeuler-x86_64.yml
  onecloud/roles/utils/detect-os/vars/rocky-8.yml
  onecloud/roles/utils/detect-os/vars/uniontech-kongzi.yml
Labels: size/S

#1254 Automated cherry pick of #1251: 在 centos 之外的 os 上不安装kmod-openvswith软件包
  onecloud/roles/utils/detect-os/vars/almalinux-8.yml
  onecloud/roles/utils/detect-os/vars/kylin_linux_advanced_server-v10.aarch64.yml
  onecloud/roles/utils/detect-os/vars/kylin_linux_advanced_server-v10.x86_64.yml
  onecloud/roles/utils/detect-os/vars/opencloudos-8.yml
  onecloud/roles/utils/detect-os/vars/openeuler-x86_64.yml
  onecloud/roles/utils/detect-os/vars/rocky-8.yml
  onecloud/roles/utils/detect-os/vars/uniontech-kongzi.yml
Labels: size/XS

#1255 Automated cherry pick of #1251: 在 centos 之外的 os 上不安装kmod-openvswith软件包
  onecloud/roles/utils/detect-os/vars/kylin_linux_advanced_server-v10.aarch64.yml
  onecloud/roles/utils/detect-os/vars/kylin_linux_advanced_server-v10.x86_64.yml
  onecloud/roles/utils/detect-os/vars/openeuler-x86_64.yml
Labels: size/XS

#1256 minor fix package name pattern
  onecloud/roles/utils/detect-os/vars/latest_packages.yml
Labels: size/XS

#1257 Automated cherry pick of #1256: yunion-climc-ee pattern
  onecloud/roles/utils/detect-os/vars/latest_packages.yml
Labels: size/XS

#1259 Automated cherry pick of #1256: yunion-climc-ee pattern
  onecloud/roles/utils/detect-os/vars/latest_packages.yml
Labels: size/XS

#1258 Automated cherry pick of #1256: yunion-climc-ee pattern
  onecloud/roles/utils/detect-os/vars/latest_packages.yml
Labels: size/XS

#1260 fix(upgrade): 升级变量判断兼容
  lib/upgrade.py
  onecloud/roles/utils/cronjobs/tasks/main.yml
  onecloud/roles/utils/detect-os/vars/almalinux-8.yml
  onecloud/roles/utils/detect-os/vars/anolis_os.yml
  onecloud/roles/utils/detect-os/vars/centos-8.yml
  onecloud/roles/utils/detect-os/vars/opencloudos-8.yml
  onecloud/roles/utils/detect-os/vars/openeuler-x86_64.yml
  onecloud/roles/utils/detect-os/vars/rocky-8.yml
Labels: size/M

#1261 Automated cherry pick of #1260: fix(upgrade): 升级变量判断兼容
  lib/upgrade.py
  onecloud/roles/utils/detect-os/vars/almalinux-8.yml
  onecloud/roles/utils/detect-os/vars/anolis_os.yml
  onecloud/roles/utils/detect-os/vars/centos-8.yml
  onecloud/roles/utils/detect-os/vars/opencloudos-8.yml
  onecloud/roles/utils/detect-os/vars/openeuler-x86_64.yml
  onecloud/roles/utils/detect-os/vars/rocky-8.yml
Labels: size/M

#1262 Automated cherry pick of #1260: fix(upgrade): 升级变量判断兼容
  lib/upgrade.py
  onecloud/roles/utils/detect-os/vars/almalinux-8.yml
  onecloud/roles/utils/detect-os/vars/anolis_os.yml
  onecloud/roles/utils/detect-os/vars/centos-8.yml
  onecloud/roles/utils/detect-os/vars/opencloudos-8.yml
  onecloud/roles/utils/detect-os/vars/openeuler-x86_64.yml
  onecloud/roles/utils/detect-os/vars/rocky-8.yml
Labels: size/M

#1263 Automated cherry pick of #1260: fix(upgrade): 升级变量判断兼容
  lib/upgrade.py
  onecloud/roles/utils/detect-os/vars/almalinux-8.yml
  onecloud/roles/utils/detect-os/vars/anolis_os.yml
  onecloud/roles/utils/detect-os/vars/centos-8.yml
  onecloud/roles/utils/detect-os/vars/opencloudos-8.yml
  onecloud/roles/utils/detect-os/vars/openeuler-x86_64.yml
  onecloud/roles/utils/detect-os/vars/rocky-8.yml
Labels: size/M

#1265 resolve conflicts 312
  onecloud/roles/utils/detect-os/vars/openeuler-x86_64.yml
Labels: size/XS

#1266 resolve conflicts 311
  onecloud/roles/utils/detect-os/vars/openeuler-x86_64.yml
Labels: size/XS

#1267 fix(compose): update compose-service-init to v3.11-0530.0
  compose/docker-compose.yml
  lib/compose/services/cluster_service.py
Labels: size/M

#1268 Automated cherry pick of #1267: fix(compose): update compose-service-init to v3.11-0530.0
  compose/docker-compose.yml
  lib/compose/services/cluster_service.py
Labels: size/M

#1273 addnode: set host_networks if missing
  onecloud/roles/master-node/tasks/k8s.yml
  onecloud/roles/utils/host-service/tasks/main.yml
  onecloud/roles/utils/set-hostnetworks/tasks/main.yml
  onecloud/roles/worker-node/tasks/k8s.yml
Labels: size/M

#1274 addnode: set host_networks if missing 312
  onecloud/roles/master-node/tasks/main.yml
  onecloud/roles/utils/fetch-node-interface/tasks/main.yml
  onecloud/roles/utils/set-hostnetworks/tasks/main.yml
  onecloud/roles/worker-node/tasks/main.yml
Labels: size/M

#1275 Automated cherry pick of #1274: addnode: set host_networks if missing 312
  onecloud/roles/master-node/tasks/main.yml
  onecloud/roles/utils/fetch-node-interface/tasks/main.yml
  onecloud/roles/utils/set-hostnetworks/tasks/main.yml
  onecloud/roles/worker-node/tasks/main.yml
Labels: size/M

#1276 Automated cherry pick of #1274: addnode: set host_networks if missing 312
  onecloud/roles/master-node/tasks/main.yml
  onecloud/roles/utils/fetch-node-interface/tasks/main.yml
  onecloud/roles/utils/set-hostnetworks/tasks/main.yml
  onecloud/roles/worker-node/tasks/main.yml
Labels: size/M

#1269 openeuler version specification
  onecloud/roles/utils/misc-check/tasks/openeuler.yml
Labels: size/XS

#1270 Automated cherry pick of #1269: openeuler version specification
  onecloud/roles/utils/misc-check/tasks/openeuler.yml
Labels: size/XS

#1271 Automated cherry pick of #1269: openeuler version specification
  onecloud/roles/utils/misc-check/tasks/openeuler.yml
Labels: size/XS

#1272 Automated cherry pick of #1269: openeuler version specification
  onecloud/roles/utils/misc-check/tasks/openeuler.yml
Labels: size/XS

#1277 fix(k8s): 解决sweet32 安全漏洞
  onecloud/roles/utils/k8s/kubelet/extra-args/tasks/main.yml
Labels: size/S

#1278 Automated cherry pick of #1277: fix(k8s): 解决sweet32 安全漏洞
  onecloud/roles/utils/k8s/kubelet/extra-args/tasks/main.yml
Labels: size/S

#1279 Automated cherry pick of #1277: fix(k8s): 解决sweet32 安全漏洞
  onecloud/roles/utils/k8s/kubelet/extra-args/tasks/main.yml
Labels: size/S

#1280 Automated cherry pick of #1277: fix(k8s): 解决sweet32 安全漏洞
  onecloud/roles/utils/k8s/kubelet/extra-args/tasks/main.yml
Labels: size/S
