Repository yunionio/ocboot, pull requests merged in 2024-10, with the labels that each got.

#1369 fix(k3s): specify pause-image from image_repository
  onecloud/roles/k3s/config/templates/config.yaml.j2
Labels: size/XS

#1371 fix(upgrade): get cluster current imageRepository when no args provided
  lib/upgrade.py
Labels: size/XS

#1372 Automated cherry pick of #1371: fix(upgrade): get cluster current imageRepository when no args provided
  lib/upgrade.py
Labels: size/XS

#1373 Automated cherry pick of #1371: fix(upgrade): get cluster current imageRepository when no args provided
  lib/upgrade.py
Labels: size/XS

#1374 Automated cherry pick of #1371: fix(upgrade): get cluster current imageRepository when no args provided
  lib/upgrade.py
Labels: size/XS

#1365 fix: upgrade version to 3.11.7
  VERSION
  scripts/package.sh
Labels: size/S

#1366 Automated cherry pick of #1365: fix: upgrade version to 3.11.7
  VERSION
  scripts/package.sh
Labels: size/S

#1367 Automated cherry pick of #1365: fix: upgrade version to 3.11.7
  VERSION
  scripts/package.sh
Labels: size/S

#1368 Automated cherry pick of #1365: fix: upgrade version to 3.11.7
  VERSION
  scripts/package.sh
Labels: size/S

#1375 feat: release v3.11.8
  VERSION
  charts/cloudpods/values-dev.yaml
  charts/cloudpods/values-prod.yaml
  charts/cloudpods/values.yaml
  compose/docker-compose.yml
  generate-compose.py
Labels: size/L

#1376 Automated cherry pick of #1375: feat: release v3.11.8
  VERSION
  charts/cloudpods/values-dev.yaml
  charts/cloudpods/values-prod.yaml
  charts/cloudpods/values.yaml
  compose/docker-compose.yml
  generate-compose.py
Labels: size/L

#1377 Automated cherry pick of #1375: feat: release v3.11.8
  VERSION
  charts/cloudpods/values-dev.yaml
  charts/cloudpods/values-prod.yaml
  charts/cloudpods/values.yaml
  compose/docker-compose.yml
  generate-compose.py
Labels: size/L

#1353 feat: use k3s as cluster defaultly
  lib/cluster.py
  lib/consts.py
  lib/k3s.py
  lib/ocboot.py
  lib/service.py
  lib/upgrade.py
  ocboot.sh
  onecloud/roles/k3s/k3s_server/tasks/main.yml
  onecloud/roles/upgrade/primary_master_node/tasks/main.yml
  onecloud/roles/utils/detect-os/tasks/main.yml
  run.py
Labels: size/L, do-not-merge/hold

#1380 fix: raise Exception
  lib/k3s.py
Labels: size/XS
