Repository yunionio/ocboot, pull requests merged in 2024-06, with the labels that each got.

#1281 ocboot 在线安装时centos repo文件逻辑变更 3.10+
  onecloud/roles/common/tasks/main.yml
  onecloud/roles/common/tasks/v3_10_offline.yml
  onecloud/roles/common/tasks/v3_10_online.yml
  onecloud/roles/common/tasks/v3_11_online.yml
Labels: size/M

#1282 Automated cherry pick of #1281: 在线安装时centos repo文件逻辑变更 3.10+
  onecloud/roles/common/tasks/main.yml
  onecloud/roles/common/tasks/v3_10_offline.yml
Labels: size/S

#1283 Automated cherry pick of #1281: 在线安装时centos repo文件逻辑变更 3.10+
  onecloud/roles/common/tasks/main.yml
  onecloud/roles/common/tasks/v3_10_offline.yml
  onecloud/roles/common/tasks/v3_10_online.yml
Labels: size/S

#1284 Automated cherry pick of #1281: 在线安装时centos repo文件逻辑变更 3.10+
  onecloud/roles/common/tasks/main.yml
  onecloud/roles/common/tasks/v3_10_offline.yml
  onecloud/roles/common/tasks/v3_10_online.yml
Labels: size/S

#1285 fix(adm0): 对于fullstack和edge忽略adm0报错
  onecloud/roles/primary-master-node/setup_cloud/tasks/main.yml
Labels: size/M

#1286 Automated cherry pick of #1285: fix(adm0): 对于fullstack和edge忽略adm0报错
  onecloud/roles/primary-master-node/setup_cloud/tasks/main.yml
Labels: size/M

#1287 Automated cherry pick of #1285: fix(adm0): 对于fullstack和edge忽略adm0报错
  onecloud/roles/primary-master-node/setup_cloud/tasks/main.yml
Labels: size/M

#1288 Automated cherry pick of #1285: fix(adm0): 对于fullstack和edge忽略adm0报错
  onecloud/roles/primary-master-node/setup_cloud/tasks/main.yml
Labels: size/M

#1290 Automated cherry pick of #1289: feat: update version to v3.11.4
  charts/cloudpods/values-dev.yaml
  charts/cloudpods/values-prod.yaml
  charts/cloudpods/values.yaml
  compose/docker-compose.yml
  generate-compose.py
Labels: size/M

#1291 Automated cherry pick of #1289: feat: update version to v3.11.4
  charts/cloudpods/values-dev.yaml
  charts/cloudpods/values-prod.yaml
  charts/cloudpods/values.yaml
  compose/docker-compose.yml
  generate-compose.py
Labels: size/M

#1292 fix(centos): fix centos repo url issue
  onecloud/roles/common/tasks/os/centos_7.yml
Labels: size/XS

#1293 Automated cherry pick of #1292: fix(centos): fix centos repo url issue
  onecloud/roles/common/tasks/os/centos_7.yml
Labels: size/XS

#1294 Automated cherry pick of #1292: fix(centos): fix centos repo url issue
  onecloud/roles/common/tasks/os/centos_7.yml
Labels: size/XS

#1295 update compose service version
  compose/docker-compose.yml
  lib/compose/services/cluster_service.py
Labels: size/M

#1296 Automated cherry pick of #1295: update compose service version
  compose/docker-compose.yml
  lib/compose/services/cluster_service.py
Labels: size/M

#1297 Automated cherry pick of #1295: update compose service version
  compose/docker-compose.yml
  lib/compose/services/cluster_service.py
Labels: size/M

#1298 update VERSION to v3.11.4
  Makefile
  VERSION
Labels: size/XS

#1299 Automated cherry pick of #1298: update VERSION to v3.11.4
  Makefile
  VERSION
Labels: size/XS

#1300 Automated cherry pick of #1298: update VERSION to v3.11.4
  Makefile
  VERSION
Labels: size/XS

#1264 fix(k3s): add-node 流程跑通
  lib/ocboot.py
  lib/upgrade.py
  onecloud/roles/common/tasks/main.yml
  onecloud/roles/common/tasks/os/debian_10.yml
  onecloud/roles/common/tasks/os/debian_family.yml
  onecloud/roles/common/tasks/utils/unified_cgroup_hierarchy.yml
  onecloud/roles/primary-master-node/setup_cloud/tasks/main.yml
  onecloud/roles/primary-master-node/setup_cloud/templates/wait-onecloud-services.sh.j2
  onecloud/roles/upgrade/controllable/primary_master_node/tasks/check-and-wait.yml
  onecloud/roles/upgrade/controllable/primary_master_node/tasks/main.yml
  onecloud/roles/upgrade/controllable/primary_master_node/tasks/wait-for-all-pods-running.yml
  onecloud/roles/upgrade/controllable/worker_nodes/tasks/main.yml
  onecloud/roles/upgrade/primary_master_node/tasks/main.yml
  onecloud/roles/utils/auto-backup-services/files/db_backup.sh
  onecloud/roles/utils/ce-services/tasks/main.yml
  onecloud/roles/utils/detect-os/tasks/main.yml
  onecloud/roles/utils/ee-services/tasks/main.yml
  onecloud/roles/utils/enable-eip/tasks/main.yml
  onecloud/roles/utils/k8s/addons/patch/tasks/main.yml
Labels: size/L

#1301 feat: generate baremetal compose file
  .gitignore
  Makefile
  generate-compose.py
  lib/compose/manifest/__init__.py
  lib/compose/object.py
  lib/compose/options.py
  lib/compose/services/__init__.py
  lib/compose/services/baremetal.py
  lib/compose/services/cluster_service.py
  lib/compose/services/dhcp_relay.py
  lib/compose/services/host_deployer.py
Labels: size/L

#1303 Automated cherry pick of #1301: feat: generate baremetal compose file
  .gitignore
  Makefile
  generate-compose.py
  lib/compose/manifest/__init__.py
  lib/compose/object.py
  lib/compose/options.py
  lib/compose/services/__init__.py
  lib/compose/services/baremetal.py
  lib/compose/services/cluster_service.py
  lib/compose/services/dhcp_relay.py
  lib/compose/services/host_deployer.py
Labels: size/L

#1302 Feature/rex add node with containerd backend
  lib/add_node.py
  lib/parser.py
  lib/service.py
  onecloud/add-node.yml
  onecloud/roles/common/tasks/master_online.yml
  onecloud/roles/common/tasks/utils/fix_ovmf_path.yml
  onecloud/roles/common/tasks/utils/unified_cgroup_hierarchy.yml
  onecloud/roles/utils/containerd/files/10-ocnet-cni.conflist
  onecloud/roles/utils/containerd/files/config.toml
  onecloud/roles/utils/containerd/files/yunion-containerd.service
  onecloud/roles/utils/containerd/handlers/main.yml
  onecloud/roles/utils/containerd/tasks/config-host.yml
  onecloud/roles/utils/containerd/tasks/ensure-binaries.yml
  onecloud/roles/utils/containerd/tasks/ensure-services.yml
  onecloud/roles/utils/containerd/tasks/main.yml
  onecloud/roles/utils/containerd/vars/defaults.yml
  onecloud/roles/utils/detect-os/tasks/main.yml
  onecloud/roles/utils/detect-os/vars/debian.yml
  onecloud/roles/utils/detect-os/vars/latest_packages.yml
Labels: size/XL

#1306 feat: baremetal compose file
  .gitignore
  Makefile
  compose/baremetal/docker-compose.yml
Labels: size/XXL

#1308 feat: baremetal compose file
  compose/baremetal/docker-compose.yml
  lib/compose/object.py
  lib/compose/services/__init__.py
  lib/compose/services/baremetal.py
  lib/compose/services/cluster_service.py
  lib/compose/services/host_deployer.py
Labels: size/L

#1309 feat: baremetal compose file
  compose/baremetal/docker-compose.yml
  lib/compose/services/cluster_service.py
Labels: size/M

#1310 Automated cherry pick of #1309: feat: baremetal compose file
  compose/docker-compose.yml
  lib/compose/services/cluster_service.py
Labels: size/L

#1311 Automated cherry pick of #1309: feat: baremetal compose file
  compose/docker-compose.yml
  lib/compose/services/cluster_service.py
Labels: size/L

#1313 Automated cherry pick of #1312: fix(compose): resolve conflict
  compose/docker-compose.yml
Labels: size/L

#1314 Automated cherry pick of #1312: fix(compose): resolve conflict
  compose/docker-compose.yml
Labels: size/L

#1307 ocboot upgrade for both k8s and k3s
  ocboot.sh
  onecloud/roles/primary-master-node/setup_cloud/tasks/main.yml
  onecloud/roles/upgrade/primary_master_node/tasks/main.yml
  onecloud/roles/upgrade/primary_master_node/templates/turn-off-operator-clear-component.patch.yml.j2
  onecloud/roles/upgrade/primary_master_node/templates/turn-on-operator-clear-component.patch.yml.j2
  onecloud/roles/utils/onecloud-waiter/tasks/main.yml
  onecloud/roles/utils/onecloud-waiter/templates/wait-onecloud-services.sh.j2
  run.py
Labels: size/L

#1305 debian 12 compatibilities
  lib/ocboot.py
  onecloud/roles/common/tasks/main.yml
  onecloud/roles/common/tasks/os/debian_12.yml
  onecloud/roles/mariadb/tasks/main.yml
  onecloud/roles/utils/misc-check/tasks/debian.yml
Labels: size/M
