Repository yunionio/ocboot, pull requests merged in 2025-08, with the labels that each got.

#1474 Automated cherry pick of #1455: feat: ipv6 support
  lib/add_node.py
  lib/consts.py
  lib/get_interface_by_ip.py
  lib/ocboot.py
  lib/parser.py
  onecloud/roles/k3s/config/templates/config.yaml.j2
  onecloud/roles/k3s/config/templates/keepalived.yaml.j2
  onecloud/roles/k3s/k3s_agent/tasks/main.yml
  onecloud/roles/k3s/k3s_agent/templates/k3s-agent.service.j2
  onecloud/roles/k3s/k3s_server/templates/k3s-ha.service.j2
  onecloud/roles/k3s/prereq/tasks/main.yml
  onecloud/roles/primary-master-node/setup_cloud/tasks/main.yml
  onecloud/roles/primary-master-node/setup_cloud/templates/onecloud-manifests.yaml.j2
  onecloud/roles/primary-master-node/setup_k3s/templates/calico.yaml.j2
  onecloud/roles/utils/fetch-node-interface/tasks/main.yml
  onecloud/roles/utils/set-hostnetworks/tasks/main.yml
  onecloud/roles/worker-node/lbagent/tasks/main.yml
  run.py
Labels: size/XL

#1477 Automated cherry pick of #1475: fix: ipv6 high availability
  lib/ocboot.py
  onecloud/roles/k3s/config/templates/config.yaml.j2
  onecloud/roles/primary-master-node/setup_k3s/templates/calico.yaml.j2
Labels: size/S

#1480 Automated cherry pick of #1478: fix: openeuler 22.03 LTS SP4 support
  onecloud/roles/common/tasks/os/openeuler-repo.yml
  onecloud/roles/common/tasks/os/openeuler_22.yml
  onecloud/roles/common/tasks/os/openeuler_24.yml
  onecloud/roles/utils/misc-check/tasks/openeuler.yml
  run.py
Labels: size/M

#1481 fix: fail to push plain http insecure registry
  onecloud/roles/primary-master-node/setup_k3s/tasks/main.yml
  onecloud/roles/utils/detect-os/vars/debian.yml
  onecloud/roles/utils/detect-os/vars/latest_packages.yml
  onecloud/roles/utils/detect-os/vars/ubuntu-20.x86_64.yml
  onecloud/roles/utils/detect-os/vars/ubuntu-22.x86_64.yml
  onecloud/roles/utils/detect-os/vars/uniontech-kongzi.yml
  onecloud/roles/utils/detect-os/vars/uniontech_os_server_20-fou.yml
  onecloud/roles/utils/detect-os/vars/uniontech_os_server_20_enterprise-20.aarch64.yml
  onecloud/roles/utils/detect-os/vars/uniontech_os_server_20_enterprise-20.x86_64.yml
Labels: size/S

#1483 Automated cherry pick of #1481: fix: fail to push plain http insecure registry
  onecloud/roles/primary-master-node/setup_k3s/tasks/main.yml
  onecloud/roles/utils/detect-os/vars/debian.yml
  onecloud/roles/utils/detect-os/vars/latest_packages.yml
  onecloud/roles/utils/detect-os/vars/ubuntu-20.x86_64.yml
  onecloud/roles/utils/detect-os/vars/ubuntu-22.x86_64.yml
  onecloud/roles/utils/detect-os/vars/uniontech-kongzi.yml
  onecloud/roles/utils/detect-os/vars/uniontech_os_server_20-fou.yml
  onecloud/roles/utils/detect-os/vars/uniontech_os_server_20_enterprise-20.aarch64.yml
  onecloud/roles/utils/detect-os/vars/uniontech_os_server_20_enterprise-20.x86_64.yml
Labels: size/S

#1482 Automated cherry pick of #1481: fix: fail to push plain http insecure registry
  onecloud/roles/primary-master-node/setup_k3s/tasks/main.yml
  onecloud/roles/utils/detect-os/vars/debian.yml
  onecloud/roles/utils/detect-os/vars/latest_packages.yml
  onecloud/roles/utils/detect-os/vars/ubuntu-20.x86_64.yml
  onecloud/roles/utils/detect-os/vars/ubuntu-22.x86_64.yml
  onecloud/roles/utils/detect-os/vars/uniontech-kongzi.yml
  onecloud/roles/utils/detect-os/vars/uniontech_os_server_20-fou.yml
  onecloud/roles/utils/detect-os/vars/uniontech_os_server_20_enterprise-20.aarch64.yml
  onecloud/roles/utils/detect-os/vars/uniontech_os_server_20_enterprise-20.x86_64.yml
Labels: size/S

#1485 fix: install private registry record
  onecloud/roles/clickhouse/install/tasks/main.yml
  onecloud/roles/common/tasks/main.yml
  onecloud/roles/utils/detect-os/vars/openeuler-aarch64.yml
  onecloud/roles/utils/detect-os/vars/openeuler-x86_64.yml
Labels: size/M

#1489 Automated cherry pick of #1488: fix: update keepalived_version_tag to v2.0.29 to support ipv6
  lib/ocboot.py
Labels: size/XS

#1490 Automated cherry pick of #1488: fix: update keepalived_version_tag to v2.0.29 to support ipv6
  lib/ocboot.py
Labels: size/XS

#1491 Automated cherry pick of #1488: fix: update keepalived_version_tag to v2.0.29 to support ipv6
  lib/ocboot.py
Labels: size/XS

#1492 fix: private-registry.onecloud as insecure registry
  onecloud/roles/k3s/config/templates/registries.yaml.j2
  onecloud/roles/utils/detect-os/vars/openeuler-aarch64.yml
  onecloud/roles/utils/detect-os/vars/openeuler-x86_64.yml
Labels: size/XS
